[package]
name = "csr"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web = { path = "../web", default-features = false, features = ["csr"] }
client = { path = "../client" }
leptos = { workspace = true, features = [ "csr" ] }

common.workspace = true
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
