[mcp_servers.context7]
args = []
command = "context7-mcp"
type = "stdio"

[mcp_servers.context7.env]
[mcp_servers.git]
args = []
command = "mcp-server-git"
type = "stdio"

[mcp_servers.git.env]
[mcp_servers.playwright]
args = []
command = "mcp-server-playwright"
type = "stdio"

[mcp_servers.playwright.env]
[mcp_servers.serena]
args = [ "start-mcp-server", "--context", "ide-assistant", "--enable-web-dashboard", "false", "--project", "." ]
command = "serena"
type = "stdio"

[mcp_servers.serena.env]
