use common::content_license::ContentLicense;
use common::ids::{AudienceId, PostId, SubscriptionId, UserId};
use common::media::MediaSource;
use common::post_title::PostTitle;
use common::slug::Slug;
use common::tagged_url::HubUrl;
use common::test_support::{
    parse_audience_name, parse_byte_size, parse_content_hash, parse_content_type,
    parse_display_name, parse_filename,
};
use common::time::UtcInstant;
use common::username::Username;
use common::visibility::{AudienceTarget, ViewerIdentity};
use host::config_key::UserConfigKey;
use host::passkey::Credential;
use host::password::Password;
use jaunder::cli::StorageArgs;
use serde_json::Value;
use sqlx::{postgres::PgPoolOptions, sqlite::SqlitePoolOptions};
use std::sync::Arc;
use storage::test_support::{
    SeedRawPost, confirmed_for, fp, passkey_credential_fixture, seed_local_subscription,
};
use storage::{
    HubMutationOutcome, MediaRecord, OperatorStatus, PasskeyCredentialId, PasskeyLabel,
    PasskeyUserHandle, PublisherGeneration, StorageRuntimeConfig, open_existing_database,
};

/// SHA-256 the media-table fixture row is keyed by; any stable value works, since
/// the media *files* are mirrored separately from the media *table*.
const FIXTURE_MEDIA_SHA256: &str =
    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

/// Identifiers returned by [`populate_backup_fixture`] so
/// [`assert_backup_fixture_restored`] can check non-author visibility fidelity
/// (a `Named`-audience post must survive restore visible to its subscriber, not
/// silently Private — the bug in issue #4).
pub struct BackupFixtureIds {
    /// The operator who authors the fixture posts and owns the audience.
    pub author: UserId,
    /// A second, non-operator account subscribed to the author and a member of
    /// the `Named` audience — the viewer who must still see the private post.
    pub viewer: UserId,
    /// A `Public` post (visible to everyone, including anonymous).
    pub public_post: PostId,
    /// The public post's autogenerated slug and title, read back by
    /// [`assert_backup_fixture_restored`] instead of a hardcoded literal (both now
    /// autogenerate; only `published_at` stays a fixed contract).
    pub public_post_slug: Slug,
    pub public_post_title: PostTitle,
    /// A post targeted at a `Named` audience the viewer belongs to.
    pub named_post: PostId,
    /// The named audience assigned to `named_post` and containing `viewer`.
    pub audience: AudienceId,
    /// The subscription linking `viewer` to `author`, used by the audience member.
    pub subscription: SubscriptionId,
    /// The publisher generation, advanced from its migration-seeded value to prove
    /// backup and restore replace the target singleton row.
    pub publisher_generation: PublisherGeneration,
    pub passkey_user_handle: PasskeyUserHandle,
    /// The durable Passkey created for the author and verified after restore.
    pub passkey_credential_id: PasskeyCredentialId,
    pub passkey_label: PasskeyLabel,
    pub passkey_serialization: Value,
    pub passkey_created_at: UtcInstant,
    pub passkey_last_used_at: UtcInstant,
}

/// Fixed microsecond-precision publish time: deterministic and safe from
/// Postgres's µs quantization, so a restored value can be asserted exactly (DEC-D).
pub fn fixture_published_at() -> UtcInstant {
    "2026-04-29T12:34:56.789012Z"
        .parse()
        .expect("valid fixture timestamp")
}

/// A credential whose serialized counter and backup-state values are both
/// non-default, so a backup cannot silently omit either value.
fn backup_passkey_credential() -> Credential {
    let mut serialized =
        serde_json::to_value(passkey_credential_fixture()).expect("serialize passkey fixture");
    let credential = serialized
        .get_mut("cred")
        .and_then(Value::as_object_mut)
        .expect("passkey fixture credential fields");
    credential.insert("backup_eligible".to_owned(), Value::Bool(true));
    credential.insert("backup_state".to_owned(), Value::Bool(true));
    Credential::deserialize_for_test(&serialized.to_string())
        .expect("passkey fixture with backup state decodes")
}

fn fixture_passkey_created_at() -> UtcInstant {
    "2026-09-12T13:14:15.123456Z"
        .parse()
        .expect("valid Passkey fixture created time")
}

fn fixture_passkey_last_used_at() -> UtcInstant {
    "2026-09-12T13:15:16.234567Z"
        .parse()
        .expect("valid Passkey fixture last-used time")
}

/// Timestamps are fixed at microsecond precision because the interop fixture
/// traverses both backends and `PostgreSQL` quantizes timestamps to microseconds.
async fn set_backup_passkey_timestamps(args: &StorageArgs, credential_id: &PasskeyCredentialId) {
    let created_at = fixture_passkey_created_at();
    let last_used_at = fixture_passkey_last_used_at();
    match &args.db {
        storage::DbConnectOptions::Sqlite(options) => {
            let pool = SqlitePoolOptions::new()
                .connect_with(options.clone())
                .await
                .expect("connect SQLite for Passkey fixture timestamps");
            sqlx::query(
                "UPDATE passkey_credentials SET created_at = $1, last_used_at = $2 \
                 WHERE credential_id = $3",
            )
            .bind(created_at)
            .bind(last_used_at)
            .bind(credential_id)
            .execute(&pool)
            .await
            .expect("set SQLite Passkey fixture timestamps");
        }
        storage::DbConnectOptions::Postgres { options, .. } => {
            let pool = PgPoolOptions::new()
                .connect_with(options.clone())
                .await
                .expect("connect PostgreSQL for Passkey fixture timestamps");
            sqlx::query(
                "UPDATE passkey_credentials SET created_at = $1, last_used_at = $2 \
                 WHERE credential_id = $3",
            )
            .bind(created_at)
            .bind(last_used_at)
            .bind(credential_id)
            .execute(&pool)
            .await
            .expect("set PostgreSQL Passkey fixture timestamps");
        }
    }
}

/// Immutable pre-Jiff NDJSON spelling captured from the deployed Chrono backup
/// format. It deliberately differs from Jiff's public `Z` rendering.
const PRE_JIFF_BACKUP_PUBLISHED_AT_BYTES: &[u8] = b"2026-04-29T12:34:56.789012+00:00";

pub fn assert_exported_backup_timestamp_bytes(backup_path: &std::path::Path) {
    let rows = std::fs::read(backup_path.join("db").join("posts.ndjson"))
        .expect("read exported post rows");
    assert!(
        rows.windows(PRE_JIFF_BACKUP_PUBLISHED_AT_BYTES.len())
            .any(|bytes| bytes == PRE_JIFF_BACKUP_PUBLISHED_AT_BYTES),
        "export must retain the established timestamp bytes; rows: {}",
        String::from_utf8_lossy(&rows)
    );
}

/// Rewrites the exported post field from an independently stored pre-Jiff
/// literal before restore. The complete current-schema archive supplies its
/// generated schema checksum and table set, while this input is deliberately
/// not sourced from the current exporter.
pub fn make_pre_jiff_backup_fixture(backup_path: &std::path::Path) {
    let rows_path = backup_path.join("db").join("posts.ndjson");
    let rows = std::fs::read_to_string(&rows_path).expect("read exported post rows");
    let mut rewritten = 0;
    let rows = rows
        .lines()
        .map(|line| {
            let mut row: serde_json::Value = serde_json::from_str(line).expect("parse post row");
            if row["published_at"].is_string() {
                row["published_at"] = serde_json::json!(
                    std::str::from_utf8(PRE_JIFF_BACKUP_PUBLISHED_AT_BYTES)
                        .expect("pre-Jiff timestamp is UTF-8")
                );
                rewritten += 1;
            }
            serde_json::to_string(&row).expect("serialize pre-Jiff post row")
        })
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        rewritten >= 2,
        "fixture must contain both public and Named post timestamps"
    );
    std::fs::write(rows_path, format!("{rows}\n")).expect("write pre-Jiff post rows");
    assert_exported_backup_timestamp_bytes(backup_path);

    let manifest_path = backup_path.join("manifest.json");
    let mut manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(&manifest_path).expect("read manifest"))
            .expect("parse manifest");
    manifest
        .as_object_mut()
        .expect("manifest object")
        .remove("format_version");
    std::fs::write(
        manifest_path,
        serde_json::to_vec_pretty(&manifest).expect("serialize pre-Jiff manifest"),
    )
    .expect("write pre-Jiff manifest");
}

/// Replaces the Named-audience post timestamp in a backup table row with a
/// value beyond Jiff's supported range. The public post remains first and
/// readable, making the decoder boundary observable row-by-row.
pub fn replace_named_post_timestamp_with_out_of_range(
    backup_path: &std::path::Path,
    public_post: PostId,
    named_post: PostId,
) {
    let rows_path = backup_path.join("db").join("posts.ndjson");
    let rows = std::fs::read_to_string(&rows_path).expect("read exported post rows");
    let public_post = serde_json::to_value(public_post).expect("serialize public post id");
    let named_post = serde_json::to_value(named_post).expect("serialize named post id");
    let mut public_index = None;
    let mut named_index = None;
    let rows = rows
        .lines()
        .enumerate()
        .map(|(index, line)| {
            let mut row: serde_json::Value = serde_json::from_str(line).expect("parse post row");
            if row["post_id"] == public_post {
                public_index = Some(index);
            }
            if row["post_id"] == named_post {
                row["published_at"] = serde_json::json!("10000-01-01T00:00:00+00:00");
                named_index = Some(index);
            }
            serde_json::to_string(&row).expect("serialize post row")
        })
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        public_index < named_index,
        "supported post row must precede the out-of-range post row"
    );
    std::fs::write(rows_path, format!("{rows}\n")).expect("write modified post rows");
}

pub fn assert_fixture_timestamp_meaning(instant: UtcInstant) {
    let rendered = instant.to_string();
    assert_eq!(rendered, "2026-04-29T12:34:56.789012Z");
    assert_eq!(&rendered[..10], "2026-04-29", "civil date");
    assert_eq!(&rendered[20..26], "789012", "microsecond precision");
    assert!(rendered.ends_with('Z'), "UTC timezone meaning");
}

/// Shows a valid backup row remains readable until a later out-of-range row is
/// decoded through the normal storage query path.
pub async fn assert_supported_post_precedes_out_of_range_post(
    args: &StorageArgs,
    ids: &BackupFixtureIds,
) {
    let factory = open_existing_database(&args.db, &StorageRuntimeConfig::default())
        .await
        .expect("open restored database");
    let posts = factory.posts();
    assert!(
        posts
            .get_post_by_id(ids.public_post, &ViewerIdentity::local(ids.author))
            .await
            .expect("decode supported preceding post row")
            .is_some(),
        "supported row preceding the out-of-range row must remain readable"
    );
    posts
        .get_post_by_id(ids.named_post, &ViewerIdentity::local(ids.viewer))
        .await
        .expect_err("decoding the out-of-range post row must fail");
}

pub async fn populate_backup_fixture(args: &StorageArgs) -> BackupFixtureIds {
    let factory = open_existing_database(&args.db, &storage::StorageRuntimeConfig::default())
        .await
        .expect("open database");
    let write_scope = factory.write_scope();
    let publisher_generation =
        configure_backup_publisher(factory.publisher(), write_scope.clone()).await;
    let (author, password) = create_backup_author(factory.users(), write_scope.clone()).await;
    let passkey = seed_backup_passkey(args, factory.passkeys(), write_scope.clone(), author).await;
    let public = SeedRawPost::new(author)
        .published_at(fixture_published_at())
        .tags(["Backup-Test"])
        .seed(factory.posts(), write_scope.clone())
        .await;
    seed_historical_permalink_alias(args, public.post_id, author).await;
    let (viewer, audience, subscription, named_post) = seed_named_audience_post(
        factory.users(),
        factory.subscriptions(),
        factory.audiences(),
        factory.posts(),
        write_scope.clone(),
        author,
        &password,
    )
    .await;
    seed_side_tables(
        factory.user_config(),
        factory.media(),
        factory.feed_events(),
        write_scope,
        author,
    )
    .await;
    std::fs::write(args.storage_path.join("media").join("avatar.txt"), "media")
        .expect("write media");
    BackupFixtureIds {
        author,
        viewer,
        public_post: public.post_id,
        public_post_slug: public.slug,
        public_post_title: public.title,
        named_post,
        audience,
        subscription,
        publisher_generation,
        passkey_user_handle: passkey.user_handle,
        passkey_credential_id: passkey.credential_id,
        passkey_label: passkey.label,
        passkey_serialization: passkey.serialization,
        passkey_created_at: passkey.created_at,
        passkey_last_used_at: passkey.last_used_at,
    }
}

async fn seed_historical_permalink_alias(args: &StorageArgs, post_id: PostId, user_id: UserId) {
    match &args.db {
        storage::DbConnectOptions::Sqlite(options) => {
            let pool = SqlitePoolOptions::new()
                .connect_with(options.clone())
                .await
                .expect("connect SQLite for Historical Post Permalink Alias fixture");
            sqlx::query(
                "INSERT INTO post_permalink_aliases
                 (post_id, user_id, permalink_date, slug)
                 VALUES ($1, $2, '2025-01-02', 'historical-backup-alias')",
            )
            .bind(post_id)
            .bind(user_id)
            .execute(&pool)
            .await
            .expect("seed SQLite Historical Post Permalink Alias fixture");
        }
        storage::DbConnectOptions::Postgres { options, .. } => {
            let pool = PgPoolOptions::new()
                .connect_with(options.clone())
                .await
                .expect("connect PostgreSQL for Historical Post Permalink Alias fixture");
            sqlx::query(
                "INSERT INTO post_permalink_aliases
                 (post_id, user_id, permalink_date, slug)
                 VALUES ($1, $2, '2025-01-02', 'historical-backup-alias')",
            )
            .bind(post_id)
            .bind(user_id)
            .execute(&pool)
            .await
            .expect("seed PostgreSQL Historical Post Permalink Alias fixture");
        }
    }
}

async fn configure_backup_publisher(
    publisher: Arc<dyn storage::PublisherStorage>,
    write_scope: storage::WriteScope,
) -> PublisherGeneration {
    let hub: HubUrl = "https://hub.example.test/"
        .parse()
        .expect("valid fixture WebSub hub");
    let publisher_mutation = confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move { publisher.mutate_hub(transaction, Some(hub)).await })
            })
            .await
            .expect("configure fixture WebSub hub"),
        "configure fixture WebSub hub",
    );
    match publisher_mutation {
        HubMutationOutcome::Changed { generation } => generation,
        HubMutationOutcome::Unchanged { .. } => panic!("initial WebSub hub must change"),
    }
}

async fn create_backup_author(
    users: Arc<dyn storage::UserStorage>,
    write_scope: storage::WriteScope,
) -> (UserId, Password) {
    let username: Username = "backupuser".parse().expect("valid username");
    let password: Password = "password123".parse().expect("valid password");
    let display_name = parse_display_name("Backup User");
    let password_for_author = storage::prepare_password(password.clone())
        .await
        .expect("prepare author password");
    let outcome = write_scope
        .run(move |transaction| {
            Box::pin(async move {
                users
                    .create_user(
                        transaction,
                        &username,
                        &password_for_author,
                        Some(&display_name),
                        OperatorStatus::OPERATOR,
                    )
                    .await
            })
        })
        .await
        .expect("create user");
    (confirmed_for(outcome, "backup fixture user"), password)
}

struct BackupPasskeyFixture {
    user_handle: PasskeyUserHandle,
    credential_id: PasskeyCredentialId,
    label: PasskeyLabel,
    serialization: Value,
    created_at: UtcInstant,
    last_used_at: UtcInstant,
}

async fn seed_backup_passkey(
    args: &StorageArgs,
    passkeys: Arc<dyn storage::PasskeyStorage>,
    write_scope: storage::WriteScope,
    author: UserId,
) -> BackupPasskeyFixture {
    let credential = backup_passkey_credential();
    let credential_id = PasskeyCredentialId::from_credential(&credential);
    let label: PasskeyLabel = "Backup corpus Passkey"
        .parse()
        .expect("valid passkey fixture label");
    let passkeys_for_insert = Arc::clone(&passkeys);
    let credential_for_insert = credential.clone();
    let label_for_insert = label.clone();
    confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move {
                    passkeys_for_insert
                        .insert_credential(
                            transaction,
                            author,
                            &label_for_insert,
                            &credential_for_insert,
                        )
                        .await
                })
            })
            .await
            .expect("insert backup fixture passkey"),
        "insert backup fixture passkey",
    );
    set_backup_passkey_timestamps(args, &credential_id).await;
    let passkey = passkeys
        .credential(&credential_id)
        .await
        .expect("read backup fixture passkey")
        .expect("inserted backup fixture passkey");
    let user_handle = passkeys
        .user_handle(author)
        .await
        .expect("read backup fixture Passkey handle")
        .expect("backup fixture user has a Passkey handle");
    BackupPasskeyFixture {
        user_handle,
        credential_id,
        label,
        serialization: serde_json::to_value(&passkey.credential)
            .expect("serialize backup fixture passkey"),
        created_at: passkey.created_at,
        last_used_at: passkey
            .last_used_at
            .expect("used backup fixture passkey has last-used time"),
    }
}

/// Seeds a non-author subscriber and a `Named`-audience post they belong to,
/// returning `(viewer_id, audience_id, subscription_id, named_post_id)`. These visibility rows
/// (`subscriptions`, `audiences`, `audience_members`, `post_audiences`) must
/// survive restore so the subscriber still resolves the private post (issue #4).
async fn seed_named_audience_post(
    users: Arc<dyn storage::UserStorage>,
    subscriptions: Arc<dyn storage::SubscriptionStorage>,
    audiences: Arc<dyn storage::AudienceStorage>,
    posts: Arc<dyn storage::PostStorage>,
    write_scope: storage::WriteScope,
    author: UserId,
    password: &Password,
) -> (UserId, AudienceId, SubscriptionId, PostId) {
    let viewer_name: Username = "viewer".parse().expect("valid username");
    let display_name = parse_display_name("Viewer");
    let password = storage::prepare_password(password.clone())
        .await
        .expect("prepare viewer password");
    let outcome = write_scope
        .run(move |transaction| {
            Box::pin(async move {
                users
                    .create_user(
                        transaction,
                        &viewer_name,
                        &password,
                        Some(&display_name),
                        OperatorStatus::STANDARD,
                    )
                    .await
            })
        })
        .await
        .expect("create viewer");
    let viewer = confirmed_for(outcome, "backup fixture viewer");
    let subscription =
        seed_local_subscription(subscriptions, write_scope.clone(), author, viewer).await;
    let audience_name = parse_audience_name("friends");
    let audience_storage = Arc::clone(&audiences);
    let audience = confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move {
                    audience_storage
                        .create_audience(transaction, author, &audience_name)
                        .await
                })
            })
            .await
            .expect("create audience"),
        "backup fixture audience",
    );
    let audiences = Arc::clone(&audiences);
    confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move {
                    audiences
                        .add_member(transaction, author, audience, subscription)
                        .await
                })
            })
            .await
            .expect("add audience member"),
        "backup fixture audience membership",
    );
    let named_post = SeedRawPost::new(author)
        .published_at(fixture_published_at())
        .audiences(vec![AudienceTarget::Named(audience)])
        .seed(posts, write_scope)
        .await
        .post_id;
    (viewer, audience, subscription, named_post)
}

/// Seeds the side tables: a `user_config` row, a media-table row, and a
/// `feed_events` row.
async fn seed_side_tables(
    user_config: Arc<dyn storage::UserConfigStorage>,
    media: Arc<dyn storage::MediaStorage>,
    feed_events: Arc<dyn storage::FeedEventStorage>,
    write_scope: storage::WriteScope,
    author: UserId,
) {
    let key = UserConfigKey::DefaultPostFormat;
    let value = String::from("org");
    let content_license = ContentLicense::CcBySa4_0;
    confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move {
                    user_config.set(transaction, author, key, &value).await?;
                    user_config
                        .set(
                            transaction,
                            author,
                            UserConfigKey::ContentLicense,
                            content_license.as_ref(),
                        )
                        .await
                })
            })
            .await
            .expect("set user config"),
        "backup fixture user config",
    );
    let record = MediaRecord {
        user_id: author,
        sha256: parse_content_hash(FIXTURE_MEDIA_SHA256),
        filename: parse_filename("my%20photo.jpg"),
        source: MediaSource::Upload,
        content_type: parse_content_type("image/jpeg"),
        size_bytes: parse_byte_size("4"),
        source_url: None,
        created_at: fixture_published_at(),
    };
    confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move { media.create_media(transaction, &record).await })
            })
            .await
            .expect("create media row"),
        "backup fixture media",
    );
    let feed_path = fp("/feed.rss");
    confirmed_for(
        write_scope
            .run(move |transaction| {
                Box::pin(async move { feed_events.enqueue(transaction, &feed_path).await })
            })
            .await
            .expect("enqueue feed event"),
        "backup fixture feed event",
    );
}

pub async fn assert_backup_fixture_restored(args: &StorageArgs, ids: &BackupFixtureIds) {
    let factory = open_existing_database(&args.db, &StorageRuntimeConfig::default())
        .await
        .expect("open restored database");
    assert_restored_backup_author(factory.users()).await;
    assert_restored_publisher(factory.publisher(), ids).await;
    assert_restored_public_post_and_passkey(factory.posts(), factory.passkeys(), ids).await;
    assert_restored_named_post(factory.posts(), ids).await;
    assert_restored_side_tables(factory.user_config(), factory.media(), args, ids).await;
}

async fn assert_restored_backup_author(users: Arc<dyn storage::UserStorage>) {
    let username: Username = "backupuser".parse().expect("valid username");
    let user = users
        .get_user_by_username(&username)
        .await
        .expect("get user")
        .expect("restored user");
    assert_eq!(user.is_operator, OperatorStatus::OPERATOR);
    assert_eq!(user.display_name.as_deref(), Some("Backup User"));
}

async fn assert_restored_publisher(
    publisher: Arc<dyn storage::PublisherStorage>,
    ids: &BackupFixtureIds,
) {
    assert_eq!(
        publisher
            .snapshot()
            .await
            .expect("read restored publisher state")
            .generation,
        ids.publisher_generation,
        "restore must replace the migration-seeded publisher generation"
    );
}

async fn assert_restored_public_post_and_passkey(
    posts: Arc<dyn storage::PostStorage>,
    passkeys: Arc<dyn storage::PasskeyStorage>,
    ids: &BackupFixtureIds,
) {
    // The public post resolves for its author.
    let post = posts
        .get_post_by_id(ids.public_post, &ViewerIdentity::local(ids.author))
        .await
        .expect("get post")
        .expect("restored post");
    assert_eq!(post.title.as_ref(), Some(&ids.public_post_title));
    assert_eq!(post.slug, ids.public_post_slug);
    // Restore preserves the instant, its UTC civil date, microsecond precision,
    // and timezone meaning across source/target backends.
    let published_at = post.published_at.expect("restored published timestamp");
    assert_eq!(
        passkeys
            .user_handle(ids.author)
            .await
            .expect("read restored Passkey handle"),
        Some(ids.passkey_user_handle.clone())
    );
    let passkey = passkeys
        .credential_for_user(ids.author, &ids.passkey_credential_id)
        .await
        .expect("read restored passkey")
        .expect("restored passkey");
    assert_eq!(passkey.id, ids.passkey_credential_id);
    assert_eq!(passkey.user_id, ids.author);
    assert_eq!(passkey.label, ids.passkey_label);
    assert_eq!(passkey.created_at, ids.passkey_created_at);
    assert_eq!(passkey.last_used_at, Some(ids.passkey_last_used_at));
    let serialized =
        serde_json::to_value(&passkey.credential).expect("serialize restored passkey credential");
    assert_eq!(serialized, ids.passkey_serialization);
    assert_eq!(
        serialized.pointer("/cred/counter"),
        Some(&Value::from(2)),
        "restored passkey credential must retain its signature counter"
    );
    assert_eq!(
        serialized.pointer("/cred/backup_eligible"),
        Some(&Value::Bool(true)),
        "restored passkey credential must retain backup eligibility"
    );
    assert_eq!(
        serialized.pointer("/cred/backup_state"),
        Some(&Value::Bool(true)),
        "restored passkey credential must retain backup state"
    );
    assert_eq!(published_at, fixture_published_at());
    assert_fixture_timestamp_meaning(published_at);

    // Tags ride along on the post record already read above (#771).
    let tags = &post.tags;
    assert_eq!(tags.len(), 1);
    assert_eq!(tags[0].tag_slug, "backup-test");
    assert_eq!(tags[0].tag_display, "Backup-Test");
}

async fn assert_restored_named_post(posts: Arc<dyn storage::PostStorage>, ids: &BackupFixtureIds) {
    // #4 closed: the Named-audience post survives restore visible to its
    // non-author subscriber — its post_audiences / subscriptions / audience_members
    // rows are carried — and correctly invisible to an anonymous viewer.
    assert!(
        posts
            .get_post_by_id(ids.named_post, &ViewerIdentity::local(ids.viewer))
            .await
            .expect("get named post")
            .is_some(),
        "restored Named-audience post must be visible to its subscriber"
    );
    assert!(
        posts
            .get_post_by_id(ids.named_post, &ViewerIdentity::Anonymous)
            .await
            .expect("get named post as anonymous")
            .is_none(),
        "a Named-audience post must not be visible to anonymous"
    );
}

async fn assert_restored_side_tables(
    user_config: Arc<dyn storage::UserConfigStorage>,
    media: Arc<dyn storage::MediaStorage>,
    args: &StorageArgs,
    ids: &BackupFixtureIds,
) {
    // The side tables (`user_config`, media, `feed_events`) survived the round trip.
    assert_eq!(
        user_config
            .get(ids.author, UserConfigKey::DefaultPostFormat)
            .await
            .expect("get user config")
            .as_deref(),
        Some("org")
    );
    assert_eq!(
        user_config
            .get_content_license(ids.author)
            .await
            .expect("get content license"),
        ContentLicense::CcBySa4_0
    );
    assert!(
        media
            .get_media(
                ids.author,
                &parse_content_hash(FIXTURE_MEDIA_SHA256),
                &parse_filename("my%20photo.jpg"),
                &MediaSource::Upload
            )
            .await
            .expect("get media")
            .is_some(),
        "restored media table row must be present"
    );
    assert_eq!(
        std::fs::read_to_string(args.storage_path.join("media").join("avatar.txt"))
            .expect("read restored media"),
        "media"
    );
}

/// Assert a restore target is untouched — neither the fixture's operator user
/// nor its media file is present — after a rejected restore rolled back.
pub async fn assert_target_unmodified(args: &StorageArgs) {
    let factory = open_existing_database(&args.db, &storage::StorageRuntimeConfig::default())
        .await
        .expect("open target");
    let users = factory.users();
    let username: Username = "backupuser".parse().expect("valid username");
    assert!(
        users
            .get_user_by_username(&username)
            .await
            .expect("get user")
            .is_none(),
        "target must be unmodified after a rejected restore"
    );
    assert!(
        !args.storage_path.join("media").join("avatar.txt").exists(),
        "target media must be unmodified after a rejected restore"
    );
}
