use common::ids::{PostId, UserId};
use common::media::MediaSource;
use common::post_title::PostTitle;
use common::slug::Slug;
use common::tagged_url::HubUrl;
use common::test_support::{
    parse_audience_name, parse_byte_size, parse_content_hash, parse_content_type,
    parse_display_name, parse_filename,
};
use common::time::UtcInstant;
use common::username::Username;
use common::visibility::{AudienceTarget, ViewerIdentity};
use host::config_key::UserConfigKey;
use host::password::Password;
use jaunder::cli::StorageArgs;
use std::sync::Arc;
use storage::test_support::{SeedRawPost, confirmed_for, fp, seed_local_subscription};
use storage::{
    AppState, HubMutationOutcome, MediaRecord, OperatorStatus, PublisherGeneration,
    StorageRuntimeConfig, open_existing_database,
};

/// SHA-256 the media-table fixture row is keyed by; any stable value works, since
/// the media *files* are mirrored separately from the media *table*.
const FIXTURE_MEDIA_SHA256: &str =
    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

/// Identifiers returned by [`populate_backup_fixture`] so
/// [`assert_backup_fixture_restored`] can check non-author visibility fidelity
/// (a `Named`-audience post must survive restore visible to its subscriber, not
/// silently Private — the bug in issue #4).
pub struct BackupFixtureIds {
    /// The operator who authors the fixture posts and owns the audience.
    pub author: UserId,
    /// A second, non-operator account subscribed to the author and a member of
    /// the `Named` audience — the viewer who must still see the private post.
    pub viewer: UserId,
    /// A `Public` post (visible to everyone, including anonymous).
    pub public_post: PostId,
    /// The public post's autogenerated slug and title, read back by
    /// [`assert_backup_fixture_restored`] instead of a hardcoded literal (both now
    /// autogenerate; only `published_at` stays a fixed contract).
    pub public_post_slug: Slug,
    pub public_post_title: PostTitle,
    /// A post targeted at a `Named` audience the viewer belongs to.
    pub named_post: PostId,
    /// The publisher generation, advanced from its migration-seeded value to prove
    /// backup and restore replace the target singleton row.
    pub publisher_generation: PublisherGeneration,
}

/// Fixed microsecond-precision publish time: deterministic and safe from
/// Postgres's µs quantization, so a restored value can be asserted exactly (DEC-D).
pub fn fixture_published_at() -> UtcInstant {
    "2026-04-29T12:34:56.789012Z"
        .parse()
        .expect("valid fixture timestamp")
}

pub async fn populate_backup_fixture(args: &StorageArgs) -> BackupFixtureIds {
    let state = open_existing_database(&args.db, &storage::StorageRuntimeConfig::default())
        .await
        .expect("open database");
    let hub: HubUrl = "https://hub.example.test/"
        .parse()
        .expect("valid fixture WebSub hub");
    let publisher = Arc::clone(&state.publisher);
    let publisher_mutation = confirmed_for(
        state
            .write_scope
            .run(move |transaction| {
                Box::pin(async move { publisher.mutate_hub(transaction, Some(hub)).await })
            })
            .await
            .expect("configure fixture WebSub hub"),
        "configure fixture WebSub hub",
    );
    let publisher_generation = match publisher_mutation {
        HubMutationOutcome::Changed { generation } => generation,
        HubMutationOutcome::Unchanged { .. } => panic!("initial WebSub hub must change"),
    };
    let username: Username = "backupuser".parse().expect("valid username");
    let password: Password = "password123".parse().expect("valid password");
    let users = Arc::clone(&state.users);
    let display_name = parse_display_name("Backup User");
    let password_for_author = storage::prepare_password(password.clone())
        .await
        .expect("prepare author password");
    let outcome = state
        .write_scope
        .run(move |transaction| {
            Box::pin(async move {
                users
                    .create_user(
                        transaction,
                        &username,
                        &password_for_author,
                        Some(&display_name),
                        OperatorStatus::OPERATOR,
                    )
                    .await
            })
        })
        .await
        .expect("create user");
    let author = confirmed_for(outcome, "backup fixture user");
    let public = SeedRawPost::new(author)
        .published_at(fixture_published_at())
        .tags(["Backup-Test"])
        .seed(&state)
        .await;

    let (viewer, named_post) = seed_named_audience_post(&state, author, &password).await;
    seed_side_tables(&state, author).await;

    std::fs::write(args.storage_path.join("media").join("avatar.txt"), "media")
        .expect("write media");
    BackupFixtureIds {
        author,
        viewer,
        public_post: public.post_id,
        public_post_slug: public.slug,
        public_post_title: public.title,
        named_post,
        publisher_generation,
    }
}

/// Seeds a non-author subscriber and a `Named`-audience post they belong to,
/// returning `(viewer_id, named_post_id)`. These visibility rows
/// (`subscriptions`, `audiences`, `audience_members`, `post_audiences`) must
/// survive restore so the subscriber still resolves the private post (issue #4).
async fn seed_named_audience_post(
    state: &Arc<AppState>,
    author: UserId,
    password: &Password,
) -> (UserId, PostId) {
    let viewer_name: Username = "viewer".parse().expect("valid username");
    let users = Arc::clone(&state.users);
    let display_name = parse_display_name("Viewer");
    let password = storage::prepare_password(password.clone())
        .await
        .expect("prepare viewer password");
    let outcome = state
        .write_scope
        .run(move |transaction| {
            Box::pin(async move {
                users
                    .create_user(
                        transaction,
                        &viewer_name,
                        &password,
                        Some(&display_name),
                        OperatorStatus::STANDARD,
                    )
                    .await
            })
        })
        .await
        .expect("create viewer");
    let viewer = confirmed_for(outcome, "backup fixture viewer");
    let subscription = seed_local_subscription(state, author, viewer).await;
    let audience_name = parse_audience_name("friends");
    let audiences = Arc::clone(&state.audiences);
    let audience = confirmed_for(
        state
            .write_scope
            .run(move |transaction| {
                Box::pin(async move {
                    audiences
                        .create_audience(transaction, author, &audience_name)
                        .await
                })
            })
            .await
            .expect("create audience"),
        "backup fixture audience",
    );
    let audiences = Arc::clone(&state.audiences);
    confirmed_for(
        state
            .write_scope
            .run(move |transaction| {
                Box::pin(async move {
                    audiences
                        .add_member(transaction, author, audience, subscription)
                        .await
                })
            })
            .await
            .expect("add audience member"),
        "backup fixture audience membership",
    );
    let named_post = SeedRawPost::new(author)
        .published_at(fixture_published_at())
        .audiences(vec![AudienceTarget::Named(audience)])
        .seed(state)
        .await
        .post_id;
    (viewer, named_post)
}

/// Seeds the side tables: a `user_config` row, a media-table row, and a
/// `feed_events` row.
async fn seed_side_tables(state: &AppState, author: UserId) {
    let user_config = Arc::clone(&state.user_config);
    let key = UserConfigKey::DefaultPostFormat;
    let value = String::from("org");
    confirmed_for(
        state
            .write_scope
            .run(move |transaction| {
                Box::pin(async move { user_config.set(transaction, author, key, &value).await })
            })
            .await
            .expect("set user config"),
        "backup fixture user config",
    );
    let media = Arc::clone(&state.media);
    let record = MediaRecord {
        user_id: author,
        sha256: parse_content_hash(FIXTURE_MEDIA_SHA256),
        filename: parse_filename("my%20photo.jpg"),
        source: MediaSource::Upload,
        content_type: parse_content_type("image/jpeg"),
        size_bytes: parse_byte_size("4"),
        source_url: None,
        created_at: fixture_published_at(),
    };
    confirmed_for(
        state
            .write_scope
            .run(move |transaction| {
                Box::pin(async move { media.create_media(transaction, &record).await })
            })
            .await
            .expect("create media row"),
        "backup fixture media",
    );
    let feed_events = Arc::clone(&state.feed_events);
    let feed_path = fp("/feed.rss");
    confirmed_for(
        state
            .write_scope
            .run(move |transaction| {
                Box::pin(async move { feed_events.enqueue(transaction, &feed_path).await })
            })
            .await
            .expect("enqueue feed event"),
        "backup fixture feed event",
    );
}

pub async fn assert_backup_fixture_restored(args: &StorageArgs, ids: &BackupFixtureIds) {
    let state = open_existing_database(&args.db, &StorageRuntimeConfig::default())
        .await
        .expect("open restored database");
    let username: Username = "backupuser".parse().expect("valid username");
    let user = state
        .users
        .get_user_by_username(&username)
        .await
        .expect("get user")
        .expect("restored user");
    assert_eq!(user.is_operator, OperatorStatus::OPERATOR);
    assert_eq!(user.display_name.as_deref(), Some("Backup User"));

    assert_eq!(
        state
            .publisher
            .snapshot()
            .await
            .expect("read restored publisher state")
            .generation,
        ids.publisher_generation,
        "restore must replace the migration-seeded publisher generation"
    );

    // The public post resolves for its author.
    let post = state
        .posts
        .get_post_by_id(ids.public_post, &ViewerIdentity::local(ids.author))
        .await
        .expect("get post")
        .expect("restored post");
    assert_eq!(post.title.as_ref(), Some(&ids.public_post_title));
    assert_eq!(post.slug, ids.public_post_slug);
    // Value interop (DEC-D): the timestamp survives with its value.
    assert_eq!(post.published_at, Some(fixture_published_at()));

    // Tags ride along on the post record already read above (#771).
    let tags = &post.tags;
    assert_eq!(tags.len(), 1);
    assert_eq!(tags[0].tag_slug, "backup-test");
    assert_eq!(tags[0].tag_display, "Backup-Test");

    // #4 closed: the Named-audience post survives restore visible to its
    // non-author subscriber — its post_audiences / subscriptions / audience_members
    // rows are carried — and correctly invisible to an anonymous viewer.
    assert!(
        state
            .posts
            .get_post_by_id(ids.named_post, &ViewerIdentity::local(ids.viewer))
            .await
            .expect("get named post")
            .is_some(),
        "restored Named-audience post must be visible to its subscriber"
    );
    assert!(
        state
            .posts
            .get_post_by_id(ids.named_post, &ViewerIdentity::Anonymous)
            .await
            .expect("get named post as anonymous")
            .is_none(),
        "a Named-audience post must not be visible to anonymous"
    );

    // The side tables (`user_config`, media, `feed_events`) survived the round trip.
    assert_eq!(
        state
            .user_config
            .get(ids.author, UserConfigKey::DefaultPostFormat)
            .await
            .expect("get user config")
            .as_deref(),
        Some("org")
    );
    assert!(
        state
            .media
            .get_media(
                ids.author,
                &parse_content_hash(FIXTURE_MEDIA_SHA256),
                &parse_filename("my%20photo.jpg"),
                &MediaSource::Upload
            )
            .await
            .expect("get media")
            .is_some(),
        "restored media table row must be present"
    );

    assert_eq!(
        std::fs::read_to_string(args.storage_path.join("media").join("avatar.txt"))
            .expect("read restored media"),
        "media"
    );
}

/// Assert a restore target is untouched — the fixture's operator user is absent —
/// after a rejected restore rolled back.
pub async fn assert_target_unmodified(args: &StorageArgs) {
    let state = open_existing_database(&args.db, &storage::StorageRuntimeConfig::default())
        .await
        .expect("open target");
    let username: Username = "backupuser".parse().expect("valid username");
    assert!(
        state
            .users
            .get_user_by_username(&username)
            .await
            .expect("get user")
            .is_none(),
        "target must be unmodified after a rejected restore"
    );
}
