-- Pending Rust work is a queue, not a history of completed migrations.
CREATE TABLE pending_code_migrations (
    queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation TEXT NOT NULL,
    enqueued_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);
