use std::borrow::Cow;
use std::path::Path;
use std::str::FromStr;

use macros::StrNewtype;
use percent_encoding::{AsciiSet, percent_decode_str, utf8_percent_encode};
use thiserror::Error;

/// A media filename in its **canonical spelling**: the percent-encoded safe leaf that is
/// simultaneously the database value, the on-disk name, and the URL segment — one value, no
/// derivation between them (#720). [`decoded`][Filename::decoded] is the display view.
///
/// The newtype makes an un-sanitized filename unrepresentable where a filename is expected:
/// the value feeds a filesystem path and a `Content-Disposition` header, so an un-sanitized
/// one is a path-traversal / header-injection hazard (ADR-0063 §1: invariant + trust/safety
/// boundary).
///
/// It is also bounded by [`MAX_FILENAME_ENCODED_BYTES`], so a value that passes validation
/// can always be written to disk. Because the stored value already *is* the encoded form,
/// that bound is a plain byte length — the encode-set coupling #708 recorded now lives only
/// in [`sanitized`][Filename::sanitized]'s intake budget.
///
/// Three construction doors:
/// - [`FromStr`] **validates** the canonical spelling — the door for untrusted URL / wire /
///   DB values that must match a stored filename exactly. It accepts `s` only when, **in
///   this order**: `s` is non-empty and neither `.` nor `..`; `sanitize_filename` fixes the
///   *decoded* form; `s` equals the encoder's output for that form; and `s.len()` is within
///   budget. `#[derive(StrNewtype)]` routes both `Deserialize` and the `sqlx` `Decode`
///   through it, so every wire value and every column read passes here.
///
///   Two subtleties, each load-bearing. The safe-leaf oracle runs on `decode(s)`, **never**
///   on `s`: `sanitize_filename("a%2Fb.jpg")` is `"a%2Fb.jpg"`, so checking the encoded form
///   passes vacuously and would admit a separator or a NUL. And the leaf check precedes the
///   canonicity check because a value like `a/b.txt` fails both — the caller needs to hear
///   about the leaf.
///
///   It *rejects* rather than truncating: a silently shortened value would match the wrong
///   file, or nothing (#708).
/// - [`sanitized`][Filename::sanitized] **normalizes** — the upload-intake door, where a
///   client's arbitrary name is reduced to a safe leaf and then encoded. It **truncates** an
///   over-long name (keeping the extension) instead of failing, so an upload is never lost
///   for a cosmetic reason. This is the one intricate step in the whole arrangement;
///   everything else is dumb by design.
/// - [`from_decoded_segment`][Filename::from_decoded_segment] **re-encodes** — the inbound
///   URL-segment door for text axum has already percent-decoded. It exists because encoding
///   is not idempotent, so one [`FromStr`] cannot serve both a decoded and an
///   already-canonical input. It checks but never repairs: an over-budget encoded spelling
///   cannot exist on disk, and truncating a lookup key could match the wrong file.
///
/// Their contract: `sanitized`'s output always satisfies `FromStr`, pinned by
/// `sanitized_output_always_reparses_as_filename`; and `from_decoded_segment` returns a
/// [`Filename`] directly, so no public decoded-intermediate type can leak past extraction.
///
/// The rest of the ADR-0063 string-newtype trailer (`Display`, `AsRef<str>`,
/// `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde bridge) is generated by
/// `#[derive(StrNewtype)]`. The wrapped `String` is private, so the only ways in
/// are the three validating doors — an arbitrary `String` cannot masquerade as a
/// filename.
///
/// The positive companion shows the identical fixture compiles — the path resolves
/// and the validating door accepts a canonical safe leaf — so each `compile_fail`
/// below fails for the private field, not for a moved path. (Fixture lines are
/// hidden with `#`.)
///
/// ```
/// use common::media::Filename;
/// use std::str::FromStr;
/// let f = Filename::from_str("a.png").unwrap();
/// let _read: &str = f.as_ref();
/// ```
///
/// No public constructor:
/// ```compile_fail
/// # use common::media::Filename;
/// # use std::str::FromStr;
/// let _ = Filename("a".to_string()); // private field
/// ```
///
/// A `String` does not convert to a `Filename` (asserted on `.into()`, so the proof
/// still fails if a `From<String>` impl is added — a function argument would not):
/// ```compile_fail
/// # use common::media::Filename;
/// # use std::str::FromStr;
/// let _f: Filename = "a".to_string().into();
/// ```
///
/// The decoded-segment door returns a `Filename` directly:
/// ```
/// # use common::media::Filename;
/// let f = Filename::from_decoded_segment("my photo.jpg").unwrap();
/// assert_eq!(f.as_ref(), "my%20photo.jpg");
/// ```
///
/// There is no public decoded-intermediate filename type:
/// ```compile_fail
/// # use common::media::Filename;
/// use common::media::ProfferedFilename;
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct Filename(String);

/// Error returned when a string is not a usable media filename leaf.
#[derive(Debug, Error)]
pub enum InvalidFilename {
    /// Not a canonical single path component.
    #[error(
        "filename must be a non-empty safe path leaf (no path components, `.`/`..`, or null bytes)"
    )]
    NotASafeLeaf,
    /// A safe leaf, but not in the canonical percent-encoded spelling.
    ///
    /// Distinct from [`NotASafeLeaf`][Self::NotASafeLeaf] because the likeliest cause is a
    /// *raw* name on the wire — a perfectly good leaf that simply was not encoded — and
    /// telling that caller their filename "is not a safe path leaf" misdirects (#720).
    #[error(
        "filename must be in canonical percent-encoded form (this is the stored spelling; \
         encode it once at the boundary, and decode only for display)"
    )]
    NotCanonical,
    /// Longer than the filesystem can hold once percent-encoded.
    ///
    /// The message states the *encoded* length and why it differs from what the user typed:
    /// "my 90-character name was rejected" is otherwise baffling (#708).
    #[error(
        "filename is too long: {encoded} bytes once percent-encoded, limit \
         {MAX_FILENAME_ENCODED_BYTES} (encoding expands each unsafe byte to `%XX`, so the \
         limit applies to the encoded form, not the characters you typed)"
    )]
    TooLong {
        /// The candidate's encoded byte length.
        encoded: usize,
    },
}

impl FromStr for Filename {
    type Err = InvalidFilename;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        // Door A: accept only the canonical stored spelling. The check order below is
        // load-bearing, not incidental — see each step.
        let decoded = percent_decode_str(s).decode_utf8_lossy();

        // The safe-leaf rule, applied to the DECODED form (#720). Canonicity does *not*
        // imply a safe leaf: `a%2Fb.jpg`, `a%00b.jpg` and `a%5Cb.jpg` are all canonical yet
        // decode to a separator, a NUL and a backslash. This is the path-traversal /
        // header-injection guard the type exists for, so losing it here would hollow out
        // `Filename` while every other check still looked present.
        //
        // Run on `decoded`, never on `s`: `sanitize_filename("a%2Fb.jpg")` is
        // `"a%2Fb.jpg"`, so testing the encoded form passes vacuously.
        //
        // Note what this does *not* catch: `sanitize_filename` does not touch CR/LF, so
        // a canonical `a%0D%0Ab.jpg` is accepted — see
        // `from_str_accepts_a_canonical_name_carrying_control_characters` for why that
        // is safe and deliberate rather than an oversight.
        //
        // Ordered BEFORE canonicity because a separator value is *both* an unsafe leaf and
        // non-canonical, and the failure a caller needs to hear about is the leaf.
        if !is_safe_leaf(&decoded) {
            return Err(InvalidFilename::NotASafeLeaf);
        }

        // Canonicity: the stored spelling is exactly what the encoder produces. This is
        // what makes "the column holds the encoded form" a checked fact rather than a
        // convention — a raw name from a hand-edited row, a restored backup or a wire
        // argument is rejected here, instead of becoming a file no URL can address.
        if utf8_percent_encode(&decoded, MEDIA_SEGMENT_ENCODE_SET).to_string() != s {
            return Err(InvalidFilename::NotCanonical);
        }

        // The value already *is* the encoded form, so the budget is a plain byte length —
        // no encode-set reference (#708's coupling now lives only in the intake door).
        // This door *rejects* rather than truncating: its values must match a stored name
        // exactly, and a silently-shortened one would match the wrong file, or nothing.
        if s.len() > MAX_FILENAME_ENCODED_BYTES {
            return Err(InvalidFilename::TooLong { encoded: s.len() });
        }
        Ok(Filename(s.to_owned()))
    }
}

impl Filename {
    /// Builds a [`Filename`] by **normalizing** `raw` to a safe leaf via
    /// [`sanitize_filename`], rejecting an empty result. This is the trusted
    /// upload-intake door (the `AtomPub` `Slug` header, a multipart `file_name`),
    /// where a client's arbitrary name is meant to be reduced to a single leaf —
    /// as distinct from [`FromStr`], which rejects a non-canonical name outright.
    ///
    /// An over-long name is **truncated, not rejected** — see [`truncate_to_budget`]. This is
    /// the intake door: failing an upload because the name is long would lose the file for a
    /// cosmetic reason, and shortening it is exactly the "reduce to a usable leaf" job this
    /// door already has (#708).
    ///
    /// # Errors
    ///
    /// Returns [`InvalidFilename::NotASafeLeaf`] when `raw` sanitizes — or truncates — to a
    /// name that is not one: `""`, `.`, or `..`.
    pub fn sanitized(raw: &str) -> Result<Self, InvalidFilename> {
        let s = truncate_to_budget(sanitize_filename(raw));
        // Truncation can leave a degenerate leaf (an empty stem with no extension), and
        // `sanitize_filename` already maps `.`/`..` to empty. Re-checked here — before the
        // encode, since `.`/`..` encode to themselves — so this door's output always
        // satisfies `FromStr`. The oracle half is redundant after `sanitize_filename`, but
        // stating one rule at all three doors is what stops them drifting apart.
        if !is_safe_leaf(&s) {
            return Err(InvalidFilename::NotASafeLeaf);
        }
        // Encode last (#720). The order `sanitize → truncate → encode` is deliberate:
        // truncating in *encoded* space would mean never splitting a `%XX` escape, never
        // splitting the escape run of one multi-byte character (`ä` is `%C3%A4`, and a cut
        // after `%C3` decodes to invalid UTF-8), and still never splitting a grapheme
        // cluster — strictly harder than measuring raw graphemes by their encoded cost,
        // for no gain. `truncate_to_budget` already bounds `encoded_len(s) <= MAX`, and
        // the encoded output's `len()` *is* that number, so the result is in budget by
        // construction.
        Ok(Filename(
            utf8_percent_encode(&s, MEDIA_SEGMENT_ENCODE_SET).to_string(),
        ))
    }

    /// Builds a [`Filename`] from one URL path segment that has already been
    /// percent-decoded by the router.
    ///
    /// This is the extractor/helper door for route parameters whose raw URL spelling is
    /// unavailable: `decoded` is checked as a safe leaf, percent-encoded exactly once with
    /// the media segment encode set, and rejected if that canonical encoded spelling would
    /// exceed [`MAX_FILENAME_ENCODED_BYTES`]. It checks but never repairs, because this is a
    /// lookup key: truncating would risk naming a different stored file.
    ///
    /// Use [`FromStr`] for values that are already in canonical encoded form, and
    /// [`sanitized`][Self::sanitized] for upload intake that should normalize arbitrary
    /// user text.
    ///
    /// # Errors
    ///
    /// Returns [`InvalidFilename::NotASafeLeaf`] when `decoded` is not a safe path leaf, or
    /// [`InvalidFilename::TooLong`] when encoding it would exceed the filesystem component
    /// budget.
    pub fn from_decoded_segment(decoded: &str) -> Result<Self, InvalidFilename> {
        if !is_safe_leaf(decoded) {
            return Err(InvalidFilename::NotASafeLeaf);
        }

        let encoded = utf8_percent_encode(decoded, MEDIA_SEGMENT_ENCODE_SET).to_string();
        if encoded.len() > MAX_FILENAME_ENCODED_BYTES {
            return Err(InvalidFilename::TooLong {
                encoded: encoded.len(),
            });
        }

        Ok(Filename(encoded))
    }

    /// The name as a human should read it — the stored value with its percent-escapes
    /// undone. The **display view**, and the only place a `Filename` is transformed on
    /// the way out (#720).
    ///
    /// Every other consumer — [`path`], the URL builders, the `sqlx` bind, a
    /// reference comparison — wants the stored bytes and gets them from the ADR-0063
    /// trailer (`Display`, `Deref<str>`, `AsRef<str>`) with no call. That asymmetry is
    /// deliberate: a missed decode here is cosmetic, whereas a missed *encode* on a path
    /// would be a 404 or, with a name collision, the wrong file. The fragile direction is
    /// the one that must not need remembering.
    ///
    /// Returns [`Cow`] so the common nothing-to-decode case allocates nothing.
    ///
    /// Decoding is **lossy**, and cannot lose anything: a `Filename`'s escapes were
    /// produced by encoding valid UTF-8, and a lone invalid byte such as `%FF` cannot be
    /// stored — it fails the canonicity check, since decoding it yields U+FFFD, which
    /// re-encodes to `%EF%BF%BD` and so differs from the input. The substitution arm is
    /// therefore unreachable on a value of this type.
    #[must_use]
    pub fn decoded(&self) -> Cow<'_, str> {
        percent_decode_str(&self.0).decode_utf8_lossy()
    }
}

/// Shortens `name` until its percent-encoded form fits [`MAX_FILENAME_ENCODED_BYTES`],
/// keeping the extension and never splitting a grapheme cluster. A name already within
/// budget is returned unchanged.
///
/// The extension is kept because [`detect_content_type`] is the **only** content-type source
/// when a client sends no `Content-Type`, and it runs on the already-sanitized name — so
/// dropping the extension here would store `application/octet-stream` permanently, with no
/// way back but a re-upload. (Serving itself reads the stored column, so it is unaffected.)
/// It also keeps the `Content-Disposition` name openable on the user's machine.
///
/// [`Path`]'s stem/extension split is used rather than a last-dot search so a dotfile
/// survives: `.hiddenfile` has no extension, so it is truncated as one piece instead of
/// having its "stem" emptied.
fn truncate_to_budget(name: String) -> String {
    if encoded_len(&name) <= MAX_FILENAME_ENCODED_BYTES {
        return name;
    }
    let path = Path::new(&name);
    let split = path
        .file_stem()
        .and_then(|s| s.to_str())
        .zip(path.extension().and_then(|e| e.to_str()));
    let (stem, extension) = match split {
        Some((stem, extension)) => (stem, format!(".{extension}")),
        None => (name.as_str(), String::new()),
    };
    // Reserve room for the extension **and a minimal stem**. Reserving only the extension
    // would let a name whose first grapheme cluster alone busts the budget — a base character
    // with dozens of combining marks — truncate to bare `.jpg`. That is a *dotfile*, whose
    // `Path::extension()` is `None`, so `detect_content_type` would answer
    // `application/octet-stream` and store it permanently: precisely the loss keeping the
    // extension is meant to prevent. An extension too large to leave that room is beyond
    // saving — drop it and truncate the whole name, accepting the degraded content type.
    let reserved = encoded_len(&extension) + encoded_len(TRUNCATED_STEM);
    let (stem, extension) = if reserved > MAX_FILENAME_ENCODED_BYTES {
        (name.as_str(), String::new())
    } else {
        (stem, extension)
    };

    let budget = MAX_FILENAME_ENCODED_BYTES - encoded_len(&extension);
    let truncated = crate::text::truncate_by_graphemes(stem, budget, encoded_len);
    // Nothing usable survived — or what did is not a name (`.`/`..`). Substitute the same
    // placeholder a *missing* filename gets, so the result is always a real leaf carrying its
    // extension. This is what keeps truncation from ever producing a value `FromStr` would
    // reject, which `sanitized` relies on because it constructs `Filename` directly.
    let mut out = if truncated.is_empty() || truncated == "." || truncated == ".." {
        TRUNCATED_STEM.to_owned()
    } else {
        truncated
    };
    out.push_str(&extension);
    out
}

/// Whether `candidate` is a usable safe leaf: non-empty, not `.` or `..`, and already
/// exactly what [`sanitize_filename`] would make of it (so no path components and no NUL).
///
/// The whole rule in one place. All three of [`Filename`]'s doors need it, and before this
/// existed each spelled its own share of it — which is how a fourth door would come to
/// rediscover the rule rather than reuse it.
///
/// The `is_empty` check is explicit because `sanitize_filename("")` is `""`, so the oracle
/// alone would accept the empty string; `.` and `..` are named because they survive
/// percent-encoding unchanged (`.` is unreserved), so they cannot be caught downstream.
fn is_safe_leaf(candidate: &str) -> bool {
    !candidate.is_empty()
        && candidate != "."
        && candidate != ".."
        && sanitize_filename(candidate) == candidate
}

/// Strip path components, replace null bytes, reject `.`, `..`, and empty results.
#[must_use]
pub fn sanitize_filename(name: &str) -> String {
    let normalized = name.replace('\\', "/");
    let path = Path::new(&normalized);
    let Some(file_name) = path.file_name() else {
        return String::new();
    };
    let s = file_name.to_string_lossy();
    s.replace('\0', "_")
}

/// The percent-encode set for the filename segment of a media path: everything
/// [`percent_encoding::NON_ALPHANUMERIC`] encodes, minus the RFC 3986 *unreserved* marks
/// `-._~`.
///
/// Keeping those four unencoded is what makes an ordinary name round-trip byte-identical —
/// `photo.jpg` stays `photo.jpg` — which is the point of encoding here at all: the on-disk
/// name has to stay greppable and paste-able from a URL. Bare
/// [`percent_encoding::NON_ALPHANUMERIC`] would
/// yield `my%2Dphoto%2Ejpg` and make every stored file unreadable. (`content_disposition`
/// in the `server` crate *does* use the bare set; correct there, wrong here.)
const MEDIA_SEGMENT_ENCODE_SET: &AsciiSet = &percent_encoding::NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'.')
    .remove(b'_')
    .remove(b'~');

/// The filesystem's limit on a single path component, in bytes. ext4/XFS/btrfs, APFS and NTFS
/// all cap one name at 255, and the media layout puts the whole filename in a single
/// component, so this is the entire budget.
///
/// It is measured against the **percent-encoded** form, because that is what lands on disk
/// (ADR-0080) — a name can be well under 255 characters and still not fit. That makes this
/// bound depend on [`MEDIA_SEGMENT_ENCODE_SET`]: widening that set shrinks the set of
/// representable names, so the two must be revisited together (#708).
pub const MAX_FILENAME_ENCODED_BYTES: usize = 255;

/// The stem substituted when truncation leaves nothing usable — the same placeholder a
/// *missing* upload filename already gets (`MediaManager::validate_filename`), so operators
/// see one recognizable name for "we had to invent this" rather than two.
const TRUNCATED_STEM: &str = "upload";

/// The encoded byte length of `s` as a media path segment — what the name costs on disk.
///
/// Sums the encoder's output chunks rather than collecting a `String`, so the per-grapheme
/// loop in [`truncate_to_budget`] allocates nothing. The single place the budget is measured,
/// so both `Filename` doors agree.
fn encoded_len(s: &str) -> usize {
    utf8_percent_encode(s, MEDIA_SEGMENT_ENCODE_SET)
        .map(str::len)
        .sum()
}

#[cfg(test)]
mod tests {
    use super::super::mime::detect_content_type;
    use super::*;

    #[test]
    fn sanitize_strips_path_components() {
        assert_eq!(sanitize_filename("../../etc/passwd"), "passwd");
        assert_eq!(sanitize_filename("foo/bar/baz.txt"), "baz.txt");
        assert_eq!(sanitize_filename("C:\\Users\\file.txt"), "file.txt");
    }

    #[test]
    fn sanitize_replaces_unsafe_chars() {
        assert_eq!(sanitize_filename("file\0name.txt"), "file_name.txt");
        assert_eq!(sanitize_filename("\0"), "_");
    }

    #[test]
    fn sanitize_rejects_empty() {
        assert!(sanitize_filename("").is_empty());
        assert!(sanitize_filename(".").is_empty());
        assert!(sanitize_filename("..").is_empty());
    }

    #[test]
    fn filename_parses_a_canonical_leaf() {
        let f: Filename = "photo.jpg".parse().unwrap();
        assert_eq!(f, "photo.jpg");
    }

    #[test]
    fn filename_rejects_non_canonical_and_empty() {
        // Non-canonical names (which Door B *would* normalize) and empty are
        // rejected here, not normalized — Door A only accepts an already-safe leaf.
        for bad in [
            "",
            "..",
            ".",
            "a/b",
            "../x",
            "sub/file.txt",
            "C:\\x\\y.txt",
            "foo\0",
        ] {
            assert!(bad.parse::<Filename>().is_err(), "must reject {bad:?}");
        }
    }

    #[test]
    fn filename_display_and_deref_read_the_leaf() {
        let f: Filename = "a.txt".parse().unwrap();
        assert_eq!(f.to_string(), "a.txt");
        assert_eq!(&f[..1], "a"); // Deref<Target = str>
    }

    // --- Filename: the display view (#720) ---

    #[test]
    fn decoded_is_identity_for_a_name_with_nothing_encoded() {
        let f = Filename::sanitized("photo.jpg").expect("valid leaf");
        assert_eq!(f.decoded(), "photo.jpg");
    }

    #[test]
    fn decoded_borrows_when_there_is_nothing_to_decode() {
        let f = Filename::sanitized("photo.jpg").expect("valid leaf");
        assert!(matches!(f.decoded(), std::borrow::Cow::Borrowed(_)));
    }

    #[test]
    fn decoded_undoes_percent_escapes() {
        // Constructed through `FromStr` so this states the intended post-#720
        // relationship directly, independent of what `sanitized` currently stores.
        let f: Filename = "my%20photo.jpg".parse().expect("a safe leaf today");
        assert_eq!(f.decoded(), "my photo.jpg");
    }

    #[test]
    fn decoded_recovers_a_literal_percent() {
        let f: Filename = "50%25.jpg".parse().expect("a safe leaf today");
        assert_eq!(f.decoded(), "50%.jpg");
    }

    // --- Filename: Door B (normalizing producer) ---

    #[test]
    fn sanitized_normalizes_to_a_safe_leaf() {
        assert_eq!(Filename::sanitized("../../etc/passwd").unwrap(), "passwd");
        assert_eq!(Filename::sanitized("foo/bar/baz.txt").unwrap(), "baz.txt");
        assert_eq!(
            Filename::sanitized("file\0name.txt").unwrap(),
            "file_name.txt"
        );
    }

    #[test]
    fn sanitized_rejects_empty_after_normalization() {
        for bad in ["", ".", ".."] {
            assert!(Filename::sanitized(bad).is_err(), "must reject {bad:?}");
        }
    }

    #[test]
    fn filename_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let f: Filename = "photo.jpg".parse().unwrap();
        assert_eq!(serde_json::to_string(&f).unwrap(), "\"photo.jpg\"");
        assert_eq!(
            serde_json::from_str::<Filename>("\"photo.jpg\"").unwrap(),
            f
        );
        // A non-canonical name is rejected at deserialize time (wire rejection).
        assert!(serde_json::from_str::<Filename>("\"../x\"").is_err());
    }

    #[test]
    fn filename_invalid_error_displays_the_rule() {
        let msg = "..".parse::<Filename>().unwrap_err().to_string();
        assert!(msg.contains("safe path leaf"), "{msg}");
    }

    // --- #708: the length bound is on the ENCODED form ---

    // #708's original case now lives at the decoded-segment door — see
    // `decoded_segment_rejects_a_name_whose_encoded_form_exceeds_the_budget`. Since #720 a
    // `Filename` holds the already-encoded value, so `"ä".repeat(100)` is non-canonical
    // and fails that check before length is ever reached; the strict door's own bound is
    // a plain byte count, pinned by `from_str_rejects_an_over_long_canonical_name`.

    #[test]
    fn from_str_accepts_a_name_exactly_at_the_budget() {
        // Boundary: `<=` not `<`. Plain ASCII encodes 1:1, so 255 chars is 255 bytes.
        let raw = "a".repeat(MAX_FILENAME_ENCODED_BYTES);
        assert!(raw.parse::<Filename>().is_ok());
        let over = "a".repeat(MAX_FILENAME_ENCODED_BYTES + 1);
        assert!(matches!(
            over.parse::<Filename>().expect_err("one over must fail"),
            InvalidFilename::TooLong { .. }
        ));
    }

    #[test]
    fn from_str_still_reports_a_bad_leaf_as_such() {
        // The two failures stay distinguishable — the length check runs after the leaf check.
        assert!(matches!(
            "../escape"
                .parse::<Filename>()
                .expect_err("traversal must fail"),
            InvalidFilename::NotASafeLeaf
        ));
    }

    #[test]
    fn sanitized_truncates_instead_of_failing_and_keeps_the_extension() {
        let long = format!("{}.jpg", "a".repeat(400));
        let f = Filename::sanitized(&long).expect("the intake door truncates, never fails here");
        assert!(f.ends_with(".jpg"), "extension must survive: {f}");
        assert!(f.len() <= MAX_FILENAME_ENCODED_BYTES, "{f}");
        // The property the extension is kept *for*: the stored content type remains JPEG.
        // Asserting merely "ends_with(.jpg)" would pass on a mangled extension.
        assert_eq!(detect_content_type(&f), "image/jpeg");
    }

    #[test]
    fn sanitized_truncation_is_measured_in_encoded_bytes_not_characters() {
        // ~3× expansion. Truncating to 255 *characters* would leave ~765 encoded bytes —
        // still unwritable. This is the assertion that pins D1's choice.
        let long = format!("{}.png", "ä".repeat(300));
        let f = Filename::sanitized(&long).expect("must truncate");
        assert!(f.len() <= MAX_FILENAME_ENCODED_BYTES, "{f}");
        assert!(
            f.chars().count() < 255,
            "must cut well short of 255 chars: {f}"
        );
        assert_eq!(detect_content_type(&f), "image/png");
    }

    #[test]
    fn sanitized_never_splits_a_grapheme_cluster() {
        // Devanagari base + combining vowel sign: cutting between them corrupts the
        // character. Re-parsing through the strict door proves the result is a valid,
        // in-budget leaf.
        let long = format!("{}.txt", "कि".repeat(200));
        let f = Filename::sanitized(&long).expect("must truncate");
        assert!(f.len() <= MAX_FILENAME_ENCODED_BYTES, "{f}");
        assert!(f.as_ref().parse::<Filename>().is_ok(), "{f}");
        // No lone combining mark left at the cut.
        assert!(!f.starts_with('\u{093F}'), "{f}");
    }

    #[test]
    fn sanitized_preserves_a_dotfile_rather_than_treating_it_as_all_extension() {
        // `Path::extension()` is `None` for a dotfile, so it truncates as one piece. A
        // manual last-dot split would empty the "stem" and destroy the name.
        assert_eq!(
            Filename::sanitized(".hiddenfile").expect("valid leaf"),
            ".hiddenfile"
        );
        let long = format!(".{}", "a".repeat(400));
        let f = Filename::sanitized(&long).expect("must truncate");
        assert!(f.starts_with('.'), "leading dot must survive: {f}");
        assert!(f.len() <= MAX_FILENAME_ENCODED_BYTES, "{f}");
    }

    #[test]
    fn sanitized_truncates_the_whole_name_when_the_extension_alone_is_over_budget() {
        let f = Filename::sanitized(&format!("x.{}", "ä".repeat(300))).expect("must truncate");
        assert!(f.len() <= MAX_FILENAME_ENCODED_BYTES, "{f}");
        assert!(f.as_ref().parse::<Filename>().is_ok(), "{f}");
    }

    #[test]
    fn sanitized_rejects_input_that_reduces_to_a_degenerate_name() {
        for bad in ["", ".", ".."] {
            assert!(matches!(
                Filename::sanitized(bad).expect_err("degenerate names are not filenames"),
                InvalidFilename::NotASafeLeaf
            ));
        }
    }

    /// A stem that is a **single** grapheme cluster too large for the budget: one base
    /// character carrying ~80 combining marks. Nothing of the stem fits, so a naive
    /// implementation emits bare `.jpg` — a *dotfile*, whose `Path::extension()` is `None`,
    /// so `detect_content_type` answers `application/octet-stream` and stores it forever.
    /// That is the exact loss keeping the extension is supposed to prevent, so it is pinned.
    #[test]
    fn sanitized_substitutes_a_stem_when_no_cluster_of_the_original_fits() {
        let zalgo = format!("a{}.jpg", "\u{0301}".repeat(80));
        let f = Filename::sanitized(&zalgo).expect("must truncate, not fail");

        assert!(f.len() <= MAX_FILENAME_ENCODED_BYTES, "{f}");
        assert!(f.ends_with(".jpg"), "{f}");
        // The property that matters: still detected as an image, not octet-stream.
        assert_eq!(detect_content_type(&f), "image/jpeg");
        assert_ne!(f, ".jpg", "a bare extension is a dotfile, not a filename");
        // And it is a value the strict door accepts — `sanitized` builds `Filename` directly,
        // so nothing else enforces that.
        assert!(f.as_ref().parse::<Filename>().is_ok(), "{f}");
    }

    #[test]
    fn sanitized_never_reports_a_length_failure_as_a_bad_leaf() {
        // Truncation must always yield a usable name, so a merely-long input is never an
        // error — the `NotASafeLeaf` guard is only for what `sanitize_filename` itself
        // empties (`""`, `.`, `..`). A regression here would surface as a baffling
        // "must be a non-empty safe path leaf" for a name that is one.
        for long in [
            format!("a{}.jpg", "\u{0301}".repeat(80)), // no cluster of the stem fits
            format!("a{}", "\u{0301}".repeat(80)),     // ditto, and no extension to keep
            format!(".{}", "\u{0301}".repeat(80)),     // dotfile whose only cluster busts it
            "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}".repeat(40), // ZWJ family emoji
        ] {
            assert!(
                Filename::sanitized(&long).is_ok(),
                "a long-but-legal name must truncate, not fail: {long:?}"
            );
        }
    }

    // Idempotence pin: whatever the intake door (B) emits must re-parse through the strict
    // door (A). Otherwise a stored, B-written filename becomes a `Decode` error on read-back
    // — this fails loudly here instead.
    //
    // Asserted on `Filename::sanitized`, not on `sanitize_filename`: the bare oracle
    // does not truncate (#708), so its output for a long name is over budget and Door A
    // rightly rejects it. The claim that has to hold is about the door callers
    // actually use.
    #[test]
    fn sanitized_output_always_reparses_as_filename() {
        for raw in [
            "photo.jpg",
            "../../etc/passwd",
            "foo/bar/baz.txt",
            "C:\\Users\\file.txt",
            "file\0name.txt",
            "a b.txt",
            ".hidden",
            "no-ext",
            // Over budget once encoded — the cases that motivated #708.
            &"ä".repeat(300),
            &format!("{}.jpg", "a".repeat(400)),
        ] {
            // Asserted as `Ok` first, deliberately: allowing `Err` to satisfy the claim
            // would hide `sanitized` regressing to *rejecting* long names (#708). None
            // of these inputs is degenerate, so every one must succeed.
            let f = Filename::sanitized(raw)
                .unwrap_or_else(|e| panic!("sanitized({raw:?}) must succeed, got {e}"));
            assert!(
                f.as_ref().parse::<Filename>().is_ok(),
                "sanitized({raw:?}) = {f:?} must re-parse as Filename"
            );
        }
    }

    // --- Filename: Door C (decoded URL segment conversion) ---

    #[test]
    fn decoded_segment_accepts_a_safe_leaf_with_space() {
        let f = Filename::from_decoded_segment("my photo.jpg").expect("a safe decoded leaf");
        assert_eq!(f, "my%20photo.jpg");
        assert_eq!(f.decoded(), "my photo.jpg");
    }

    #[test]
    fn decoded_segment_rejects_unsafe_decoded_leaves() {
        // The decoded segment axum hands us. `a\b.png` is not a leaf, and the member
        // route answers 400 for it — pinned here so #720's re-encode cannot silently
        // turn that into a 404.
        for bad in ["a\\b.png", "a/b.png", "..", ".", "", "a\0b.png"] {
            assert!(
                Filename::from_decoded_segment(bad).is_err(),
                "must reject {bad:?}"
            );
        }
    }

    #[test]
    fn decoded_segment_rejects_an_over_long_name_rather_than_truncating() {
        // Reject, never repair: a shortened lookup key would match the wrong file.
        let long = format!("{}.jpg", "a".repeat(MAX_FILENAME_ENCODED_BYTES));
        assert!(Filename::from_decoded_segment(&long).is_err());
    }

    #[test]
    fn decoded_segment_conversion_returns_filename_directly() {
        // The door returns `Filename`, not a public decoded-intermediate trailer.
        let f: Filename = Filename::from_decoded_segment("photo.jpg").expect("a safe decoded leaf");
        assert_eq!(f, "photo.jpg");
    }

    // --- #720: the encoded form is canonical ---

    #[test]
    fn sanitized_stores_the_encoded_form() {
        let f = Filename::sanitized("my photo.jpg").expect("valid leaf");
        assert_eq!(f, "my%20photo.jpg");
        assert_eq!(f.decoded(), "my photo.jpg");
    }

    #[test]
    fn from_str_rejects_a_non_canonical_value() {
        // Raw (unencoded) and a lowercase escape are both non-canonical.
        assert!("my photo.jpg".parse::<Filename>().is_err());
        assert!("my%2fphoto.jpg".parse::<Filename>().is_err());
        assert!("my%20photo.jpg".parse::<Filename>().is_ok());
    }

    #[test]
    fn from_str_rejects_canonical_but_unsafe_values() {
        // The test that fails if the decoded-form safe-leaf guard is dropped. Each of
        // these is canonical, non-empty, neither `.` nor `..`, and under the length
        // bound — so only a check run on `decode(s)` rejects it. Running the oracle on
        // the encoded form would pass vacuously.
        for bad in ["a%2Fb.jpg", "a%00b.jpg", "a%5Cb.jpg"] {
            assert!(
                bad.parse::<Filename>().is_err(),
                "canonical-but-unsafe value must be rejected: {bad:?}"
            );
        }
    }

    #[test]
    fn from_str_accepts_a_canonical_name_carrying_control_characters() {
        // CR/LF in a canonical name is accepted — decided, not missed (#720):
        // `sanitize_filename` normalizes backslashes, strips path components and maps
        // NUL, but does not reject CR/LF. No live hazard follows: `content_disposition`
        // drops control characters from its `filename=` fallback and percent-encodes
        // `filename*=`, the stored spelling holds no literal control byte, and CR/LF
        // are legal XML in the Atom `<title>` (NUL, which is not, is caught above).
        // Tightening this would change what uploads are accepted — a separate decision.
        assert!("a%0D%0Ab.jpg".parse::<Filename>().is_ok());
    }

    #[test]
    fn from_str_distinguishes_non_canonical_from_a_bad_leaf() {
        // Check order matters: `a/b.txt` is BOTH an unsafe leaf and non-canonical, and
        // must still report the leaf failure. A merely-unencoded name reports the new
        // variant.
        assert!(matches!(
            "a/b.txt".parse::<Filename>().expect_err("not a leaf"),
            InvalidFilename::NotASafeLeaf
        ));
        assert!(matches!(
            "my photo.jpg"
                .parse::<Filename>()
                .expect_err("not canonical"),
            InvalidFilename::NotCanonical
        ));
    }
    #[test]
    fn a_literal_percent_round_trips() {
        // The case that exposes a double-encode or double-decode.
        let f = Filename::sanitized("50%.jpg").expect("valid leaf");
        assert_eq!(f, "50%25.jpg");
        assert_eq!(f.decoded(), "50%.jpg");
        assert!(
            f.as_ref().parse::<Filename>().is_ok(),
            "a canonical value must re-parse"
        );
    }
    #[test]
    fn decoded_segment_re_encodes_the_decoded_segment() {
        // The serve door: axum hands us the decoded name; the stored form must come back.
        assert_eq!(
            Filename::from_decoded_segment("my photo.jpg").expect("a safe decoded leaf"),
            "my%20photo.jpg"
        );
    }
    #[test]
    fn decoded_segment_output_always_satisfies_filename() {
        for raw in [
            "photo.jpg",
            "my photo.jpg",
            "50%.jpg",
            "résumé.pdf",
            ".hiddenfile",
        ] {
            let f = Filename::from_decoded_segment(raw).expect("a safe decoded leaf");
            assert!(
                f.as_ref().parse::<Filename>().is_ok(),
                "must re-parse: {raw:?}"
            );
        }
    }
    #[test]
    fn from_str_rejects_an_over_long_canonical_name() {
        // At `FromStr` the value is already encoded, so the bound is a plain byte count.
        let over = "a".repeat(MAX_FILENAME_ENCODED_BYTES + 1);
        assert!(matches!(
            over.parse::<Filename>().expect_err("over budget"),
            InvalidFilename::TooLong { .. }
        ));
    }
    #[test]
    fn decoded_segment_rejects_a_name_whose_encoded_form_exceeds_the_budget() {
        // #708's original case, relocated: the decoded-segment door receives the decoded
        // name, so this is where "100 chars, 200 raw bytes, 600 encoded" is still the
        // hazard a char-count bound would miss.
        let raw = "ä".repeat(100);
        let err =
            Filename::from_decoded_segment(&raw).expect_err("an over-budget name must be rejected");
        assert!(matches!(err, InvalidFilename::TooLong { .. }), "{err}");
        let msg = err.to_string();
        assert!(msg.contains("percent-encoded"), "{msg}");
        assert!(msg.contains("255"), "{msg}");
    }
}
