use std::fmt::Write;
use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A validated media content hash: exactly 64 lowercase hex characters
/// (`[0-9a-f]{64}`), the canonical `format!("{digest:x}")` form of a SHA-256
/// digest. Introducing the type means an arbitrary string can no longer be passed
/// where a media content hash is expected (a transposition hazard, ADR-0063 §1).
///
/// [`FromStr`] is the single validating chokepoint — it delegates to
/// [`is_valid_content_hash`], the one source of truth for "canonical content
/// hash". The rest of the ADR-0063 string-newtype trailer (`Display`, `AsRef<str>`,
/// `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde bridge) is generated by
/// `#[derive(StrNewtype)]`, so a `ContentHash` serializes as a plain string and
/// rejects invalid input on the wire — safe to use as a (de)serialized DTO field.
///
/// The wrapped `String` is private, so the only way in is a validating parse or
/// the trusted [`from_digest`][ContentHash::from_digest] door — an arbitrary
/// `String` cannot masquerade as a content hash.
///
/// The positive companion shows the identical fixture compiles — the path resolves
/// and the validating door accepts a canonical 64-hex digest — so each
/// `compile_fail` below fails for the private field, not for a moved path.
/// (Fixture lines are hidden with `#`.)
///
/// ```
/// use common::media::ContentHash;
/// use std::str::FromStr;
/// let h = ContentHash::from_str(
///     "0000000000000000000000000000000000000000000000000000000000000000",
/// )
/// .unwrap();
/// let _read: &str = h.as_ref();
/// ```
///
/// No public constructor:
/// ```compile_fail
/// # use common::media::ContentHash;
/// # use std::str::FromStr;
/// let _ = ContentHash("abc".to_string()); // private field
/// ```
///
/// A `String` does not convert to a `ContentHash`. Asserted on `.into()`, not on a
/// function argument: an argument is never coerced through `From`, so
/// `takes_hash(String)` fails for any two distinct types and would keep failing
/// even if the `From<String>` impl this forbids were added.
/// ```compile_fail
/// # use common::media::ContentHash;
/// # use std::str::FromStr;
/// let _h: ContentHash = "abc".to_string().into();
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct ContentHash(String);

/// Error returned when a string cannot be parsed as a [`ContentHash`].
#[derive(Debug, Error)]
#[error("content hash must be 64 lowercase hex characters ([0-9a-f]{{64}})")]
pub struct InvalidContentHash;

impl FromStr for ContentHash {
    type Err = InvalidContentHash;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if is_valid_content_hash(s) {
            Ok(ContentHash(s.to_owned()))
        } else {
            Err(InvalidContentHash)
        }
    }
}

impl ContentHash {
    /// Builds a [`ContentHash`] from the raw 32 bytes of a SHA-256 digest,
    /// lowercase-hex-encoding them here so the caller never spells the format.
    /// This is the trusted producer door — validity is **structural**: 32 bytes
    /// always encode to exactly 64 lowercase hex characters, so an invalid hash
    /// cannot be constructed (unlike a byte-slice or string door). A digest from
    /// `sha2` reaches it directly with `.into()`:
    /// `ContentHash::from_digest(Sha256::digest(bytes).into())`.
    ///
    /// A hash arriving as a **string** — a URL path segment, a `#[server]` wire
    /// arg, or a value read back from the `sha256` column — is not a digest here;
    /// it goes through [`FromStr`]/`TryFrom`, which validate the canonical form.
    #[must_use]
    pub fn from_digest(digest: [u8; 32]) -> Self {
        let mut hex = String::with_capacity(64);
        for byte in digest {
            // Infallible: writing to a String never errors.
            let _ = write!(hex, "{byte:02x}");
        }
        ContentHash(hex)
    }
}

/// Returns true if `hash` is a canonical content hash: exactly 64 lowercase
/// hex characters (`[0-9a-f]{64}`), the form produced by `format!("{digest:x}")`
/// for a SHA-256 digest.
///
/// Callers that accept a hash from an untrusted source (e.g. a URL path
/// segment) must check this before slicing or joining it into a path:
/// [`path`] slices `sha256[..2]`/`[2..4]` unguarded, which panics on a
/// shorter string or one whose byte index 2 is not a UTF-8 char boundary.
#[must_use]
pub fn is_valid_content_hash(hash: &str) -> bool {
    hash.len() == 64
        && hash
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

#[cfg(test)]
mod tests {
    use crate::test_support::MEDIA_TEST_SHA256;
    use sha2::{Digest, Sha256};

    use super::*;

    #[test]
    fn valid_content_hash_accepts_64_lowercase_hex() {
        let hash = "a".repeat(64);
        assert!(is_valid_content_hash(&hash));
        // A realistic lowercase sha256 hex digest.
        assert!(is_valid_content_hash(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        ));
    }

    #[test]
    fn valid_content_hash_rejects_short_input() {
        // A single byte cannot be sliced at [2..]; short input must reject, not panic.
        assert!(!is_valid_content_hash("a"));
        assert!(!is_valid_content_hash(""));
        assert!(!is_valid_content_hash(&"a".repeat(63)));
    }

    #[test]
    fn valid_content_hash_rejects_long_input() {
        assert!(!is_valid_content_hash(&"a".repeat(65)));
    }

    #[test]
    fn valid_content_hash_rejects_uppercase_hex() {
        // Stored digests are lowercase (`format!("{digest:x}")`); uppercase is not canonical.
        assert!(!is_valid_content_hash(&"A".repeat(64)));
    }

    #[test]
    fn valid_content_hash_rejects_non_hex_chars() {
        // 64 chars but contains a non-hex letter.
        assert!(!is_valid_content_hash(&format!("g{}", "a".repeat(63))));
        // 64 chars but contains a path separator.
        assert!(!is_valid_content_hash(&format!("/{}", "a".repeat(63))));
    }

    #[test]
    fn valid_content_hash_rejects_non_ascii_off_boundary() {
        // A multi-byte char makes byte index 2 land off a UTF-8 boundary — the
        // other off-boundary slice hazard: build a 64-byte string whose char
        // boundaries do not align with byte 2. It must reject, not panic.
        let hash = format!("é{}", "a".repeat(62));
        assert!(!is_valid_content_hash(&hash));
    }

    #[test]
    fn content_hash_parses_canonical_digest() {
        let h: ContentHash = MEDIA_TEST_SHA256.parse().unwrap();
        assert_eq!(h, MEDIA_TEST_SHA256);
    }

    #[test]
    fn content_hash_rejects_non_canonical_forms() {
        // Reuses the `is_valid_content_hash` invariants: short, long, uppercase,
        // non-hex, off-boundary.
        assert!("a".parse::<ContentHash>().is_err());
        assert!("a".repeat(63).parse::<ContentHash>().is_err());
        assert!("a".repeat(65).parse::<ContentHash>().is_err());
        assert!("A".repeat(64).parse::<ContentHash>().is_err());
        assert!(
            format!("g{}", "a".repeat(63))
                .parse::<ContentHash>()
                .is_err()
        );
        assert!(
            format!("é{}", "a".repeat(62))
                .parse::<ContentHash>()
                .is_err()
        );
    }

    #[test]
    fn content_hash_display_produces_the_canonical_string() {
        let h: ContentHash = MEDIA_TEST_SHA256.parse().unwrap();
        assert_eq!(h.to_string(), MEDIA_TEST_SHA256);
    }

    #[test]
    fn content_hash_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let h: ContentHash = MEDIA_TEST_SHA256.parse().unwrap();
        assert_eq!(
            serde_json::to_string(&h).unwrap(),
            format!("\"{MEDIA_TEST_SHA256}\"")
        );

        // Deserialize routes through the validating parse.
        assert_eq!(
            serde_json::from_str::<ContentHash>(&format!("\"{MEDIA_TEST_SHA256}\"")).unwrap(),
            h
        );
        // Invalid input is rejected at deserialize time (wire rejection).
        assert!(serde_json::from_str::<ContentHash>("\"not-a-hash\"").is_err());
    }

    #[test]
    fn content_hash_from_digest_hex_encodes_the_32_digest_bytes() {
        // The producer door hex-encodes exactly 32 bytes into the canonical
        // 64-char lowercase form — always a valid ContentHash by construction.
        assert_eq!(ContentHash::from_digest([0u8; 32]), "0".repeat(64).as_str());
        assert_eq!(
            ContentHash::from_digest([0xab; 32]),
            "ab".repeat(32).as_str()
        );
        // A real digest round-trips: its hex equals the canonical string form.
        let digest: [u8; 32] = Sha256::digest(b"").into();
        assert_eq!(ContentHash::from_digest(digest), MEDIA_TEST_SHA256);
    }

    #[test]
    fn content_hash_invalid_error_displays_the_rule() {
        let msg = "bad".parse::<ContentHash>().unwrap_err().to_string();
        assert!(msg.contains("64 lowercase hex"), "{msg}");
    }

    // --- Filename: Door A (validating FromStr, canonical-only) ---
}
