use std::path::Path;
use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

use super::filename::Filename;

/// A media `Content-Type` header value — a `type/subtype` media type with optional
/// `;`-separated parameters (e.g. `image/png`, `text/html; charset=utf-8`). Introducing
/// the type means an arbitrary string can no longer stand in for a media content type
/// (ADR-0063 §1), and every accepted value is a valid HTTP header / Atom `type=` value.
///
/// [`FromStr`] is the single validating chokepoint — it delegates to the private
/// `is_valid_content_type`. The rest of the ADR-0063 string-newtype trailer (`Display`,
/// `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde + sqlx bridges) is generated by
/// `#[derive(StrNewtype)]`. The wrapped `String` is private, so the only way in is the
/// validating door — an arbitrary `String` cannot masquerade as a content type:
///
/// The positive companion shows the identical fixture compiles — the path resolves
/// and the validating door accepts a real media type — so each `compile_fail`
/// below fails for the private field, not for a moved path. (Fixture lines are
/// hidden with `#`.)
///
/// ```
/// use common::media::ContentType;
/// use std::str::FromStr;
/// let t = ContentType::from_str("image/png").unwrap();
/// let _read: &str = t.as_ref();
/// ```
///
/// No public constructor:
/// ```compile_fail
/// # use common::media::ContentType;
/// # use std::str::FromStr;
/// let _ = ContentType("x".to_string()); // private field
/// ```
///
/// A `String` does not convert to a `ContentType` (asserted on `.into()`, so the
/// proof still fails if a `From<String>` impl is added — a function argument would
/// not):
/// ```compile_fail
/// # use common::media::ContentType;
/// # use std::str::FromStr;
/// let _t: ContentType = "image/png".to_string().into();
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct ContentType(String);

impl ContentType {
    /// Mint a `ContentType` from a string the caller asserts is a valid media type —
    /// a fixed `&'static` literal or other known-valid source — bypassing the
    /// [`FromStr`] check. The trusted-producer door, `pub(crate)` so outside this crate
    /// the only way in stays the validating `FromStr`.
    ///
    /// Grepping `ContentType::from_trusted` enumerates every mint site, and each is
    /// pinned by a test that the value is valid (`detect_content_type_outputs_are_valid`,
    /// `feed_path::…::format_content_types`). That is a convention backed by those
    /// tests, not a build-time guarantee.
    #[must_use]
    pub(crate) fn from_trusted(content_type: impl Into<String>) -> Self {
        Self(content_type.into())
    }

    /// PNG image media type.
    #[must_use]
    pub fn image_png() -> Self {
        Self::from_trusted("image/png")
    }
}

/// Error returned when a string is not a valid media `Content-Type` value.
#[derive(Debug, Error)]
#[error("content type must be a `type/subtype` media type, e.g. `image/png`")]
pub struct InvalidContentType;

impl FromStr for ContentType {
    type Err = InvalidContentType;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if is_valid_content_type(s) {
            Ok(ContentType(s.to_owned()))
        } else {
            Err(InvalidContentType)
        }
    }
}

/// An RFC 7230 `tchar` (the token characters a `type`/`subtype` may use).
fn is_tchar(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b"!#$%&'*+-.^_`|~".contains(&b)
}

/// Whether `s` is a valid media `Content-Type`: every byte a valid `HeaderValue` byte
/// (`VCHAR` / SP / HTAB), and the essence (before the first `;`) is `token "/" token` with
/// non-empty, `tchar`-only halves. Parameters (after `;`) need only be header-safe — so
/// every accepted value is `HeaderValue::from_str`-constructible. The single source of
/// truth for [`ContentType`]'s invariant.
fn is_valid_content_type(s: &str) -> bool {
    if !s.bytes().all(|b| b == b'\t' || (0x20..=0x7e).contains(&b)) {
        return false;
    }
    // The essence is everything before the first `;` (or the whole string when there is no
    // parameter list); RFC 7231 permits optional whitespace around it, so trim for the check.
    let essence = s.split_once(';').map_or(s, |(before, _)| before).trim();
    let Some((ty, sub)) = essence.split_once('/') else {
        return false;
    };
    !ty.is_empty() && !sub.is_empty() && ty.bytes().all(is_tchar) && sub.bytes().all(is_tchar)
}

/// Returns true if the content type should be served inline rather than as an attachment.
#[must_use]
pub fn should_inline(content_type: &str) -> bool {
    matches!(
        content_type,
        "image/jpeg"
            | "image/png"
            | "image/gif"
            | "image/webp"
            | "image/svg+xml"
            | "audio/mpeg"
            | "audio/ogg"
            | "audio/flac"
            | "audio/wav"
            | "video/mp4"
            | "video/webm"
            | "application/pdf"
    )
}

/// Extension-based content type detection. Falls back to `application/octet-stream`.
/// Mints the [`ContentType`] via [`ContentType::from_trusted`] from its canonical
/// `&'static str` table (all valid `type/subtype` literals) — no `FromStr` round-trip,
/// since the table is fixed and known-valid (pinned by
/// `detect_content_type_outputs_are_valid`).
#[must_use]
pub fn detect_content_type(filename: &Filename) -> ContentType {
    static EXTENSIONS: [(&[&str], &str); 12] = [
        (&["jpg", "jpeg"], "image/jpeg"),
        (&["png"], "image/png"),
        (&["gif"], "image/gif"),
        (&["webp"], "image/webp"),
        (&["svg"], "image/svg+xml"),
        (&["mp3"], "audio/mpeg"),
        (&["ogg", "oga"], "audio/ogg"),
        (&["flac"], "audio/flac"),
        (&["wav"], "audio/wav"),
        (&["mp4"], "video/mp4"),
        (&["webm"], "video/webm"),
        (&["pdf"], "application/pdf"),
    ];

    let ext = Path::new(filename.decoded().as_ref())
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();

    for (extensions, content_type) in EXTENSIONS {
        if extensions.contains(&ext.as_str()) {
            return ContentType::from_trusted(content_type);
        }
    }
    ContentType::from_trusted("application/octet-stream")
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;

    /// A validated filename built through the same intake door as uploaded names.
    fn filename(name: &str) -> Filename {
        Filename::sanitized(name).expect("a media test name is a valid leaf")
    }

    /// Detect a type from an inbound filename, preserving the production boundary shape.
    fn detected_content_type(name: &str) -> ContentType {
        detect_content_type(&filename(name))
    }

    #[rstest]
    #[case::jpeg("image/jpeg", true)]
    #[case::png("image/png", true)]
    #[case::gif("image/gif", true)]
    #[case::webp("image/webp", true)]
    #[case::svg("image/svg+xml", true)]
    #[case::mpeg("audio/mpeg", true)]
    #[case::mp4("video/mp4", true)]
    #[case::pdf("application/pdf", true)]
    #[case::zip("application/zip", false)]
    #[case::text("text/plain", false)]
    #[case::octet_stream("application/octet-stream", false)]
    fn should_inline_classifies_content_types(#[case] content_type: &str, #[case] expected: bool) {
        assert_eq!(should_inline(content_type), expected);
    }

    #[rstest]
    #[case::jpeg("photo.jpg", "image/jpeg")]
    #[case::jpeg_alias("photo.jpeg", "image/jpeg")]
    #[case::png("image.png", "image/png")]
    #[case::gif("anim.gif", "image/gif")]
    #[case::webp("photo.webp", "image/webp")]
    #[case::svg("icon.svg", "image/svg+xml")]
    #[case::mpeg("track.mp3", "audio/mpeg")]
    #[case::ogg("track.ogg", "audio/ogg")]
    #[case::oga("track.oga", "audio/ogg")]
    #[case::flac("track.flac", "audio/flac")]
    #[case::wav("track.wav", "audio/wav")]
    #[case::mp4("video.mp4", "video/mp4")]
    #[case::webm("clip.webm", "video/webm")]
    #[case::pdf("doc.pdf", "application/pdf")]
    #[case::unknown_extension("file.xyz", "application/octet-stream")]
    #[case::no_extension("noext", "application/octet-stream")]
    fn detect_content_type_classifies_filenames(#[case] filename: &str, #[case] expected: &str) {
        assert_eq!(detected_content_type(filename), expected);
    }

    #[test]
    fn content_type_accepts_valid() {
        for s in [
            "image/png",
            "application/pdf",
            "image/svg+xml",
            "text/html; charset=utf-8",
            "application/octet-stream",
        ] {
            assert!(s.parse::<ContentType>().is_ok(), "must accept {s:?}");
        }
    }

    #[test]
    fn content_type_rejects_malformed() {
        for s in [
            "",
            "garbage",             // no slash
            "a/",                  // empty subtype
            "/b",                  // empty type
            "image /png",          // space in type (not a tchar)
            "text/plain; x=\u{1}", // control byte inside a parameter
            "im\u{1}age/png",      // control byte in the type
        ] {
            assert!(s.parse::<ContentType>().is_err(), "must reject {s:?}");
        }
    }

    #[test]
    fn detect_content_type_outputs_are_valid() {
        // The in-module mint is honest: every canonical literal + the fallback re-parses
        // through the validating `FromStr`, so `detect` never fabricates an invalid value.
        for f in [
            "a.jpg",
            "a.png",
            "a.gif",
            "a.webp",
            "a.svg",
            "a.mp3",
            "a.ogg",
            "a.flac",
            "a.wav",
            "a.mp4",
            "a.webm",
            "a.pdf",
            "a.unknownext",
        ] {
            assert!(
                detected_content_type(f)
                    .as_ref()
                    .parse::<ContentType>()
                    .is_ok()
            );
        }
    }
}
