use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;
use url::Url;

use super::storage::parse_stored_media_path;
use super::{ContentHash, Filename, MediaRef, MediaSource};

/// A closed classification of the URL form that named a media entry.
///
/// The storage key retains this form because local URLs are intrinsically local,
/// while absolute and scheme-relative URLs require a later live ownership check.
/// `legacy` is deliberately not a parser value; it belongs only to migrated rows.
#[macros::text_enum(
    sqlx,
    error = InvalidMediaReferenceKind,
    message = "media reference kind must be \"local\", \"absolute\", or \"scheme_relative\""
)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[strum(serialize_all = "snake_case")]
pub enum MediaReferenceKind {
    /// A relative or root-relative URL, which always names this instance.
    Local,
    /// An HTTP(S) URL with its own scheme and authority.
    Absolute,
    /// An authority-relative URL beginning with `//`.
    SchemeRelative,
}

/// The parser-canonical, fragment-free URL form retained as media-reference evidence.
///
/// A value is valid only when [`parse_media_url`] recognizes it and emits the exact
/// same form: relative and scheme-relative forms retain their authored spelling,
/// while absolute URLs use `url`'s canonical serialization. Consequently a fragment,
/// unsupported scheme, malformed URL, non-media path, or merely non-canonical absolute
/// form cannot enter persisted evidence. [`FromStr`] is the validating door used by
/// serde and the `SQLx` bridge generated by [`StrNewtype`].
///
/// The wrapped [`String`] is private. Parser output constructs it directly; all other
/// callers must parse an exact canonical form.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct MediaReferenceForm(String);

/// Error returned when a string is not an exact parser-canonical media reference form.
#[derive(Debug, Error)]
#[error("media reference form must be an exact parser-canonical media URL without a fragment")]
pub struct InvalidMediaReferenceForm;

impl FromStr for MediaReferenceForm {
    type Err = InvalidMediaReferenceForm;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let Some(reference) = parse_media_url(s) else {
            return Err(InvalidMediaReferenceForm);
        };
        if reference.reference_form.as_ref() == s {
            Ok(reference.reference_form)
        } else {
            Err(InvalidMediaReferenceForm)
        }
    }
}

/// A stored-media identity together with the complete URL form that named it.
///
/// The fields are private so a caller cannot manufacture a reference with a
/// media identity and URL evidence that the parser did not establish. The form
/// is retained exactly for local and scheme-relative input (apart from a
/// fragment, which browsers never send); absolute input uses `url`'s canonical
/// serialization.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct MediaReference {
    media: MediaRef,
    kind: MediaReferenceKind,
    reference_form: MediaReferenceForm,
}

impl MediaReference {
    /// The canonical stored entry this URL names.
    #[must_use]
    pub fn media(&self) -> &MediaRef {
        &self.media
    }

    /// The syntactic URL form that named this entry.
    #[must_use]
    pub fn kind(&self) -> MediaReferenceKind {
        self.kind
    }

    /// The fragment-free form storage persists and a live ownership resolver probes.
    #[must_use]
    pub fn reference_form(&self) -> &MediaReferenceForm {
        &self.reference_form
    }
}

/// Parses a media URL into the [`MediaReference`] it names, or `None` if it names none.
///
/// Relative and root-relative input is local. Absolute input must be HTTP(S), has a
/// canonical `url` serialization, and rejects userinfo. Scheme-relative input retains its
/// authored authority, explicit port, path, and query, while dropping its fragment. The path
/// remains the exact serve or AtomPub-member layout and filename validation is unchanged.
#[must_use]
pub fn parse_media_url(input: &str) -> Option<MediaReference> {
    let fragment_free = input.split_once('#').map_or(input, |(form, _)| form);

    if fragment_free.starts_with("//") {
        let url = Url::parse(&format!("http:{fragment_free}")).ok()?;
        if has_userinfo(fragment_free, &url) {
            return None;
        }
        return parse_media_path(url.path()).map(|media| MediaReference {
            media,
            kind: MediaReferenceKind::SchemeRelative,
            reference_form: MediaReferenceForm(fragment_free.to_owned()),
        });
    }

    if has_leading_url_scheme(fragment_free) {
        let mut url = Url::parse(fragment_free).ok()?;
        if !matches!(url.scheme(), "http" | "https") || has_userinfo(fragment_free, &url) {
            return None;
        }
        url.set_fragment(None);
        return parse_media_path(url.path()).map(|media| MediaReference {
            media,
            kind: MediaReferenceKind::Absolute,
            reference_form: MediaReferenceForm(url.into()),
        });
    }

    parse_media_path(
        fragment_free
            .split_once('?')
            .map_or(fragment_free, |(path, _)| path),
    )
    .map(|media| MediaReference {
        media,
        kind: MediaReferenceKind::Local,
        reference_form: MediaReferenceForm(fragment_free.to_owned()),
    })
}

/// Whether the input's authority carries userinfo.
///
/// `url` canonicalizes an empty `@` username away, so inspect only the original
/// authority delimiter as well as the parsed username/password.
fn has_userinfo(input: &str, url: &Url) -> bool {
    let authority = input
        .strip_prefix("//")
        .or_else(|| input.split_once("://").map(|(_, authority)| authority));
    !url.username().is_empty()
        || url.password().is_some()
        || authority.is_some_and(|authority| {
            authority
                .split_once(['/', '?'])
                .map_or(authority, |(authority, _)| authority)
                .contains('@')
        })
}

/// Whether `input` syntactically starts with an RFC 3986 scheme.
///
/// A colon in a relative path, query, or fragment does not make the input absolute.
fn has_leading_url_scheme(input: &str) -> bool {
    let Some((scheme, _)) = input.split_once(':') else {
        return false;
    };
    let mut characters = scheme.bytes();
    matches!(characters.next(), Some(b'a'..=b'z' | b'A'..=b'Z'))
        && characters.all(|character| {
            matches!(
                character,
                b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'+' | b'-' | b'.'
            )
        })
}

fn parse_media_path(path: &str) -> Option<MediaRef> {
    parse_stored_media_path(path).or_else(|| parse_atompub_media_path(path))
}

fn parse_atompub_media_path(path: &str) -> Option<MediaRef> {
    let mut segments = path.trim_start_matches('/').split('/');
    if segments.next()? != "atompub" {
        return None;
    }
    let _user = segments.next()?;
    if segments.next()? != "media" {
        return None;
    }
    let sha256: ContentHash = segments.next()?.parse().ok()?;
    let encoded_filename = segments.next()?;
    if segments.next().is_some() {
        return None;
    }
    let decoded = percent_encoding::percent_decode_str(encoded_filename)
        .decode_utf8()
        .ok()?;
    let filename = Filename::from_decoded_segment(&decoded).ok()?;
    Some(MediaRef {
        source: MediaSource::Upload,
        sha256,
        filename,
    })
}

#[cfg(test)]
mod tests {
    use crate::test_support::MEDIA_TEST_SHA256;

    use super::super::{MAX_FILENAME_ENCODED_BYTES, storage::url};
    use super::*;

    /// The canonical `Filename` for a raw (undecoded) name, via the decoded-segment door.
    fn canonical(raw: &str) -> Filename {
        Filename::from_decoded_segment(raw).expect("a legal filename")
    }

    #[test]
    fn parse_media_url_retains_local_path_and_root_relative_forms_without_fragments() {
        for form in [
            format!("media/upload/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg?download=1#preview"),
            format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg?download=1#preview"),
        ] {
            let reference = parse_media_url(&form).expect("local media URL parses");
            assert_eq!(reference.kind(), MediaReferenceKind::Local);
            assert_eq!(
                reference.reference_form(),
                form.split_once('#').map_or(form.as_str(), |(form, _)| form)
            );
        }
    }

    #[test]
    fn parse_media_url_round_trips_every_source_and_encoded_names_as_local() {
        for source in [MediaSource::Upload, MediaSource::Cached] {
            for raw in ["photo.jpg", "my photo.jpg", "ünïcode nàme.png", "100%.jpg"] {
                let filename = canonical(raw);
                let hash: ContentHash = MEDIA_TEST_SHA256.parse().unwrap();
                let url = url(&source, &hash, &filename);
                let reference = parse_media_url(&url).expect("relative media URL parses");
                assert_eq!(
                    reference.media(),
                    &MediaRef {
                        source,
                        sha256: hash,
                        filename,
                    },
                    "round trip failed for {source:?} / {raw}"
                );
                assert_eq!(reference.kind(), MediaReferenceKind::Local);
                assert_eq!(reference.reference_form(), url.as_ref());
            }
        }
    }

    #[test]
    fn parse_media_url_canonicalises_absolute_form_and_removes_fragment() {
        let path = format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg");
        let reference =
            parse_media_url(&format!("HTTPS://Example.COM:443{path}?download=1#preview"))
                .expect("absolute URL parses");
        assert_eq!(reference.kind(), MediaReferenceKind::Absolute);
        assert_eq!(
            reference.reference_form().as_ref(),
            format!("https://example.com{path}?download=1")
        );
    }

    #[test]
    fn media_reference_form_accepts_only_exact_parser_output() {
        let path = format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg");
        let canonical = format!("https://example.com{path}?download=1");
        let form: MediaReferenceForm = canonical.parse().expect("canonical form parses");
        assert_eq!(form.as_ref(), canonical);

        for invalid in [
            format!("HTTPS://Example.COM:443{path}?download=1"),
            format!("{canonical}#preview"),
            format!("ftp://example.com{path}"),
            "/not-media.jpg".to_owned(),
        ] {
            assert!(
                invalid.parse::<MediaReferenceForm>().is_err(),
                "{invalid} must not enter persisted evidence"
            );
        }
    }

    #[test]
    fn parse_media_url_preserves_scheme_relative_authority_port_path_and_query() {
        let path = format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg");
        let reference = parse_media_url(&format!("//Example.COM:8443{path}?download=1#preview"))
            .expect("scheme-relative URL parses");
        assert_eq!(reference.kind(), MediaReferenceKind::SchemeRelative);
        assert_eq!(
            reference.reference_form().as_ref(),
            format!("//Example.COM:8443{path}?download=1")
        );
    }

    #[test]
    fn parse_media_url_accepts_the_atompub_member_layout_as_upload() {
        let url = format!("/atompub/alice/media/{MEDIA_TEST_SHA256}/photo.jpg");
        let reference = parse_media_url(&url).expect("AtomPub media member URL parses");
        assert_eq!(
            reference.media(),
            &MediaRef {
                source: MediaSource::Upload,
                sha256: MEDIA_TEST_SHA256.parse().unwrap(),
                filename: canonical("photo.jpg"),
            }
        );
        assert_eq!(reference.kind(), MediaReferenceKind::Local);
        assert_eq!(reference.reference_form().as_ref(), url);
    }

    #[test]
    fn parse_media_url_canonicalises_a_raw_filename_to_the_stored_spelling() {
        let raw = format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/my photo.jpg");
        let encoded = format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/my%20photo.jpg");
        let raw_reference = parse_media_url(&raw).expect("raw spelling parses");
        let encoded_reference = parse_media_url(&encoded).expect("encoded spelling parses");
        assert_eq!(raw_reference.media(), encoded_reference.media());
        assert_ne!(
            raw_reference.reference_form(),
            encoded_reference.reference_form()
        );
        assert_eq!(raw_reference.media().filename.as_ref(), "my%20photo.jpg");
    }

    #[test]
    fn parse_media_url_rejects_non_exact_shard_prefixes() {
        for (p1, p2) in [("ff", "b0"), ("e3", "ff"), ("e", "b0"), ("e3", "b")] {
            assert_eq!(
                parse_media_url(&format!(
                    "/media/upload/{p1}/{p2}/{MEDIA_TEST_SHA256}/photo.jpg"
                )),
                None
            );
        }
    }

    #[test]
    fn parse_media_url_rejects_userinfo_malformed_and_non_http_absolute_urls() {
        let path = format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg");
        for url in [
            format!("https://user:password@example.com{path}"),
            format!("https://@example.com{path}"),
            format!("https://{path}"),
            format!("https://example.com:bad{path}"),
            format!("ftp://example.com{path}"),
            format!("mailto:media@example.com{path}"),
            format!("//user:password@example.com{path}"),
            // This begins with a letter but contains a forbidden scheme byte, so
            // it must remain a relative form rather than reaching URL parsing.
            format!("http^s:{path}"),
        ] {
            assert_eq!(parse_media_url(&url), None, "{url} must not be a reference");
        }
    }

    #[test]
    fn parse_media_url_rejects_non_media_paths() {
        assert_eq!(parse_media_url("/posts/hello"), None);
        assert_eq!(parse_media_url("/media/upload/e3/b0/short/photo.jpg"), None);
        assert_eq!(
            parse_media_url(&format!(
                "/media/bogus-source/e3/b0/{MEDIA_TEST_SHA256}/photo.jpg"
            )),
            None,
            "an unknown source token is not a media URL"
        );
        assert_eq!(parse_media_url(""), None);
        assert_eq!(parse_media_url("/media/upload/e3/b0"), None);
        assert_eq!(
            parse_media_url(&format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/a/b.jpg")),
            None,
            "the filename is one segment, so a deeper path is not this layout"
        );
        assert_eq!(
            parse_media_url(&format!(
                "/atompub/alice/not-media/{MEDIA_TEST_SHA256}/photo.jpg"
            )),
            None,
            "the AtomPub member layout requires its media segment"
        );
        assert_eq!(
            parse_media_url(&format!(
                "/atompub/alice/media/{MEDIA_TEST_SHA256}/photo.jpg/extra"
            )),
            None,
            "the AtomPub filename is the final path segment"
        );
    }

    #[test]
    fn media_refs_order_by_source_then_hash_then_filename() {
        // The ordering exists so a set of references serializes one way for one body:
        // extraction collects into a `BTreeSet`, so this is what makes the written rows
        // deterministic rather than hash-order.
        let hash: ContentHash = MEDIA_TEST_SHA256.parse().unwrap();
        let make = |source, name| MediaRef {
            source,
            sha256: hash.clone(),
            filename: canonical(name),
        };

        // Same hash: the filename breaks the tie.
        assert!(
            make(MediaSource::Upload, "a.jpg") < make(MediaSource::Upload, "b.jpg"),
            "filename orders last"
        );
        // The source dominates the filename. Which source sorts first is the *derived*
        // order — by variant declaration, so `Upload` before `Cached` — not the
        // lexicographic order of their tokens, which would put `cached` first. Nothing
        // depends on the direction; the ordering exists only so one body yields one
        // byte-identical set of rows.
        assert!(
            make(MediaSource::Upload, "z.jpg") < make(MediaSource::Cached, "a.jpg"),
            "source orders first"
        );

        let mut sorted = [
            make(MediaSource::Cached, "z.jpg"),
            make(MediaSource::Upload, "b.jpg"),
            make(MediaSource::Upload, "a.jpg"),
        ];
        sorted.sort();
        let names: Vec<&str> = sorted.iter().map(|r| r.filename.as_ref()).collect();
        // Both `Upload`s first (source dominates), `a` before `b` within them, and the
        // `Cached` one last regardless of its filename sorting first.
        assert_eq!(names, ["a.jpg", "b.jpg", "z.jpg"]);
    }

    #[test]
    fn media_refs_deduplicate_in_a_btree_set() {
        // A post embedding the same image twice must yield one row, without needing
        // dialect-divergent conflict handling at the insert.
        let hash: ContentHash = MEDIA_TEST_SHA256.parse().unwrap();
        let one = MediaRef {
            source: MediaSource::Upload,
            sha256: hash,
            filename: canonical("photo.jpg"),
        };
        let set: std::collections::BTreeSet<MediaRef> =
            [one.clone(), one.clone(), one].into_iter().collect();
        assert_eq!(set.len(), 1);
    }

    #[test]
    fn parse_media_url_rejects_a_filename_the_stored_door_would_reject() {
        // An over-budget or unsafe segment cannot name a stored entry, so it is not a
        // reference — the decoded-segment door is the single arbiter of that.
        let long = "a".repeat(MAX_FILENAME_ENCODED_BYTES + 1);
        assert_eq!(
            parse_media_url(&format!("/media/upload/e3/b0/{MEDIA_TEST_SHA256}/{long}")),
            None
        );
    }
}
