use std::str::FromStr;

use macros::StrNewtype;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{media::ContentType, tag::Tag, username::Username};

/// A validated, canonical feed identity path (e.g. `/feed.rss`,
/// `/~alice/tags/rust/feed.atom`): the dedup/SQL key for `feed_cache` and
/// `feed_events`. Its *identity* — constructed via [`FromStr`] (untrusted
/// strings) or [`canonical`](FeedPath::canonical) (an already-decomposed
/// surface). The trailer (`Display`, `AsRef`/`Borrow`/`Deref<str>`,
/// `TryFrom<String>`, `From<Self> for String`, `PartialEq<str>`, and the
/// validating serde bridge) is generated by `#[derive(StrNewtype)]` (ADR-0063);
/// only `canonical` and the normalizing `FromStr` are hand-written. Keeps `Hash`
/// (it is a `HashMap` key in the feed worker); no `Ord` — feed paths are never
/// sorted.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct FeedPath(String);

/// Error returned when a string is not a valid canonical feed path.
#[derive(Debug, Error)]
#[error("not a valid feed path (expected a canonical /…/feed.{{rss,atom,json}} path)")]
pub struct InvalidFeedPath;

impl FeedPath {
    /// Infallible, provenance-guaranteed constructor: a `(surface, format)` pair
    /// is *always* a valid canonical path, so this cannot fail. Used by the
    /// identity-key producers that already hold a decomposed surface
    /// ([`affected_feed_urls`], the feed handlers), so they skip the fallible
    /// [`FromStr`] reparse. Delegates the format logic to [`canonicalize`] — its
    /// single source of truth.
    #[must_use]
    pub fn canonical(surface: &FeedSurface, format: FeedFormat) -> Self {
        Self(canonicalize(surface, format))
    }
}

impl FromStr for FeedPath {
    type Err = InvalidFeedPath;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        // `parse` is the grammar; re-canonicalize so the stored form is *the*
        // canonical spelling (idempotent — normalizes case in user/tag segments).
        let (surface, format) = parse(s).ok_or(InvalidFeedPath)?;
        Ok(Self::canonical(&surface, format))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FeedFormat {
    Rss,
    Atom,
    Json,
}

impl FeedFormat {
    #[must_use]
    pub fn ext(self) -> &'static str {
        match self {
            FeedFormat::Rss => "rss",
            FeedFormat::Atom => "atom",
            FeedFormat::Json => "json",
        }
    }
    /// The media `Content-Type` served for this feed format. Minted via the trusted
    /// [`ContentType::from_trusted`] door from a fixed, known-valid `&'static` literal
    /// (like `detect_content_type`) — `format_content_types` pins that each literal is a
    /// valid media type, so an edit to an invalid one fails the build, not production.
    #[must_use]
    pub fn content_type(self) -> ContentType {
        let literal = match self {
            FeedFormat::Rss => "application/rss+xml; charset=utf-8",
            FeedFormat::Atom => "application/atom+xml; charset=utf-8",
            FeedFormat::Json => "application/feed+json",
        };
        ContentType::from_trusted(literal)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum FeedSurface {
    Site,
    SiteTag { tag: Tag },
    User { username: Username },
    UserTag { username: Username, tag: Tag },
}

#[must_use]
pub fn canonicalize(surface: &FeedSurface, format: FeedFormat) -> String {
    let ext = format.ext();
    match surface {
        FeedSurface::Site => format!("/feed.{ext}"),
        FeedSurface::SiteTag { tag } => format!("/tags/{tag}/feed.{ext}"),
        FeedSurface::User { username } => format!("/~{username}/feed.{ext}"),
        FeedSurface::UserTag { username, tag } => format!("/~{username}/tags/{tag}/feed.{ext}"),
    }
}

/// Every feed URL a post by `username` carrying `tags` can appear on: the site
/// feed, the author's feed, and the site-/user-tag feeds for each tag — each in
/// all three [`FeedFormat`]s. Shared by the write-path feed fan-out (`web`) and
/// the feed worker's go-live pass so both enqueue exactly the same surfaces.
#[must_use]
pub fn affected_feed_urls<'a, I>(username: &Username, tags: I) -> Vec<FeedPath>
where
    I: IntoIterator<Item = &'a Tag>,
{
    let mut surfaces = vec![
        FeedSurface::Site,
        FeedSurface::User {
            username: username.clone(),
        },
    ];
    for tag in tags {
        surfaces.push(FeedSurface::SiteTag { tag: tag.clone() });
        surfaces.push(FeedSurface::UserTag {
            username: username.clone(),
            tag: tag.clone(),
        });
    }
    let mut urls = Vec::with_capacity(surfaces.len() * 3);
    for surface in &surfaces {
        for format in [FeedFormat::Rss, FeedFormat::Atom, FeedFormat::Json] {
            urls.push(FeedPath::canonical(surface, format));
        }
    }
    urls
}

#[must_use]
pub fn parse(path: &str) -> Option<(FeedSurface, FeedFormat)> {
    let rest = path.strip_prefix('/')?;
    let (head, ext) = rest.rsplit_once('.')?;
    let format = match ext {
        "rss" => FeedFormat::Rss,
        "atom" => FeedFormat::Atom,
        "json" => FeedFormat::Json,
        _ => return None,
    };
    // Head must be "feed" (site) or end in "/feed"
    let surface_part = if head == "feed" {
        return Some((FeedSurface::Site, format));
    } else {
        head.strip_suffix("/feed")?
    };
    if surface_part.is_empty() {
        return None;
    }
    // tags/:tag
    if let Some(tag) = surface_part.strip_prefix("tags/") {
        // `Tag::from_str` rejects empty input and any non-`[a-z0-9-]`
        // character (including `/`), so it subsumes the prior ad-hoc checks
        // while also rejecting inputs the old parser wrongly accepted
        // (uppercase, dots, leading hyphen, non-ASCII).
        let tag = tag.parse::<Tag>().ok()?;
        return Some((FeedSurface::SiteTag { tag }, format));
    }
    // ~:username[/tags/:tag]
    if let Some(after_tilde) = surface_part.strip_prefix('~') {
        if let Some((username, tag_part)) = after_tilde.split_once("/tags/") {
            let username = username.parse::<Username>().ok()?;
            let tag = tag_part.parse::<Tag>().ok()?;
            return Some((FeedSurface::UserTag { username, tag }, format));
        }
        let username = after_tilde.parse::<Username>().ok()?;
        return Some((FeedSurface::User { username }, format));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rt(surface: FeedSurface, format: FeedFormat) {
        let path = canonicalize(&surface, format);
        let parsed = parse(&path).expect("parses");
        assert_eq!(parsed, (surface, format));
    }

    fn tag(s: &str) -> Tag {
        s.parse().expect("valid tag")
    }

    fn user(s: &str) -> Username {
        s.parse().expect("valid username")
    }

    #[test]
    fn round_trips_all_surfaces_and_formats() {
        for format in [FeedFormat::Rss, FeedFormat::Atom, FeedFormat::Json] {
            rt(FeedSurface::Site, format);
            rt(FeedSurface::SiteTag { tag: tag("rust") }, format);
            rt(
                FeedSurface::User {
                    username: user("alice"),
                },
                format,
            );
            rt(
                FeedSurface::UserTag {
                    username: user("alice"),
                    tag: tag("rust"),
                },
                format,
            );
        }
    }

    #[test]
    fn round_trips_hyphenated_tag() {
        rt(
            FeedSurface::SiteTag {
                tag: tag("hello-world"),
            },
            FeedFormat::Rss,
        );
    }

    // Previously-divergent inputs: the old ad-hoc parser accepted these
    // (anything without '/'), but the canonical `Tag`/`Username` validators
    // reject them, so `parse()` must now refuse them too.
    #[test]
    fn rejects_inputs_the_canonical_validators_reject() {
        // `+` is not in the tag/username grammar (old parser accepted "c++").
        assert!(parse("/tags/c++/feed.rss").is_none());
        // Non-ASCII (old parser accepted "日本語").
        assert!(parse("/tags/日本語/feed.atom").is_none());
        assert!(parse("/~bob/tags/日本語/feed.json").is_none());
        // Leading hyphen is rejected by `Tag::from_str`.
        assert!(parse("/tags/-rust/feed.rss").is_none());
        // Dots in the username segment are rejected by `Username::from_str`.
        assert!(parse("/~al.ice/feed.rss").is_none());
    }

    // The canonical validators lowercase their input, so a mixed-case path
    // parses to the normalized newtype (and no longer round-trips verbatim).
    #[test]
    fn normalizes_case_via_canonical_validators() {
        assert_eq!(
            parse("/~Alice/feed.rss"),
            Some((
                FeedSurface::User {
                    username: user("alice"),
                },
                FeedFormat::Rss,
            ))
        );
        assert_eq!(
            parse("/tags/Rust/feed.atom"),
            Some((FeedSurface::SiteTag { tag: tag("rust") }, FeedFormat::Atom))
        );
    }

    #[test]
    fn format_content_types() {
        use crate::test_support::parse_content_type;
        assert_eq!(
            FeedFormat::Rss.content_type(),
            parse_content_type("application/rss+xml; charset=utf-8")
        );
        assert_eq!(
            FeedFormat::Atom.content_type(),
            parse_content_type("application/atom+xml; charset=utf-8")
        );
        assert_eq!(
            FeedFormat::Json.content_type(),
            parse_content_type("application/feed+json")
        );
    }

    #[test]
    fn rejects_path_without_feed_suffix_in_subpath() {
        assert!(parse("/something/else.rss").is_none());
    }

    #[test]
    fn rejects_completely_unrecognized_path() {
        assert!(parse("/random/stuff/here.rss").is_none());
    }

    #[test]
    fn rejects_double_leading_slash() {
        // "//feed.rss" → head = "/feed", strip_suffix yields empty surface_part.
        assert!(parse("//feed.rss").is_none());
    }

    #[test]
    fn rejects_non_tag_non_user_prefix() {
        // surface_part = "something" — not tags/, not ~, no match.
        assert!(parse("/something/feed.rss").is_none());
    }

    #[test]
    fn rejects_unknown_extension() {
        assert!(parse("/feed.xml").is_none());
    }

    #[test]
    fn rejects_missing_feed_suffix() {
        assert!(parse("/~alice/profile.rss").is_none());
    }

    #[test]
    fn rejects_empty_tag() {
        assert!(parse("/tags//feed.rss").is_none());
        assert!(parse("/~alice/tags//feed.rss").is_none());
    }

    #[test]
    fn rejects_empty_username() {
        assert!(parse("/~/feed.rss").is_none());
    }

    // -- FeedPath (#399) --

    #[test]
    fn feed_path_accepts_and_roundtrips_all_canonical_surfaces() {
        for format in [FeedFormat::Rss, FeedFormat::Atom, FeedFormat::Json] {
            for surface in [
                FeedSurface::Site,
                FeedSurface::SiteTag { tag: tag("rust") },
                FeedSurface::User {
                    username: user("alice"),
                },
                FeedSurface::UserTag {
                    username: user("alice"),
                    tag: tag("rust"),
                },
            ] {
                let canon = canonicalize(&surface, format);
                let fp: FeedPath = canon.parse().expect("canonical path parses");
                assert_eq!(fp.as_ref(), canon);
                // `canonical` agrees with the free `canonicalize`.
                assert_eq!(FeedPath::canonical(&surface, format).as_ref(), canon);
            }
        }
    }

    #[test]
    fn feed_path_normalizes_case_in_segments() {
        // The one residual normalization: username/tag segments lowercase.
        assert_eq!(
            "/~Alice/feed.rss".parse::<FeedPath>().unwrap(),
            *"/~alice/feed.rss"
        );
        assert_eq!(
            "/tags/Rust/feed.atom".parse::<FeedPath>().unwrap(),
            *"/tags/rust/feed.atom"
        );
    }

    #[test]
    fn feed_path_from_str_is_idempotent() {
        let once = FeedPath::canonical(
            &FeedSurface::UserTag {
                username: user("alice"),
                tag: tag("rust"),
            },
            FeedFormat::Json,
        );
        assert_eq!(once.as_ref().parse::<FeedPath>().unwrap(), once);
    }

    #[test]
    fn feed_path_rejects_non_canonical_and_invalid() {
        for bad in [
            "/feed.xml",
            "/tags/c++/feed.rss",
            "/~/feed.rss",
            "/something/feed.rss",
            "//feed.rss",
            "not-a-feed-url",
        ] {
            assert!(bad.parse::<FeedPath>().is_err(), "should reject {bad}");
        }
    }

    #[test]
    fn feed_path_derefs_and_displays_as_str() {
        let fp = FeedPath::canonical(&FeedSurface::Site, FeedFormat::Rss);
        let coerced: &str = &fp; // Deref<str> coercion
        assert_eq!(coerced, "/feed.rss");
        assert_eq!(fp.to_string(), "/feed.rss"); // Display
        assert_eq!(fp, *"/feed.rss"); // PartialEq<str>
    }

    #[test]
    fn affected_feed_urls_yields_feed_paths() {
        let urls = affected_feed_urls(&user("alice"), [&tag("rust")]);
        assert!(urls.iter().any(|u| u.as_ref() == "/feed.rss"));
        assert!(urls.iter().all(|u| u.as_ref().starts_with('/')));
    }
}
