use std::sync::Arc;

use axum::{Router, body::Body, extract::Extension, http::Request};
use chrono::Datelike;
use common::post_title::PostTitle;
use storage::RenderedHtml;
use storage::test_support::{SeedRawPost, SeedUser};

/// A recognizable stand-in for the real `index.html`, so tests can tell a
/// shell-fallback response apart from a projected one.
pub(super) const TEST_SHELL: &str = "<!DOCTYPE html><!--test-shell--><html><body></body></html>";

/// A router carrying only the public projector routes and their storage
/// dependencies.
/// The projector is feature-independent (mounted into the live router only under
/// `csr`, but `register` itself always compiles), so registering it onto a bare
/// router exercises it directly under the default test build — no `csr` feature,
/// no full `create_router`.
pub(super) fn projector_app(state: &Arc<storage::AppState>) -> Router {
    let shell = jaunder::projector::Shell(TEST_SHELL.into());
    jaunder::projector::register(Router::new(), shell)
        .layer(Extension(state.posts.clone()))
        .layer(Extension(state.users.clone()))
        .layer(Extension(state.user_config.clone()))
        .layer(Extension(state.site_config.clone()))
}

/// Seed a published, `rust`-tagged post; returns the seeded user's username and the
/// post's autogenerated title (the tag pages assert the post is present by its title).
pub(super) async fn seed_tagged_post(state: &Arc<storage::AppState>) -> (String, PostTitle) {
    let user = SeedUser::new().seed(state).await;
    let post = SeedRawPost::new(user.user_id)
        .tags(["rust"])
        .seed(state)
        .await;
    (user.username.to_string(), post.title)
}

/// Seed a published post and return the permalink components (username, y, m, d, slug)
/// plus the post's autogenerated title and rendered HTML for the projected-content
/// assertions.
pub(super) async fn seed_published_post(
    state: &Arc<storage::AppState>,
) -> (String, i32, u32, u32, String, PostTitle, RenderedHtml) {
    let user = SeedUser::new().seed(state).await;
    let post = SeedRawPost::new(user.user_id).seed(state).await;
    let published_at = post.published_at.expect("seeded post is published");
    (
        user.username.to_string(),
        published_at.value().year(),
        published_at.value().month(),
        published_at.value().day(),
        post.slug.to_string(),
        post.title,
        post.rendered_html,
    )
}

pub(super) fn get(uri: &str) -> Request<Body> {
    Request::builder()
        .method("GET")
        .uri(uri)
        .body(Body::empty())
        .unwrap()
}
