use std::sync::Arc;

use axum::{
    body::Body,
    extract::Extension,
    http::{header, Request, StatusCode},
    Router,
};
use chrono::Datelike;
use common::post_title::PostTitle;
use storage::RenderedHtml;
use tower::ServiceExt;

use rstest::*;
use rstest_reuse::*;

use storage::test_support::{backends, Backend, SeedRawPost, SeedUser, TestEnv};

/// A recognizable stand-in for the real `index.html`, so tests can tell a
/// shell-fallback response apart from a projected one.
const TEST_SHELL: &str = "<!DOCTYPE html><!--test-shell--><html><body></body></html>";

/// A router carrying only the public projector routes plus the posts store.
///
/// The projector is feature-independent (mounted into the live router only under
/// `csr`, but `register` itself always compiles), so registering it onto a bare
/// router exercises it directly under the default test build — no `csr` feature,
/// no full `create_router`.
fn projector_app(state: &Arc<storage::AppState>) -> Router {
    let shell = jaunder::projector::Shell(TEST_SHELL.into());
    jaunder::projector::register(Router::new(), shell)
        .layer(Extension(state.posts.clone()))
        .layer(Extension(state.users.clone()))
}

/// Seed a published, `rust`-tagged post; returns the seeded user's username and the
/// post's autogenerated title (the tag pages assert the post is present by its title).
async fn seed_tagged_post(state: &Arc<storage::AppState>) -> (String, PostTitle) {
    let user = SeedUser::new().seed(state).await;
    let post = SeedRawPost::new(user.user_id)
        .tags(["rust"])
        .seed(state)
        .await;
    (user.username.to_string(), post.title)
}

/// Seed a published post and return the permalink components (username, y, m, d, slug)
/// plus the post's autogenerated title and rendered HTML for the projected-content
/// assertions.
async fn seed_published_post(
    state: &Arc<storage::AppState>,
) -> (String, i32, u32, u32, String, PostTitle, RenderedHtml) {
    let user = SeedUser::new().seed(state).await;
    let post = SeedRawPost::new(user.user_id).seed(state).await;
    let published_at = post.published_at.expect("seeded post is published");
    (
        user.username.to_string(),
        published_at.year(),
        published_at.month(),
        published_at.day(),
        post.slug.to_string(),
        post.title,
        post.rendered_html,
    )
}

fn get(uri: &str) -> Request<Body> {
    Request::builder()
        .method("GET")
        .uri(uri)
        .body(Body::empty())
        .unwrap()
}

#[apply(backends)]
#[tokio::test]
async fn permalink_projects_cacheable_crawlable_html(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, y, m, d, slug, title, rendered_html) = seed_published_post(&state).await;
    let uri = format!("/~{u}/{y}/{m}/{d}/{slug}");

    let resp = projector_app(&state)
        .oneshot(get(&uri))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "published permalink → 200");
    assert!(
        resp.headers().get(header::ETAG).is_some(),
        "ETag header present"
    );
    let body1 = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body1);

    // Crawlable, JS-off: real content is in the served HTML.
    assert!(html.contains(title.as_ref()), "title present: {html}");
    assert!(
        html.contains(rendered_html.as_ref()),
        "rendered post body injected raw"
    );
    // The seed blob + CSR boot are embedded for the client to adopt.
    assert!(html.contains(r#"id="jaunder-seed""#), "data blob present");
    assert!(html.contains("/pkg/jaunder.js"), "CSR boot script present");

    // Byte-identical on repeat — no per-request variation, so CDN-cacheable.
    let body2 = axum::body::to_bytes(
        projector_app(&state)
            .oneshot(get(&uri))
            .await
            .unwrap()
            .into_body(),
        usize::MAX,
    )
    .await
    .unwrap();
    assert_eq!(body1, body2, "identical bytes per URL");
}

#[apply(backends)]
#[tokio::test]
async fn permalink_unknown_serves_spa_shell(#[case] backend: Backend) {
    // A URL with no anonymous-public post (nonexistent, or a draft only its
    // author may see) must serve the SPA shell — not a hard 404 — so the CSR
    // client resolves it with the session (draft view, or a client-side 404).
    let TestEnv { state, base: _base } = backend.setup().await;
    let resp = projector_app(&state)
        .oneshot(get("/~ghost/2026/1/2/missing"))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "no public post → SPA shell");
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body);
    assert!(html.contains("test-shell"), "served the SPA shell: {html}");
    assert!(
        !html.contains("jaunder-seed"),
        "no projected content for a nonexistent post"
    );
}

#[apply(backends)]
#[tokio::test]
async fn permalink_invalid_segment_serves_shell(#[case] backend: Backend) {
    // An unparseable username segment (a dot is not allowed) is never public
    // content — serve the shell and let the client route it.
    let TestEnv { state, base: _base } = backend.setup().await;
    let resp = projector_app(&state)
        .oneshot(get("/~in.valid/2026/1/2/slug"))
        .await
        .expect("request");
    assert_eq!(
        resp.status(),
        StatusCode::OK,
        "unparseable segment → SPA shell"
    );
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    assert!(String::from_utf8_lossy(&body).contains("test-shell"));
}

#[apply(backends)]
#[tokio::test]
async fn permalink_stale_if_none_match_serves_full_200(#[case] backend: Backend) {
    // A non-matching `If-None-Match` must not 304 — the client's cached copy is
    // stale, so serve the full document.
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, y, m, d, slug, ..) = seed_published_post(&state).await;
    let uri = format!("/~{u}/{y}/{m}/{d}/{slug}");
    let req = Request::builder()
        .method("GET")
        .uri(&uri)
        .header(header::IF_NONE_MATCH, "\"sha256-stale\"")
        .body(Body::empty())
        .unwrap();
    let resp = projector_app(&state).oneshot(req).await.expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "stale ETag → full 200");
}

#[apply(backends)]
#[tokio::test]
async fn permalink_if_none_match_returns_304(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, y, m, d, slug, ..) = seed_published_post(&state).await;
    let uri = format!("/~{u}/{y}/{m}/{d}/{slug}");

    let resp = projector_app(&state)
        .oneshot(get(&uri))
        .await
        .expect("request");
    let etag = resp
        .headers()
        .get(header::ETAG)
        .unwrap()
        .to_str()
        .unwrap()
        .to_string();

    let conditional = Request::builder()
        .method("GET")
        .uri(&uri)
        .header(header::IF_NONE_MATCH, &etag)
        .body(Body::empty())
        .unwrap();
    let resp = projector_app(&state)
        .oneshot(conditional)
        .await
        .expect("request");
    assert_eq!(
        resp.status(),
        StatusCode::NOT_MODIFIED,
        "matching If-None-Match → 304"
    );
}

#[apply(backends)]
#[tokio::test]
async fn profile_projects_user_timeline(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, .., title, _rendered_html) = seed_published_post(&state).await;
    let resp = projector_app(&state)
        .oneshot(get(&format!("/~{u}")))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "profile → 200");
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body);
    assert!(
        html.contains(&format!("Posts by {u}")),
        "profile heading: {html}"
    );
    assert!(html.contains(title.as_ref()), "post title present");
    assert!(html.contains(r#"id="jaunder-seed""#), "data blob present");
}

#[apply(backends)]
#[tokio::test]
async fn site_timeline_projects_local_posts(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (.., title, _rendered_html) = seed_published_post(&state).await;
    let resp = projector_app(&state)
        .oneshot(get("/"))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "root site timeline → 200");
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body);
    assert!(html.contains(title.as_ref()), "post present: {html}");
    assert!(html.contains(r#"id="jaunder-seed""#), "data blob present");
}

#[apply(backends)]
#[tokio::test]
async fn profile_invalid_username_serves_shell(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let resp = projector_app(&state)
        .oneshot(get("/~in.valid"))
        .await
        .expect("request");
    assert_eq!(
        resp.status(),
        StatusCode::OK,
        "unparseable username → shell"
    );
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    assert!(String::from_utf8_lossy(&body).contains("test-shell"));
}

#[apply(backends)]
#[tokio::test]
async fn site_tag_projects_tagged_posts(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (_u, title) = seed_tagged_post(&state).await;
    let resp = projector_app(&state)
        .oneshot(get("/tags/rust"))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "site tag → 200");
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body);
    assert!(html.contains("#rust"), "tag heading: {html}");
    assert!(html.contains(title.as_ref()), "tagged post present");
    assert!(html.contains(r#"id="jaunder-seed""#), "data blob present");
}

#[apply(backends)]
#[tokio::test]
async fn user_tag_projects_tagged_posts(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, title) = seed_tagged_post(&state).await;
    let resp = projector_app(&state)
        .oneshot(get(&format!("/~{u}/tags/rust")))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "user tag → 200");
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body);
    assert!(html.contains(title.as_ref()), "tagged post present: {html}");
    assert!(html.contains(r#"id="jaunder-seed""#), "data blob present");
}

#[apply(backends)]
#[tokio::test]
async fn site_tag_invalid_serves_shell(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let resp = projector_app(&state)
        .oneshot(get("/tags/-rust"))
        .await
        .expect("request");
    assert_eq!(resp.status(), StatusCode::OK, "unparseable tag → shell");
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    assert!(String::from_utf8_lossy(&body).contains("test-shell"));
}

#[apply(backends)]
#[tokio::test]
async fn user_tag_invalid_serves_shell(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let resp = projector_app(&state)
        .oneshot(get("/~in.valid/tags/rust"))
        .await
        .expect("request");
    assert_eq!(
        resp.status(),
        StatusCode::OK,
        "unparseable username → shell"
    );
    let body = axum::body::to_bytes(resp.into_body(), usize::MAX)
        .await
        .unwrap();
    assert!(String::from_utf8_lossy(&body).contains("test-shell"));
}

#[apply(backends)]
#[tokio::test]
async fn projected_bytes_ignore_request_auth(#[case] backend: Backend) {
    // Cacheability invariant: the projector never branches on the viewer, so a
    // request carrying a session cookie yields byte-identical output to an
    // anonymous one — one cacheable response for every visitor.
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, y, m, d, slug, ..) = seed_published_post(&state).await;
    let uri = format!("/~{u}/{y}/{m}/{d}/{slug}");
    let anon = axum::body::to_bytes(
        projector_app(&state)
            .oneshot(get(&uri))
            .await
            .unwrap()
            .into_body(),
        usize::MAX,
    )
    .await
    .unwrap();
    let with_cookie = Request::builder()
        .method("GET")
        .uri(&uri)
        .header(header::COOKIE, "session=whatever")
        .body(Body::empty())
        .unwrap();
    let authed = axum::body::to_bytes(
        projector_app(&state)
            .oneshot(with_cookie)
            .await
            .unwrap()
            .into_body(),
        usize::MAX,
    )
    .await
    .unwrap();
    assert_eq!(
        anon, authed,
        "projector output must not vary with request auth"
    );
}

#[apply(backends)]
#[tokio::test]
async fn projected_response_is_publicly_cacheable(#[case] backend: Backend) {
    let TestEnv { state, base: _base } = backend.setup().await;
    let (u, y, m, d, slug, ..) = seed_published_post(&state).await;
    let uri = format!("/~{u}/{y}/{m}/{d}/{slug}");
    let resp = projector_app(&state)
        .oneshot(get(&uri))
        .await
        .expect("request");
    let cache_control = resp
        .headers()
        .get(header::CACHE_CONTROL)
        .and_then(|v| v.to_str().ok())
        .unwrap_or_default();
    assert!(
        cache_control.contains("public"),
        "projected response must be publicly cacheable, got: {cache_control}"
    );
}
