[package]
name = "devtool"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
coverage = { path = "../coverage" }
doctests = { path = "../doctests" }
tempfile = "3"
signal-hook = "0.3"
brotli = "8"
flate2 = "1"
