use common::ids::UserId;
use common::mailer::test_utils::CapturingMailSender;
use common::test_support::parse_session_label;
use common::token::RawToken;
use common::username::Username;
use host::config_key::SiteConfigKey;
use std::sync::Arc;

use storage::test_support::{Backend, TestEnv};

/// Returns a `PathBuf` pointing to a temporary directory usable as a storage
/// root.  The caller is responsible for keeping the `TempDir` alive; this
/// function returns the inner path for convenience when lifetime management is
/// not needed (e.g. when storage is never actually written to in the test).
pub fn tmp_storage_path() -> std::path::PathBuf {
    // Return the system temp dir — the media subdirectories are created on
    // demand by the handlers, so the root just needs to exist.
    std::env::temp_dir().join("jaunder-test-storage")
}

/// The `session=<token>` cookie header value for an authenticated request — the
/// one place the session-cookie shape is written, so call sites pass the
/// `RawToken` directly instead of re-`format!`-ing it.
pub fn session_cookie(token: &RawToken) -> String {
    format!("session={token}")
}

/// The session token carried by a `Set-Cookie` header — the inverse of
/// [`session_cookie`]. Tests read the session the *cookie* establishes, because the
/// login/register response bodies no longer carry a token (#533).
///
/// # Panics
///
/// If the header is not a `session=<token>` cookie, or the token does not parse.
#[must_use]
pub fn token_from_set_cookie(set_cookie: &str) -> RawToken {
    let value = set_cookie
        .strip_prefix("session=")
        .expect("Set-Cookie is not a session cookie");
    // The cookie is `session=<token>; HttpOnly; SameSite=Lax; Path=/[; Secure]`
    // (`host::auth::session_cookie_header`), so the token runs to the first `;`.
    let token = value.split(';').next().unwrap_or(value);
    token.parse().expect("valid token in session cookie")
}

/// A user seeded together with one authenticated web session. `username` is the
/// user's autogenerated name (read it instead of hardcoding a literal); `token`
/// is the raw session token (what bearer/basic-auth callers want); `cookie()`
/// renders the `session=<token>` header for cookie-authenticated requests.
pub struct SeededSession {
    pub user_id: UserId,
    pub username: Username,
    pub token: RawToken,
}

impl SeededSession {
    /// The `session=<token>` cookie header authenticating a request as this user.
    #[must_use]
    pub fn cookie(&self) -> String {
        session_cookie(&self.token)
    }

    /// A [`SeedPost`](storage::test_support::SeedPost) pre-owned by this session's
    /// user — so authenticated tests seed a post without re-typing `session.user_id`.
    /// `.seed(&state)` still takes the state (irreducible — no ambient DB handle).
    /// The returned builder owns its typed title if one is set, so its lifetime is
    /// decoupled from `&self` (it only copies `user_id`).
    #[must_use]
    pub fn seed_post(&self) -> storage::test_support::SeedPost {
        storage::test_support::SeedPost::new(self.user_id)
    }
}

/// Issue a `"test session"` session for `user_id` — the one place the default
/// session label lives, so a `create_session`-signature change (#325) touches
/// only here.
async fn issue_session(state: &Arc<storage::AppState>, user_id: UserId) -> RawToken {
    let sessions = Arc::clone(&state.sessions);
    let label = parse_session_label("test session");
    let outcome = state
        .write_scope
        .run(|transaction| {
            Box::pin(async move { sessions.create_session(transaction, user_id, &label).await })
        })
        .await
        .expect("create session");
    match outcome {
        common::mutation::MutationOutcome::Confirmed(token) => token,
        common::mutation::MutationOutcome::CommitIndeterminate(_) => {
            panic!("test session requires a confirmed commit")
        }
    }
}

/// A session on an already-seeded `user_id`. Looks the username up so the
/// returned `SeededSession` always carries it.
pub async fn create_session_for(state: &Arc<storage::AppState>, user_id: UserId) -> SeededSession {
    let username = state
        .users
        .get_user(user_id)
        .await
        .expect("get_user")
        .expect("user exists")
        .username;
    let token = issue_session(state, user_id).await;
    SeededSession {
        user_id,
        username,
        token,
    }
}

/// Seed `seed`'s user and issue a session for it, bundling the generated
/// username onto the returned `SeededSession` (no extra lookup — `seed()` already
/// yields the name).
async fn seed_and_session(
    state: &Arc<storage::AppState>,
    seed: storage::test_support::SeedUser<'_>,
) -> SeededSession {
    let user = seed.seed(state).await;
    let token = issue_session(state, user.user_id).await;
    SeededSession {
        user_id: user.user_id,
        username: user.username,
        token,
    }
}

/// Seed a non-operator user (autogenerated username) and an authenticated web
/// session in one step — the workhorse behind the integration suite's setup.
pub async fn create_user_and_session(state: &Arc<storage::AppState>) -> SeededSession {
    seed_and_session(state, storage::test_support::SeedUser::new()).await
}

/// Like [`create_user_and_session`] but the seeded user is an operator — for the
/// operator-gated site/backup settings tests.
pub async fn create_operator_and_session(state: &Arc<storage::AppState>) -> SeededSession {
    seed_and_session(state, storage::test_support::SeedUser::new().operator()).await
}

/// An `Authorization: Basic <base64(username:token)>` header value — the app-password
/// credential the `atompub` suite sends. Takes the `RawToken` directly.
pub fn basic_header(username: &str, token: &RawToken) -> String {
    use base64::Engine as _;
    let encoded = base64::engine::general_purpose::STANDARD.encode(format!("{username}:{token}"));
    format!("Basic {encoded}")
}

/// Seeds the required `site.base_url` precondition (#560): the `AtomPub` handlers
/// compose absolute URLs from it, so any handler that emits a URL 500s when it is
/// unset. `BaseUrl` canonicalizes this to `https://example.com/` (trailing
/// slash), so composed URLs are prefixed with `https://example.com`.
pub async fn seed_base_url(state: &Arc<storage::AppState>) {
    state
        .site_config
        .set(SiteConfigKey::SiteBaseUrl, "https://example.com/")
        .await
        .unwrap();
}

/// `backend.setup()` + the required `site.base_url` seed (#560): the standard setup for a
/// test that exercises the feed/AtomPub surface, so require-base is a fixture default
/// rather than a per-test opt-in. Returns the `TestEnv` unchanged.
pub async fn setup_with_base_url(backend: Backend) -> TestEnv {
    let env = backend.setup().await;
    seed_base_url(&env.state).await;
    env
}

/// Assert exactly one email was captured, sent to `recipient`, carrying an
/// **absolute** `https://example.com{path}?token=…` link (not a relative path) —
/// the shape produced when `site.base_url` is seeded (`seed_base_url`).
pub fn assert_one_absolute_link_email(mailer: &CapturingMailSender, recipient: &str, path: &str) {
    let sent = mailer.sent();
    assert_eq!(sent.len(), 1, "expected exactly one email");
    assert_eq!(sent[0].to.len(), 1);
    assert_eq!(sent[0].to[0], recipient);
    let expected = format!("https://example.com{path}?token=");
    assert!(
        sent[0].body_text.contains(&expected),
        "email body should contain an ABSOLUTE link {expected}, got: {}",
        sent[0].body_text
    );
}

/// Assert no email was captured — a blocked or failed send.
pub fn assert_no_email(mailer: &CapturingMailSender) {
    assert_eq!(mailer.sent().len(), 0, "expected no email to be sent");
}
