//! Host-owned CSR bundle URLs and immutable asset inventory, generated by `build.rs`.

include!(concat!(env!("OUT_DIR"), "/csr_bundle_data.rs"));

/// The two semantic URLs needed to boot the CSR client, when a verified bundle was staged.
#[derive(Clone, Copy)]
pub(crate) struct BootUrls {
    pub(crate) glue: &'static str,
    pub(crate) wasm: &'static str,
}

pub(crate) fn boot_urls() -> Option<BootUrls> {
    boot_urls_from(GLUE_URL, WASM_URL)
}

fn boot_urls_from(glue: Option<&'static str>, wasm: Option<&'static str>) -> Option<BootUrls> {
    Some(BootUrls {
        glue: glue?,
        wasm: wasm?,
    })
}

pub(crate) fn is_manifest_asset(logical_path: &str) -> bool {
    MANIFEST_PATHS.binary_search(&logical_path).is_ok()
}
pub(crate) fn early_wasm_fetch_script(urls: BootUrls) -> String {
    format!(
        "<script>\n      const __jaunderWasmUrl = \"{}\";\n      window.__jaunderWasmFetch = fetch(__jaunderWasmUrl);\n    </script>",
        urls.wasm
    )
}

pub(crate) fn module_init_script(urls: BootUrls, mark: &str) -> String {
    format!(
        "<script type=\"module\">import {{initMeasured}} from \"{}\"; performance.mark(\"{}\"); initMeasured(window.__jaunderWasmFetch ?? __jaunderWasmUrl);</script>",
        urls.glue, mark
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn boot_urls_requires_both_generated_boot_roles() {
        assert!(boot_urls_from(Some("/pkg/glue.js"), Some("/pkg/client.wasm")).is_some());
        assert!(boot_urls_from(None, Some("/pkg/client.wasm")).is_none());
        assert!(boot_urls_from(Some("/pkg/glue.js"), None).is_none());
    }
}
