mod adr;
mod adr_readme;
mod audit_wasm;
mod census;
mod cli;
mod compile_cache;
pub mod coverage;
mod dispatch;
mod doc_links;
pub mod elisp_coverage;
mod files;
mod gate;
pub mod git;
mod ids;
pub mod issue;
mod lifecycle;
pub mod markers;
mod nix_build;
mod playwright_report;
pub mod pr;
mod result;
mod server_fn_coverage;
mod server_fns;
mod sh;
#[cfg(test)]
mod test_support;
mod traces;
mod wasm_budget;
mod wasm_sections;
mod wasm_symbols;
mod web_server_fns;
mod steps {
    pub mod adr_check;
    pub mod boot_decomposition_coverage;
    pub mod build_csr;
    pub mod common_host_target_closure;
    pub mod doc_links;
    pub mod doctest_fences;
    pub mod duration_budget;
    pub mod e2e_goto_wrapper_check;
    pub mod e2e_local;
    pub mod e2e_scaffold_check;
    pub mod e2e_server_fn_endpoint_check;
    pub mod e2e_telemetry_boundary_check;
    pub mod error_swallowing_inventory_check;
    pub mod flaky;
    pub mod flow_docs;
    pub mod host_tests;
    pub mod html_sink_check;
    pub mod ident_gate;
    pub mod lint_suppression_check;
    pub mod nix;
    mod process;
    pub mod proffered_secret_check;
    pub mod raw_html_door_check;
    pub mod rendered_html_compiler_boundary;
    pub mod scan;
    pub mod sequence_check;
    pub mod server_fn_coverage_check;
    pub mod server_fn_registrar_check;
    pub mod server_fn_tracing_check;
    pub mod server_fn_wire_arg_error_check;
    pub mod sqlx_newtype_bind_check;
    pub mod sqlx_newtype_decode_check;
    pub mod static_checks;
    pub mod target_arch_placement_check;
    pub mod test_local;
    pub mod test_pattern_check;
    pub mod thin_components;
    pub mod traced_context_check;
    pub mod wasm_budget;
    pub mod write_transaction_contract_check;
    pub mod xlang_literal_check;
}

pub use cli::{
    AdrCommand, Cli, Command, CoverageCommand, E2eBackend, E2eBrowser, PrCommand, PrWatchUntil,
    ServerFnCoverageCommand, TracesCommand,
};
pub use dispatch::run;
pub use lifecycle::ensure_hooks_installed;
pub use result::{CommandResult, Mode, StepResult};
