[workspace]
resolver = "3"
members = ["coverage", "csr_bundle", "devtool", "diagnostic-coverage-runtime", "doctests", "performance"]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[patch.crates-io]
orgize = { git = "https://github.com/jaunder-org/orgize", rev = "f8b7e0bb90c2b8be7869d81ea2febd723bc7013d" }
atom_syndication = { git = "https://github.com/jaunder-org/atom", rev = "921118c311d2117956d86e25052918e7c549ef00" }
lettre = { git = "https://github.com/jaunder-org/lettre", rev = "cb9e5747e5ed4012d41b5ff4bba8dd503fc148e2" }
webauthn-rs = { git = "https://github.com/jaunder-org/webauthn-rs", rev = "6d0acc73fbf4436b1ed853fa5c8a219dac304a8e" }
webauthn-rs-core = { git = "https://github.com/jaunder-org/webauthn-rs", rev = "6d0acc73fbf4436b1ed853fa5c8a219dac304a8e" }
