[workspace]
resolver = "3"
members = ["coverage", "csr_bundle", "devtool", "diagnostic-coverage-runtime", "doctests", "performance"]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[patch.crates-io]
atom_syndication = { git = "https://github.com/jaunder-org/atom", rev = "921118c311d2117956d86e25052918e7c549ef00" }
lettre = { git = "https://github.com/jaunder-org/lettre", rev = "cb9e5747e5ed4012d41b5ff4bba8dd503fc148e2" }
