//! [`AbsoluteUrl`] — a validated, normalized absolute `http(s)` URL (scheme + host +
//! path), the type for values that are *always* absolute: the site origin
//! (`SiteIdentity.base_url`), the `WebSub` hub target, and the composed feed/site URLs a
//! configured base yields. Its constructor parses + normalizes through the `url` crate
//! (host/scheme case, default-port stripping, percent-encoding, canonical root slash),
//! so two spellings of one URL are not both representable (ADR-0063, invariant axis).
//!
//! The ergonomic trailer (`Display`, `AsRef`/`Borrow`/`Deref<str>`, `TryFrom<String>`,
//! `From<Self> for String`, `PartialEq<str>`, the validating serde + sqlx bridges) is
//! generated by `#[derive(StrNewtype)]`; only the normalizing [`FromStr`] is
//! hand-written. Composition lives on the type ([`AbsoluteUrl::join`] /
//! [`compose`]) so callers stop hand-rolling `format!("{base}{path}")`.

use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A validated, normalized absolute `http(s)` URL. Construct via [`FromStr`]
/// (untrusted strings) or [`AbsoluteUrl::join`] (base + path). `Hash` is derived (it
/// may be a map key); no `Ord` — URLs are not sorted.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct AbsoluteUrl(String);

/// Error returned when a string is not a valid absolute `http(s)` URL.
#[derive(Debug, Error)]
#[error("not a valid absolute http(s) URL")]
pub struct InvalidAbsoluteUrl;

impl FromStr for AbsoluteUrl {
    type Err = InvalidAbsoluteUrl;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let url = url::Url::parse(s.trim()).map_err(|_| InvalidAbsoluteUrl)?;
        // The invariant: `http`/`https` only. `url` lowercases the scheme and, for
        // these special schemes, guarantees a non-empty host on a successful parse
        // (an empty authority is a parse error), so the scheme check is the whole
        // invariant. `url.to_string()` is the canonical form: host lowercased,
        // default port stripped, root path present, percent-encoding canonicalized.
        if !matches!(url.scheme(), "http" | "https") {
            return Err(InvalidAbsoluteUrl);
        }
        Ok(Self(url.to_string()))
    }
}

impl AbsoluteUrl {
    /// Compose this base with a (typically site-absolute) `path`, via `url`'s join.
    /// The joined result is re-validated through [`FromStr`], so a `path` that
    /// introduces a non-`http(s)` scheme is rejected. It does **not** enforce
    /// same-origin: an absolute `http` `path` resolves to its own host and is
    /// accepted — every in-tree call site passes a server-built `/…` literal, never
    /// untrusted input.
    ///
    /// # Errors
    ///
    /// Returns [`InvalidAbsoluteUrl`] if `path` cannot be joined onto the base or the
    /// joined result is not a valid absolute `http(s)` URL.
    pub fn join(&self, path: &str) -> Result<AbsoluteUrl, InvalidAbsoluteUrl> {
        let base = url::Url::parse(&self.0).map_err(|_| InvalidAbsoluteUrl)?;
        let joined = base.join(path).map_err(|_| InvalidAbsoluteUrl)?;
        joined.as_str().parse()
    }
}

/// Compose `base` + a site-absolute `path` into an absolute URL string when a base is
/// configured, else the relative `path` unchanged — preserving the caller's behavior
/// when `SiteIdentity.base_url` is unset. The base-set branch goes through
/// [`AbsoluteUrl::join`] (correct slash boundary + encoding).
///
/// Infallible by design: [`AbsoluteUrl::join`] only rejects a non-`http(s)`/unparseable
/// `path`, and every call site passes a server-built canonical `/…` path, so the error
/// is unreachable — it falls back to the relative `path` rather than surfacing a
/// `Result` no caller would branch on. Use [`AbsoluteUrl::join`] directly when the
/// error matters.
#[must_use]
pub fn compose(base: Option<&AbsoluteUrl>, path: &str) -> String {
    let Some(b) = base else {
        return path.to_owned();
    };
    match b.join(path) {
        Ok(url) => url.into(),
        Err(_) => path.to_owned(), // cov:ignore unreachable: callers pass canonical paths
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // -- FromStr: invariant + normalization (D4, D6) --

    #[test]
    fn rejects_non_http_schemes() {
        for bad in [
            "file:///etc/passwd",
            "ftp://h/x",
            "javascript:alert(1)",
            "mailto:a@b.c",
        ] {
            assert!(bad.parse::<AbsoluteUrl>().is_err(), "should reject {bad}");
        }
    }

    #[test]
    fn rejects_unparseable_or_relative() {
        for bad in ["https://", "/feed.rss", "not a url", ""] {
            assert!(bad.parse::<AbsoluteUrl>().is_err(), "should reject {bad}");
        }
    }

    #[test]
    fn normalizes_host_case_and_default_port() {
        assert_eq!(
            "https://Example.COM:443/".parse::<AbsoluteUrl>().unwrap(),
            *"https://example.com/"
        );
        assert_eq!("http://H:80/".parse::<AbsoluteUrl>().unwrap(), *"http://h/");
    }

    #[test]
    fn adds_canonical_root_slash() {
        assert_eq!(
            "https://example.com".parse::<AbsoluteUrl>().unwrap(),
            *"https://example.com/"
        );
    }

    #[test]
    fn from_str_is_idempotent() {
        let once = "https://Example.com/Path".parse::<AbsoluteUrl>().unwrap();
        assert_eq!(once.as_ref().parse::<AbsoluteUrl>().unwrap(), once);
    }

    #[test]
    fn trailer_derefs_and_displays() {
        let u = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        let s: &str = &u; // Deref<str>
        assert_eq!(s, "https://example.com/");
        assert_eq!(u.to_string(), "https://example.com/"); // Display
        assert_eq!(u, *"https://example.com/"); // PartialEq<str>
    }

    // -- join (D3) --

    #[test]
    fn join_composes_without_double_slash() {
        let base = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        assert_eq!(
            base.join("/feed.rss").unwrap(),
            *"https://example.com/feed.rss"
        );
        assert_eq!(
            base.join("/tags/rust/").unwrap(),
            *"https://example.com/tags/rust/"
        );
    }

    #[test]
    fn join_preserves_query() {
        let base = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        assert_eq!(
            base.join("/atompub/alice/posts?updated_before=x&id_before=1")
                .unwrap(),
            *"https://example.com/atompub/alice/posts?updated_before=x&id_before=1"
        );
    }

    #[test]
    fn join_of_canonical_feed_path_is_unchanged_path() {
        // percent_encode_path removal regression (AC#2): canonical feed paths need no
        // escaping.
        let base = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        assert_eq!(
            base.join("/~alice/tags/rust/feed.atom").unwrap(),
            *"https://example.com/~alice/tags/rust/feed.atom"
        );
    }

    #[test]
    fn join_rejects_non_http_result() {
        // An absolute path with a non-http(s) scheme replaces the base entirely; the
        // re-validation through FromStr then rejects it. Pins join's Err branch.
        let base = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        assert!(base.join("mailto:foo@bar.example").is_err());
        assert!(base.join("ftp://other.example/x").is_err());
    }

    #[test]
    fn join_does_not_guarantee_same_origin() {
        // Documented limitation: an absolute *http* path resolves to the other host and
        // is accepted. All real call sites pass server-built "/…" literals, never user
        // input, so this cannot fire in-tree.
        let base = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        assert_eq!(
            base.join("http://other.example/evil").unwrap(),
            *"http://other.example/evil"
        );
    }

    // -- compose: relative fallback (D3, AC#5) --

    #[test]
    fn compose_uses_base_when_present() {
        let base = "https://example.com/".parse::<AbsoluteUrl>().unwrap();
        assert_eq!(
            compose(Some(&base), "/feed.rss"),
            "https://example.com/feed.rss"
        );
    }

    #[test]
    fn compose_falls_back_to_relative_when_no_base() {
        assert_eq!(compose(None, "/feed.rss"), "/feed.rss");
        assert_eq!(compose(None, "/"), "/");
    }
}
