use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A validated audience name: non-empty after trimming, original casing preserved.
///
/// Constructed via [`FromStr`] — the single validating chokepoint; the ADR-0063
/// string-newtype trailer (`Display`, `AsRef`/`Borrow`/`Deref<str>`, owned-`String`
/// conversions, `PartialEq<str>`/`<&str>`, and the validating serde bridge that rejects
/// an empty name on the wire) is generated by `#[derive(StrNewtype)]`. Used as a typed
/// `#[server]` wire arg with client-side pre-validation (ADR-0065). No `Hash`/`Ord`:
/// never a map/set key — DB uniqueness is `UNIQUE (author_user_id, name)`, enforced by
/// the store.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct AudienceName(String);

/// Error returned when a string cannot be parsed as an [`AudienceName`].
#[derive(Debug, Error)]
#[error("audience name must not be empty")]
pub struct InvalidAudienceName;

impl FromStr for AudienceName {
    type Err = InvalidAudienceName;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() {
            return Err(InvalidAudienceName);
        }
        Ok(AudienceName(trimmed.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_and_trims_preserving_case() {
        assert_eq!(
            "  Close Friends ".parse::<AudienceName>().unwrap(),
            "Close Friends"
        );
        assert_eq!("Family".parse::<AudienceName>().unwrap(), "Family");
    }

    #[test]
    fn rejects_empty_and_whitespace_only() {
        assert!("".parse::<AudienceName>().is_err());
        assert!("   ".parse::<AudienceName>().is_err());
        assert!("\t\n".parse::<AudienceName>().is_err());
    }

    #[test]
    fn display_round_trips_the_name() {
        let n: AudienceName = "Work".parse().unwrap();
        assert_eq!(n.to_string(), "Work");
    }

    #[test]
    fn invalid_error_display_is_the_public_message() {
        assert_eq!(
            InvalidAudienceName.to_string(),
            "audience name must not be empty"
        );
    }

    #[test]
    fn serde_serializes_as_plain_string_and_rejects_empty_on_deserialize() {
        let n: AudienceName = "Friends".parse().unwrap();
        assert_eq!(serde_json::to_string(&n).unwrap(), "\"Friends\"");
        // Deserialize routes through `FromStr`, so it trims on the wire too.
        assert_eq!(
            serde_json::from_str::<AudienceName>("\" Friends \"").unwrap(),
            "Friends".parse::<AudienceName>().unwrap()
        );
        // An empty / whitespace-only value is rejected at deserialize time.
        assert!(serde_json::from_str::<AudienceName>("\"   \"").is_err());
    }
}
