//! The backup **configuration** model, shared between the server's scheduled
//! backup worker (`server::backup`) and the web admin surface that reads and
//! writes these values through `site_config`. This module holds only the value
//! types plus their validation and defaults; the actual export, archiving, and
//! retention-pruning logic lives in the `storage` and `server` crates.

use std::str::FromStr;

use croner::Cron;
use macros::{NumNewtype, StrNewtype};
use serde::{Deserialize, Serialize};
use thiserror::Error;

/// How a backup is written to its destination.
///
/// `BackupMode` is the single source of truth for its own string forms: the `strum`
/// derives (`serialize_all = "snake_case"`, mirroring serde's `rename_all`) supply
/// variant enumeration (`VARIANTS`), the wire/storage token (`AsRef<str>`), and parsing
/// (`FromStr`) — all from the variant names, so the admin `<select>` and `site_config`
/// need no hand-maintained string list. Only [`BackupMode::label`] (UI text) is authored.
#[derive(
    Clone,
    Copy,
    Debug,
    Default,
    Deserialize,
    Eq,
    PartialEq,
    Serialize,
    strum::VariantArray,
    strum::AsRefStr,
    strum::IntoStaticStr,
    strum::EnumString,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum BackupMode {
    /// An expanded directory (`backup-<timestamp>/` holding `manifest.json`, the
    /// dumped tables, and the media tree). The default.
    #[default]
    Directory,
    /// A single `backup-<timestamp>.tar.gz` archive of the same contents.
    Archive,
}

impl BackupMode {
    /// Human-facing label for the admin `<select>` (distinct from the wire token).
    /// The exhaustive match makes the compiler force a new variant to be handled here.
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            BackupMode::Directory => "Directory",
            BackupMode::Archive => "Archive",
        }
    }
}

/// A validated six-field cron schedule expression.
///
/// Constructed via [`FromStr`] — the single validating chokepoint, backed by the
/// `croner` crate — or [`BackupSchedule::default`], guaranteeing the inner string is
/// always valid. The rest of the ADR-0063 string-newtype trailer (`Display`,
/// `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde bridge) is generated by
/// `#[derive(StrNewtype)]`, so a `BackupSchedule` serializes as a plain string and
/// rejects invalid input on the wire — safe to use as a (de)serialized DTO field.
#[derive(Clone, Debug, Eq, PartialEq, StrNewtype)]
pub struct BackupSchedule(String);

/// Error returned when a string is not a valid six-field cron expression.
///
/// Carries the underlying `croner` reason behind a stable label (mirrors
/// [`common::email::InvalidEmail`](crate::email::InvalidEmail)); the field is private,
/// so the dependency type does not leak into `common`'s public surface — only its
/// `Display` string escapes.
#[derive(Debug, Error)]
#[error("invalid backup schedule: {0}")]
pub struct InvalidBackupSchedule(croner::errors::CronError);

impl FromStr for BackupSchedule {
    type Err = InvalidBackupSchedule;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        // Parse only to validate; the six-field (seconds-required) source string is what
        // we store, so an admin's expression round-trips verbatim (minus surrounding space).
        Cron::new(trimmed)
            .with_seconds_required()
            .parse()
            .map_err(InvalidBackupSchedule)?;
        Ok(Self(trimmed.to_owned()))
    }
}

impl Default for BackupSchedule {
    fn default() -> Self {
        Self("0 0 0 * * *".to_owned())
    }
}

/// The number of most-recent backups to keep. Always >= 1, so retention pruning
/// (`server::backup::prune_backups`) can never remove every backup — including one just
/// created. Constructed via [`FromStr`]/serde (both reject 0 via the min-1 bound) or
/// [`RetentionCount::default`] (7). The `NumNewtype` derive supplies the whole trailer —
/// validating `FromStr`, `value` (+ `From<Self> for usize`), `Display`, the compile-checked
/// `Default`, and the transparent-`usize` serde bridge — plus the [`InvalidRetentionCount`]
/// error type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, NumNewtype)]
#[num_newtype(
    inner = usize,
    min = 1,
    default = 7,
    error = "backup retention count must be a whole number of at least 1"
)]
pub struct RetentionCount(usize);

/// The persisted backup settings (stored in `site_config`, surfaced in the
/// admin UI, and consumed by the scheduled backup worker).
///
/// `Default` is derived: each field's own `Default` supplies the default (no destination,
/// the daily-midnight schedule, retention 7, directory mode).
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct BackupConfig {
    /// Filesystem path backups are written under. `None` means no destination is
    /// configured and scheduled backups are disabled.
    pub destination_path: Option<String>,
    /// When scheduled backups run, as a validated six-field cron expression.
    pub schedule: BackupSchedule,
    /// How many of the most recent backups to keep (>= 1); older ones are pruned.
    pub retention_count: RetentionCount,
    /// Whether each backup is written as a directory or a single archive.
    pub mode: BackupMode,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn retention_count_parses_and_rejects_zero_and_non_integers() {
        assert_eq!("1".parse::<RetentionCount>().unwrap().value(), 1);
        assert_eq!("  7  ".parse::<RetentionCount>().unwrap().value(), 7);
        for bad in ["0", "", "-1", "abc", "1.5"] {
            assert!(
                bad.parse::<RetentionCount>().is_err(),
                "{bad} should be rejected"
            );
        }
        // The domain message, not std's generic parse error.
        assert!("0"
            .parse::<RetentionCount>()
            .unwrap_err()
            .to_string()
            .starts_with("backup retention count"));
    }

    #[test]
    fn retention_count_default_is_seven_and_display_round_trips() {
        let d = RetentionCount::default();
        assert_eq!(d.value(), 7);
        assert_eq!(usize::from(d), 7); // From<Self> for the inner
        assert_eq!(d.to_string().parse::<RetentionCount>().unwrap(), d);
    }

    #[test]
    fn retention_count_serde_rejects_zero_on_the_wire() {
        let r: RetentionCount = "5".parse().unwrap();
        // Plain integer — the JSON shape is unchanged from the old `usize` field.
        assert_eq!(serde_json::to_string(&r).unwrap(), "5");
        assert_eq!(serde_json::from_str::<RetentionCount>("5").unwrap(), r);
        // The min-1 bound rejects 0 at deserialize time.
        assert!(serde_json::from_str::<RetentionCount>("0").is_err());
    }

    #[test]
    fn backup_mode_string_forms_agree_across_strum_serde_and_parse() {
        use strum::VariantArray;
        for &m in BackupMode::VARIANTS {
            // strum's wire token equals serde's serialized token — one snake_case rule.
            assert_eq!(
                serde_json::to_value(m).unwrap(),
                serde_json::Value::String(m.as_ref().to_owned())
            );
            // The `IntoStaticStr` form (the value rendered as the `<option>`) is the same token.
            assert_eq!(<&'static str>::from(m), m.as_ref());
            // Parsing that token round-trips back to the variant.
            assert_eq!(m.as_ref().parse::<BackupMode>().ok(), Some(m));
            // The UI label is present.
            assert!(!m.label().is_empty());
        }
        // An unknown token is rejected.
        assert!("floppy".parse::<BackupMode>().is_err());
        // Sanity: both known variants are enumerated.
        assert_eq!(BackupMode::VARIANTS.len(), 2);
    }

    #[test]
    fn backup_schedule_parse_accepts_valid_six_field_cron() {
        assert!("0 0 0 * * *".parse::<BackupSchedule>().is_ok());
        assert!("0 30 2 * * MON-FRI".parse::<BackupSchedule>().is_ok());
    }

    #[test]
    fn backup_schedule_parse_rejects_invalid_expressions() {
        assert!("".parse::<BackupSchedule>().is_err());
        assert!("not a cron".parse::<BackupSchedule>().is_err());
        assert!("* * * * *".parse::<BackupSchedule>().is_err()); // five-field, not six
        assert!("99 0 0 * * *".parse::<BackupSchedule>().is_err());
    }

    #[test]
    fn backup_schedule_error_carries_the_underlying_reason() {
        // The error keeps croner's specific diagnostic behind our own label, rather
        // than collapsing every failure to a constant string.
        let msg = "not a cron"
            .parse::<BackupSchedule>()
            .unwrap_err()
            .to_string();
        assert!(msg.starts_with("invalid backup schedule: "), "{msg}");
        assert!(msg.len() > "invalid backup schedule: ".len(), "{msg}");
    }

    #[test]
    fn backup_schedule_default_is_valid() {
        let s = BackupSchedule::default();
        assert_eq!(s, "0 0 0 * * *"); // PartialEq<str> from the trailer
        assert!(s.to_string().parse::<BackupSchedule>().is_ok());
    }

    #[test]
    fn backup_schedule_parse_trims_whitespace() {
        let s = "  0 0 0 * * *  ".parse::<BackupSchedule>().unwrap();
        assert_eq!(s, "0 0 0 * * *");
    }

    #[test]
    fn backup_schedule_serializes_as_plain_string_and_validates_on_deserialize() {
        let s: BackupSchedule = "0 0 0 * * *".parse().unwrap();
        assert_eq!(serde_json::to_string(&s).unwrap(), "\"0 0 0 * * *\"");

        // Deserialize routes through the validating parse.
        assert_eq!(
            serde_json::from_str::<BackupSchedule>("\"0 0 0 * * *\"").unwrap(),
            "0 0 0 * * *".parse::<BackupSchedule>().unwrap()
        );

        // Invalid input is rejected at deserialize time (the tightening over the old
        // transparent derive).
        assert!(serde_json::from_str::<BackupSchedule>("\"not a cron\"").is_err());
    }

    #[test]
    fn backup_config_default_has_no_destination() {
        assert_eq!(BackupConfig::default().destination_path, None);
    }
}
