use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// Maximum profile-biography length, in Unicode scalar values.
pub const MAX_BIO_CHARS: usize = 1000;

/// A validated user biography: outer whitespace trimmed, non-empty, at most
/// [`MAX_BIO_CHARS`] scalars; inner whitespace/newlines and case preserved (a bio is
/// free-form prose, not a normalized identifier).
///
/// Constructed via [`FromStr`] — the single validating chokepoint — so interior code
/// works only with already-valid bios. Absence of a bio is modeled by `Option<Bio>` at
/// the boundary, so `FromStr` rejects the empty string: an empty wire value is rejected
/// and clearing goes through omission (`None`), never `Some("")`. The rest of the
/// ADR-0063 string-newtype trailer (`Display`, `AsRef`/`Borrow`/`Deref<str>`, owned
/// `String` conversions, `PartialEq<str>`/`<&str>`, the validating serde bridge, and the
/// ADR-0071 sqlx bridge) is generated by `#[derive(StrNewtype)]`. No `Hash` — a `Bio` is
/// never a map/set key.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct Bio(String);

/// Error returned when a string cannot be parsed as a [`Bio`].
#[derive(Debug, Error)]
#[error("biography must be non-empty and at most {MAX_BIO_CHARS} characters")]
pub struct InvalidBio;

impl FromStr for Bio {
    type Err = InvalidBio;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() || trimmed.chars().count() > MAX_BIO_CHARS {
            return Err(InvalidBio);
        }
        Ok(Bio(trimmed.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_and_trims_preserving_inner_and_case() {
        assert_eq!("  Hello there  ".parse::<Bio>().unwrap(), "Hello there");
        // Inner newlines are preserved (a bio is multi-line free-form prose).
        assert_eq!(
            "para 1\n\npara 2".parse::<Bio>().unwrap(),
            "para 1\n\npara 2"
        );
        // Unicode is preserved as-is (no normalization).
        assert_eq!("Автор".parse::<Bio>().unwrap(), "Автор");
    }

    #[test]
    fn rejects_empty_and_whitespace_only() {
        assert!("".parse::<Bio>().is_err());
        assert!("   \t\n".parse::<Bio>().is_err());
    }

    #[test]
    fn enforces_length_cap_on_scalars_post_trim() {
        let max: String = "a".repeat(MAX_BIO_CHARS);
        assert!(max.parse::<Bio>().is_ok());
        let over: String = "a".repeat(MAX_BIO_CHARS + 1);
        assert!(over.parse::<Bio>().is_err());
        // The cap counts scalars post-trim, so surrounding whitespace does not push an
        // otherwise-valid bio over the limit.
        let padded = format!("  {}  ", "a".repeat(MAX_BIO_CHARS));
        assert!(padded.parse::<Bio>().is_ok());
    }

    #[test]
    fn serde_serializes_plain_string_and_validates_on_deserialize() {
        let b: Bio = "About me".parse().unwrap();
        assert_eq!(serde_json::to_string(&b).unwrap(), "\"About me\"");
        assert_eq!(serde_json::from_str::<Bio>("\"About me\"").unwrap(), b);
        // Invalid input is rejected at deserialize time.
        assert!(serde_json::from_str::<Bio>("\"\"").is_err());
        let over = format!("\"{}\"", "a".repeat(MAX_BIO_CHARS + 1));
        assert!(serde_json::from_str::<Bio>(&over).is_err());
    }
}
