use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// Maximum display-name length, in Unicode scalar values. Generous — a display
/// name is a free-form human label, not an identifier — while still bounding the
/// stored value and the profile form.
pub const MAX_DISPLAY_NAME_CHARS: usize = 255;

/// A validated user display name: surrounding whitespace trimmed, non-empty, at
/// most [`MAX_DISPLAY_NAME_CHARS`] scalars. Casing is preserved (a display name
/// is a human label, not a normalized identifier like [`crate::username::Username`]).
///
/// Constructed via [`FromStr`] — the single validating/normalizing chokepoint;
/// invalid strings are rejected at the boundary so interior code works only with
/// already-valid names. The rest of the ADR-0063 string-newtype trailer
/// (`Display`, `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned `String`
/// conversions, `PartialEq<str>`/`PartialEq<&str>`, and the validating serde
/// bridge) is generated by `#[derive(StrNewtype)]`, so a `DisplayName` serializes
/// as a plain string and rejects invalid input on the wire — safe to use as a
/// (de)serialized DTO field. No `Hash` — a `DisplayName` is never a map/set key.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct DisplayName(String);

/// Error returned when a string cannot be parsed as a [`DisplayName`].
#[derive(Debug, Error)]
#[error("display name must be non-empty and at most {MAX_DISPLAY_NAME_CHARS} characters")]
pub struct InvalidDisplayName;

impl FromStr for DisplayName {
    type Err = InvalidDisplayName;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() || trimmed.chars().count() > MAX_DISPLAY_NAME_CHARS {
            return Err(InvalidDisplayName);
        }
        Ok(DisplayName(trimmed.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn display_name_parses_and_preserves_casing() {
        assert_eq!("Alice".parse::<DisplayName>().unwrap(), "Alice");
        assert_eq!(
            "Dr. Ada Lovelace".parse::<DisplayName>().unwrap(),
            "Dr. Ada Lovelace"
        );
        // Unicode is preserved as-is (no lowercasing/normalization).
        assert_eq!("Москва".parse::<DisplayName>().unwrap(), "Москва");
    }

    #[test]
    fn display_name_trims_surrounding_whitespace() {
        assert_eq!("  Bob  ".parse::<DisplayName>().unwrap(), "Bob");
        // Interior whitespace is kept.
        assert_eq!(" a b ".parse::<DisplayName>().unwrap(), "a b");
    }

    #[test]
    fn display_name_rejects_empty_and_whitespace_only() {
        assert!("".parse::<DisplayName>().is_err());
        assert!("   ".parse::<DisplayName>().is_err());
        assert!("\t\n".parse::<DisplayName>().is_err());
    }

    #[test]
    fn display_name_enforces_length_cap() {
        let max: String = "a".repeat(MAX_DISPLAY_NAME_CHARS);
        assert!(max.parse::<DisplayName>().is_ok());
        let over: String = "a".repeat(MAX_DISPLAY_NAME_CHARS + 1);
        assert!(over.parse::<DisplayName>().is_err());
        // The cap counts scalars post-trim, so surrounding whitespace does not
        // push an otherwise-valid name over the limit.
        let padded = format!("  {}  ", "a".repeat(MAX_DISPLAY_NAME_CHARS));
        assert!(padded.parse::<DisplayName>().is_ok());
    }

    #[test]
    fn display_name_display_returns_inner_string() {
        let d: DisplayName = "Ada".parse().unwrap();
        assert_eq!(d.to_string(), "Ada");
        assert_eq!(d, "Ada"); // generated PartialEq<&str>
    }

    #[test]
    fn display_name_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let d: DisplayName = "Ada".parse().unwrap();
        assert_eq!(serde_json::to_string(&d).unwrap(), "\"Ada\"");
        assert_eq!(
            serde_json::from_str::<DisplayName>("\"Ada\"").unwrap(),
            "Ada".parse::<DisplayName>().unwrap()
        );
        // Invalid input (empty) is rejected at deserialize time.
        assert!(serde_json::from_str::<DisplayName>("\"\"").is_err());
    }
}
