use std::str::FromStr;

use email_address::{EmailAddress, Options};
use macros::StrNewtype;
use thiserror::Error;

/// A validated, domain-normalized email address (RFC 5321/6531 addr-spec).
///
/// Constructed via [`FromStr`] — the single validating/normalizing chokepoint,
/// backed by the `email_address` crate. The DNS domain is lowercased (it is
/// case-insensitive per RFC) while the local-part is preserved (it is not); a
/// domain-literal (`[192.0.2.1]` / `[IPv6:…]`) is left verbatim. Display-name /
/// angle-bracket forms (`Foo <a@b>`) are rejected — an `Email` is a bare address,
/// not a mailbox. The rest of the ADR-0063 string-newtype trailer (`Display`,
/// `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde bridge) is generated by
/// `#[derive(StrNewtype)]`, so an `Email` serializes as a plain string and rejects
/// invalid input on the wire — safe to use as a (de)serialized DTO field.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct Email(String);

/// Error returned when a string cannot be parsed as an [`Email`].
///
/// Carries the underlying `email_address` reason (e.g. a missing `@`) so a caller
/// keeps the specific diagnostic the crate produces. The field is private, so the
/// dependency type does not leak into `common`'s public surface — only its
/// `Display` string escapes.
#[derive(Debug, Error)]
#[error("invalid email address: {0}")]
pub struct InvalidEmail(email_address::Error);

impl FromStr for Email {
    type Err = InvalidEmail;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        // Reject the display-name form that `email_address` accepts by default —
        // for a bare-address primitive it is a typo, not input to silently strip.
        let addr = EmailAddress::parse_with_options(s, Options::default().without_display_text())
            .map_err(InvalidEmail)?;
        // `email_address` is case-preserving. Canonicalize the DNS domain's ASCII
        // case only: `to_ascii_lowercase` is exactly what RFC-5321 case-insensitivity
        // covers, and — unlike `to_lowercase` — it can never change a non-ASCII
        // (EAI/IDN) domain's length. A length-changing lowercasing (e.g. `İ` → `i` +
        // U+0307 combining dot) would leave a label ending in a non-alphanumeric mark,
        // producing a canonical string that fails its own re-parse and would brick
        // reads (the serde bridge re-runs `FromStr`). A domain-literal is left verbatim.
        let domain = addr.domain();
        let canonical = if domain.starts_with('[') {
            format!("{}@{}", addr.local_part(), domain)
        } else {
            format!("{}@{}", addr.local_part(), domain.to_ascii_lowercase())
        };
        Ok(Email(canonical))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn email_parses_valid_addresses() {
        assert!("user@example.com".parse::<Email>().is_ok());
        assert!("first.last+tag@sub.example.co.uk".parse::<Email>().is_ok());
    }

    #[test]
    fn email_lowercases_domain_and_preserves_local_part() {
        let e: Email = "Foo.Bar@Example.COM".parse().unwrap();
        assert_eq!(e, "Foo.Bar@example.com");
    }

    #[test]
    fn email_rejects_display_name_form() {
        // Accepted by email_address by default, but not a bare address.
        assert!("Foo <a@b.com>".parse::<Email>().is_err());
    }

    #[test]
    fn email_preserves_domain_literal_verbatim() {
        let e: Email = "user@[127.0.0.1]".parse().unwrap();
        assert_eq!(e, "user@[127.0.0.1]");
    }

    #[test]
    fn email_rejects_malformed_input() {
        assert!("not-an-email".parse::<Email>().is_err());
        assert!("a@".parse::<Email>().is_err());
        assert!("@b.com".parse::<Email>().is_err());
        assert!("".parse::<Email>().is_err());
    }

    #[test]
    fn email_error_carries_the_underlying_reason() {
        // The error keeps the specific `email_address` diagnostic behind our own
        // label, rather than collapsing every failure to a constant string.
        let msg = "not-an-email".parse::<Email>().unwrap_err().to_string();
        assert!(msg.starts_with("invalid email address: "), "{msg}");
        assert!(msg.len() > "invalid email address: ".len(), "{msg}");
    }

    #[test]
    fn email_display_produces_the_canonical_string() {
        let e: Email = "user@example.com".parse().unwrap();
        assert_eq!(e.to_string(), "user@example.com");
    }

    #[test]
    fn email_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let e: Email = "user@example.com".parse().unwrap();
        assert_eq!(serde_json::to_string(&e).unwrap(), "\"user@example.com\"");

        // Deserialize routes through the validating parse (domain lowercasing too).
        assert_eq!(
            serde_json::from_str::<Email>("\"USER@EXAMPLE.COM\"").unwrap(),
            "USER@example.com".parse::<Email>().unwrap()
        );

        // Invalid input is rejected at deserialize time.
        assert!(serde_json::from_str::<Email>("\"not-an-email\"").is_err());
    }

    #[test]
    fn email_canonical_form_is_idempotent() {
        let e: Email = "Foo.Bar@Example.COM".parse().unwrap();
        let reparsed: Email = e.to_string().parse().unwrap();
        assert_eq!(e, reparsed);
    }

    #[test]
    fn email_non_ascii_domain_is_idempotent_and_uncorrupted() {
        // `İ` (U+0130) is accepted in a domain; its Unicode lowercase is
        // length-changing (`i` + U+0307), which would leave a label ending in a
        // combining mark that fails re-parse. ASCII-only casing keeps it verbatim.
        let e: Email = "user@İ.com".parse().unwrap();
        assert_eq!(e, "user@İ.com");
        let reparsed: Email = e.to_string().parse().unwrap();
        assert_eq!(e, reparsed);
    }
}
