//! HTTP `ETag` values: the RFC 7232 strong quoted-tag invariant, owned by a
//! validating newtype.
//!
//! [`FromStr`] is the one validating chokepoint, backing the derived serde/sqlx
//! bridges so a stored `feed_cache.etag` re-validates on read-back. Host-side
//! construction from content bytes or hashes lives in [`host::etag`].

use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// `String` is private, so the only way in is the validating [`FromStr`] bridge
/// used for stored and wire values; arbitrary input cannot masquerade as an
/// `ETag`.
/// (`Display`, `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned-`String`
/// conversions, `PartialEq<str>`, and the validating serde + sqlx bridges) is generated by
/// `#[derive(StrNewtype)]`, so `ETag` serializes as a plain string, rejects invalid input
/// on the wire, and decodes as a first-class TEXT column that re-validates the quoted
/// invariant on read-back.
///
/// The wrapped `String` is private, so an arbitrary `String` cannot masquerade as an
/// `ETag` (mirroring the `ContentHash`/`ContentType` doctests).
///
/// The positive companion shows the identical fixture compiles — the path resolves
/// and the validating door accepts a double-quoted value — so each `compile_fail`
/// below fails for the private field, not for a moved path. (Fixture lines are
/// hidden with `#`.)
///
/// ```
/// use common::etag::ETag;
/// use std::str::FromStr;
/// let e = ETag::from_str("\"abc\"").unwrap();
/// let _read: &str = e.as_ref();
/// ```
///
/// No public constructor:
/// ```compile_fail
/// # use common::etag::ETag;
/// # use std::str::FromStr;
/// let _ = ETag("\"abc\"".to_string()); // private field
/// ```
///
/// A `String` does not convert to an `ETag` (asserted on `.into()`, so the proof
/// still fails if a `From<String>` impl is added — a function argument would not,
/// since an argument is never coerced through `From`):
/// ```compile_fail
/// # use common::etag::ETag;
/// # use std::str::FromStr;
/// let _e: ETag = "\"abc\"".to_string().into();
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct ETag(String);

/// Error returned when a string is not a valid strong HTTP `ETag`.
#[derive(Debug, Error)]
#[error("ETag must be a double-quoted strong opaque-tag, e.g. \"sha256-<hex>\"")]
pub struct InvalidETag;

impl FromStr for ETag {
    type Err = InvalidETag;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if is_valid_etag(s) {
            Ok(ETag(s.to_owned()))
        } else {
            Err(InvalidETag)
        }
    }
}

/// Whether `s` is a strong HTTP `ETag`: RFC 7232 `opaque-tag = DQUOTE *etagc DQUOTE`, where
/// `etagc` is `%x21` / `%x23-7E` / `%x80-FF` (every byte except the `"` delimiter, controls,
/// and space). A leading `W/` (weak validator) fails the opening-`"` check and is rejected —
/// nothing here produces or consumes weak `ETag`s. The single source of truth for [`ETag`]'s
/// invariant.
fn is_valid_etag(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() >= 2
        && b[0] == b'"'
        && b[b.len() - 1] == b'"'
        && b[1..b.len() - 1]
            .iter()
            .all(|&c| c == 0x21 || (0x23..=0x7e).contains(&c) || c >= 0x80)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fromstr_accepts_a_canonical_quoted_tag() {
        assert_eq!("\"sha256-abc\"".parse::<ETag>().unwrap(), "\"sha256-abc\"");
        // A non-sha256 body is still a valid HTTP ETag (the sha256- scheme is a producer
        // policy, not a parse requirement).
        assert_eq!("\"known-etag\"".parse::<ETag>().unwrap(), "\"known-etag\"");
    }

    #[test]
    fn fromstr_rejects_malformed_and_weak_forms() {
        for bad in [
            "",          // empty string
            "unquoted",  // no quotes
            "\"",        // single quote
            "\"missing", // no closing quote
            "abc\"",     // no opening quote
            "\"a\"b\"",  // interior double-quote (not etagc)
            "\"a b\"",   // interior space (not etagc)
            "\"a\tb\"",  // interior control byte
            "W/\"abc\"", // weak validator
        ] {
            let err = bad.parse::<ETag>().unwrap_err();
            assert!(err.to_string().contains("quoted"), "msg for {bad:?}: {err}");
        }
    }

    #[test]
    fn serde_serializes_as_the_raw_quoted_string_and_validates_on_deserialize() {
        let e: ETag = format!("\"sha256-{}\"", "0".repeat(64)).parse().unwrap();
        let json = serde_json::to_string(&e).unwrap();
        assert_eq!(json, format!("\"\\\"sha256-{}\\\"\"", "0".repeat(64)));
        assert_eq!(serde_json::from_str::<ETag>(&json).unwrap(), e);
        assert!(serde_json::from_str::<ETag>("\"unquoted\"").is_err());
    }
}
