//! HTTP `ETag` values: the RFC 7232 strong quoted-tag invariant, owned by a newtype.
//!
//! Every `ETag` in jaunder is SHA-256-based, so `ETag` owns the whole
//! `digest → 64-lowercase-hex → "sha256-" prefix → surrounding quotes` pipeline: producers
//! hand it content bytes, a precomputed digest, or a [`ContentHash`] and never spell hex or
//! quotes. [`FromStr`] (the one validating chokepoint, backing the derived serde/sqlx
//! bridges) validates the *general* strong quoted format, so a stored `feed_cache.etag`
//! re-validates on read-back. The rest of the ADR-0063 trailer is `#[derive(StrNewtype)]`.
//!
//! The three producer doors ([`sha256_of`](ETag::sha256_of),
//! [`from_sha256`](ETag::from_sha256), [`from_content_hash`](ETag::from_content_hash))
//! compose down to one place — [`from_content_hash`](ETag::from_content_hash) — that writes
//! the `sha256-` prefix and the quotes, so the format lives in exactly one function.

use std::str::FromStr;

use macros::StrNewtype;
use sha2::{Digest, Sha256};
use thiserror::Error;

use crate::media::ContentHash;

/// A strong HTTP `ETag` — a double-quoted opaque validator (RFC 7232). The wrapped
/// `String` is private, so the only ways in are the validating [`FromStr`] (for stored /
/// wire values) and the trusted producer doors below (for freshly minted values); an
/// arbitrary `String` cannot masquerade as an `ETag`. The ADR-0063 string-newtype trailer
/// (`Display`, `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned-`String`
/// conversions, `PartialEq<str>`, and the validating serde + sqlx bridges) is generated by
/// `#[derive(StrNewtype)]`, so `ETag` serializes as a plain string, rejects invalid input
/// on the wire, and decodes as a first-class TEXT column that re-validates the quoted
/// invariant on read-back.
///
/// The wrapped `String` is private, so an arbitrary `String` cannot masquerade as an
/// `ETag` (mirroring the `ContentHash`/`ContentType` doctests):
/// The positive companion shows the identical fixture compiles — the path resolves
/// and the validating door accepts a double-quoted value — so each `compile_fail`
/// below fails for the private field, not for a moved path. (Fixture lines are
/// hidden with `#`.)
///
/// ```
/// use common::etag::ETag;
/// use std::str::FromStr;
/// let e = ETag::from_str("\"abc\"").unwrap();
/// let _read: &str = e.as_ref();
/// ```
///
/// No public constructor:
/// ```compile_fail
/// # use common::etag::ETag;
/// # use std::str::FromStr;
/// let _ = ETag("\"abc\"".to_string()); // private field
/// ```
///
/// A `String` is not an `ETag`:
/// ```compile_fail
/// # use common::etag::ETag;
/// # use std::str::FromStr;
/// fn takes_etag(_: ETag) {}
/// takes_etag("\"abc\"".to_string());
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct ETag(String);

/// Error returned when a string is not a valid strong HTTP `ETag`.
#[derive(Debug, Error)]
#[error("ETag must be a double-quoted strong opaque-tag, e.g. \"sha256-<hex>\"")]
pub struct InvalidETag;

impl FromStr for ETag {
    type Err = InvalidETag;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if is_valid_etag(s) {
            Ok(ETag(s.to_owned()))
        } else {
            Err(InvalidETag)
        }
    }
}

/// Whether `s` is a strong HTTP `ETag`: RFC 7232 `opaque-tag = DQUOTE *etagc DQUOTE`, where
/// `etagc` is `%x21` / `%x23-7E` / `%x80-FF` (every byte except the `"` delimiter, controls,
/// and space). A leading `W/` (weak validator) fails the opening-`"` check and is rejected —
/// nothing here produces or consumes weak `ETag`s. The single source of truth for [`ETag`]'s
/// invariant.
fn is_valid_etag(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() >= 2
        && b[0] == b'"'
        && b[b.len() - 1] == b'"'
        && b[1..b.len() - 1]
            .iter()
            .all(|&c| c == 0x21 || (0x23..=0x7e).contains(&c) || c >= 0x80)
}

impl ETag {
    /// The `ETag` of `bytes`: `"sha256-<hex>"` over `Sha256::digest(bytes)`. The door for a
    /// producer holding the raw content it wants to fingerprint (a rendered page, a
    /// serialized post projection).
    #[must_use]
    pub fn sha256_of(bytes: impl AsRef<[u8]>) -> ETag {
        Self::from_sha256(Sha256::digest(bytes.as_ref()).into())
    }

    /// The `ETag` of a precomputed 32-byte SHA-256 digest. The door for a producer that
    /// already has a digest — a compile-time embed hash, or an incremental [`Sha256`] it
    /// finalizes itself. Reuses [`ContentHash::from_digest`] for the lowercase-hex encoding
    /// (structurally valid: 32 bytes always encode to 64 lowercase hex).
    #[must_use]
    pub fn from_sha256(digest: [u8; 32]) -> ETag {
        Self::from_content_hash(&ContentHash::from_digest(digest))
    }

    /// The `ETag` of an already-validated content hash: `"sha256-<hex>"`. The door for a
    /// producer that holds only the hex (a URL path segment whose file is streamed, so
    /// re-hashing is not an option). This is the one place the `sha256-` prefix and the
    /// surrounding quotes are written.
    #[must_use]
    pub fn from_content_hash(hash: &ContentHash) -> ETag {
        let hex = hash.as_ref();
        let mut s = String::with_capacity(hex.len() + "\"sha256-\"".len());
        s.push('"');
        s.push_str("sha256-");
        s.push_str(hex);
        s.push('"');
        ETag(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::media::ContentHash;

    // A realistic lowercase sha256 hex digest (of the empty input) and its ETag form.
    const HASH64: &str = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

    #[test]
    fn from_sha256_produces_quoted_prefixed_lowercase_hex() {
        // 32 zero bytes → 64 '0' hex, prefixed and quoted.
        assert_eq!(
            ETag::from_sha256([0u8; 32]),
            format!("\"sha256-{}\"", "0".repeat(64)).as_str()
        );
    }

    #[test]
    fn sha256_of_hashes_then_formats_and_equals_from_sha256() {
        // sha256_of(b"") == from_sha256(digest of "") == "sha256-<HASH64>"
        assert_eq!(
            ETag::sha256_of(b""),
            format!("\"sha256-{HASH64}\"").as_str()
        );
        assert_eq!(
            ETag::sha256_of(b""),
            ETag::from_sha256(Sha256::digest(b"").into())
        );
    }

    #[test]
    fn from_content_hash_prefixes_and_quotes_the_hex() {
        let h: ContentHash = HASH64.parse().unwrap();
        assert_eq!(
            ETag::from_content_hash(&h),
            format!("\"sha256-{HASH64}\"").as_str()
        );
        // The three doors agree for the same digest.
        assert_eq!(ETag::from_content_hash(&h), ETag::sha256_of(b""));
    }

    #[test]
    fn every_door_output_reparses_via_fromstr() {
        let h: ContentHash = HASH64.parse().unwrap();
        for e in [
            ETag::from_sha256([0xab; 32]),
            ETag::sha256_of(b"hello"),
            ETag::from_content_hash(&h),
        ] {
            assert!(
                e.as_ref().parse::<ETag>().is_ok(),
                "door output must re-parse: {e}"
            );
        }
    }

    #[test]
    fn fromstr_accepts_a_canonical_quoted_tag() {
        assert_eq!("\"sha256-abc\"".parse::<ETag>().unwrap(), "\"sha256-abc\"");
        // A non-sha256 body is still a valid HTTP ETag (the sha256- scheme is a producer
        // policy, not a parse requirement).
        assert_eq!("\"known-etag\"".parse::<ETag>().unwrap(), "\"known-etag\"");
    }

    #[test]
    fn fromstr_rejects_malformed_and_weak_forms() {
        for bad in [
            "",          // empty string
            "unquoted",  // no quotes
            "\"",        // single quote
            "\"missing", // no closing quote
            "abc\"",     // no opening quote
            "\"a\"b\"",  // interior double-quote (not etagc)
            "\"a b\"",   // interior space (not etagc)
            "\"a\tb\"",  // interior control byte
            "W/\"abc\"", // weak validator
        ] {
            let err = bad.parse::<ETag>().unwrap_err();
            assert!(err.to_string().contains("quoted"), "msg for {bad:?}: {err}");
        }
    }

    #[test]
    fn serde_serializes_as_the_raw_quoted_string_and_validates_on_deserialize() {
        let e = ETag::from_sha256([0u8; 32]);
        let json = serde_json::to_string(&e).unwrap();
        assert_eq!(json, format!("\"\\\"sha256-{}\\\"\"", "0".repeat(64)));
        assert_eq!(serde_json::from_str::<ETag>(&json).unwrap(), e);
        assert!(serde_json::from_str::<ETag>("\"unquoted\"").is_err());
    }
}
