use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A retry key that identifies one post-creation attempt for a user.
///
/// [`FromStr`] is the single validation and canonicalization chokepoint: outer
/// whitespace is removed, and an empty result is rejected. Any other text is
/// preserved, because key format is chosen by the client rather than this domain
/// type. The ADR-0063 string-newtype trailer (`Display`, `AsRef`/`Borrow`/
/// `Deref<str>`, owned `String` conversions, `PartialEq<str>`/`<&str>`, ordering,
/// and validating serde and sqlx bridges) is generated by `#[derive(StrNewtype)]`.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct IdempotencyKey(String);

/// Error returned when a string cannot be parsed as an [`IdempotencyKey`].
#[derive(Debug, Error)]
#[error("idempotency key must be non-empty")]
pub struct InvalidIdempotencyKey;

impl FromStr for IdempotencyKey {
    type Err = InvalidIdempotencyKey;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() {
            return Err(InvalidIdempotencyKey);
        }
        Ok(Self(trimmed.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use std::borrow::Borrow;

    use super::*;

    #[test]
    fn parses_trimmed_arbitrary_text_without_format_restrictions() {
        let key: IdempotencyKey = " \t retry:🦀/v1  \n".parse().unwrap();

        assert_eq!(key, "retry:🦀/v1");
        let canonical: &str = key.as_ref();
        assert_eq!(canonical, "retry:🦀/v1");
    }

    #[test]
    fn rejects_empty_and_whitespace_only_keys() {
        for input in ["", "   ", "\t\n", "\u{2003}"] {
            assert!(input.parse::<IdempotencyKey>().is_err(), "{input:?}");
        }
        assert_eq!(
            InvalidIdempotencyKey.to_string(),
            "idempotency key must be non-empty"
        );
    }

    #[test]
    fn serde_round_trips_canonical_key_and_rejects_blank_input() {
        let key: IdempotencyKey = "  retry key  ".parse().unwrap();

        assert_eq!(serde_json::to_string(&key).unwrap(), "\"retry key\"");
        assert_eq!(
            serde_json::from_str::<IdempotencyKey>("\"  retry key  \"").unwrap(),
            key
        );
        assert!(serde_json::from_str::<IdempotencyKey>("\"\"").is_err());
        assert!(serde_json::from_str::<IdempotencyKey>("\"  \\t  \"").is_err());
    }

    #[test]
    fn standard_trailer_supports_owned_and_borrowed_access() {
        let key = IdempotencyKey::try_from("  retry-key  ".to_owned()).unwrap();

        assert_eq!(key.as_ref(), "retry-key");
        let via_borrow: &str = key.borrow();
        assert_eq!(via_borrow, "retry-key");
        let borrowed: &str = &key;
        assert_eq!(borrowed, "retry-key");
        assert_eq!(String::from(key), "retry-key");
    }

    #[test]
    fn standard_trailer_compares_and_orders_by_canonical_string() {
        let earlier: IdempotencyKey = "  alpha ".parse().unwrap();
        let later: IdempotencyKey = "beta".parse().unwrap();

        assert_eq!(earlier, "alpha");
        assert!(earlier < later);
    }
}
