//! Numeric domain-id newtypes (ADR-0063 numeric trailer).
//!
//! Each is a bare `i64` row id wrapped so it cannot be transposed with another id
//! (a `user_id` passed where a `post_id` is expected) at a call site. The whole
//! ADR-0063 numeric trailer — `From<i64>`, `From<Self> for i64`, `Display`, and a
//! transparent-i64 serde bridge (the wire form stays a bare integer) — is generated by
//! `#[derive(IdNewtype)]`; `Copy` and the std derives stay in each type's derive list.
//! An id has no value invariant, so there is no hand-written `FromStr` and deserialize is
//! an infallible wrap. This module is the shared home for every id newtype (ADR-0063 §3).

use macros::IdNewtype;

/// A user's row id.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct UserId(i64);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_id_round_trips_through_i64() {
        let id = UserId::from(42);
        assert_eq!(i64::from(id), 42);
        // Copy + Eq: a copy compares equal without moving the original.
        let copy = id;
        assert_eq!(copy, id);
    }

    #[test]
    fn user_id_displays_as_the_bare_integer() {
        assert_eq!(UserId::from(7).to_string(), "7");
    }

    #[test]
    fn user_id_serde_is_a_transparent_bare_integer() {
        // Wire form is a plain integer, so a DTO field can adopt the type with no
        // serialized-shape change; deserialize is an infallible wrap.
        assert_eq!(serde_json::to_string(&UserId::from(42)).unwrap(), "42");
        assert_eq!(
            serde_json::from_str::<UserId>("42").unwrap(),
            UserId::from(42)
        );
    }
}
