//! Numeric domain-id newtypes (ADR-0063 numeric trailer).
//!
//! Each is a bare `i64` row id wrapped so it cannot be transposed with another id
//! (a `user_id` passed where a `post_id` is expected) at a call site. The whole
//! ADR-0063 numeric trailer — `From<i64>`, `From<Self> for i64`, `Display`, and a
//! transparent-i64 serde bridge (the wire form stays a bare integer) — is generated by
//! `#[derive(IdNewtype)]`; `Copy` and the std derives stay in each type's derive list.
//! An id has no value invariant, so there is no hand-written `FromStr` and deserialize is
//! an infallible wrap. This module is the shared home for every id newtype (ADR-0063 §3).

use macros::IdNewtype;

/// A user's row id.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct UserId(i64);

/// An audience's row id.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct AudienceId(i64);

/// A post's row id. Newtyped so it can't be transposed with another `i64` id
/// (user, tag, audience, …) at a call site.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct PostId(i64);

/// A subscription's row id.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct SubscriptionId(i64);

/// A channel's row id (the `local` channel and any future channels).
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct ChannelId(i64);

/// A tag's row id (distinct from the string `Tag` slug / `TagLabel` display).
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct TagId(i64);

/// A post revision's row id.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct RevisionId(i64);

/// A feed-regeneration queue row id.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, IdNewtype)]
pub struct FeedEventId(i64);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_id_round_trips_through_i64() {
        let id = UserId::from(42);
        assert_eq!(i64::from(id), 42);
        // Copy + Eq: a copy compares equal without moving the original.
        let copy = id;
        assert_eq!(copy, id);
    }

    #[test]
    fn user_id_displays_as_the_bare_integer() {
        assert_eq!(UserId::from(7).to_string(), "7");
    }

    #[test]
    fn user_id_parses_from_a_string() {
        // For sites that carry an id as a string (e.g. a Leptos route param).
        assert_eq!("42".parse::<UserId>().unwrap(), UserId::from(42));
        assert!("not-a-number".parse::<UserId>().is_err());
    }

    #[test]
    fn user_id_serde_is_a_transparent_bare_integer() {
        // Wire form is a plain integer, so a DTO field can adopt the type with no
        // serialized-shape change; deserialize is an infallible wrap.
        assert_eq!(serde_json::to_string(&UserId::from(42)).unwrap(), "42");
        assert_eq!(
            serde_json::from_str::<UserId>("42").unwrap(),
            UserId::from(42)
        );
    }

    #[test]
    fn audience_id_exercises_the_generated_surface() {
        // Covers this type's generated From/Into/Display/FromStr/serde impls.
        let id = AudienceId::from(9);
        assert_eq!(i64::from(id), 9);
        assert_eq!(id.to_string(), "9");
        assert_eq!("9".parse::<AudienceId>().unwrap(), id);
        assert!("nope".parse::<AudienceId>().is_err());
        assert_eq!(serde_json::to_string(&id).unwrap(), "9");
        assert_eq!(serde_json::from_str::<AudienceId>("9").unwrap(), id);
    }

    #[test]
    fn post_id_round_trips_through_i64() {
        let id = PostId::from(42);
        assert_eq!(i64::from(id), 42);
        // Copy + Eq: a copy compares equal without moving the original.
        let copy = id;
        assert_eq!(copy, id);
    }

    #[test]
    fn post_id_displays_as_the_bare_integer() {
        assert_eq!(PostId::from(7).to_string(), "7");
    }

    #[test]
    fn post_id_parses_from_a_string() {
        // For sites that carry an id as a string (e.g. a Leptos route param).
        assert_eq!("42".parse::<PostId>().unwrap(), PostId::from(42));
        assert!("not-a-number".parse::<PostId>().is_err());
    }

    #[test]
    fn post_id_serde_is_a_transparent_bare_integer() {
        // Wire form is a plain integer, so a DTO field can adopt the type with no
        // serialized-shape change; deserialize is an infallible wrap.
        assert_eq!(serde_json::to_string(&PostId::from(42)).unwrap(), "42");
        assert_eq!(
            serde_json::from_str::<PostId>("42").unwrap(),
            PostId::from(42)
        );
    }

    #[test]
    fn subscription_id_exercises_the_generated_surface() {
        // Covers this type's generated From/Into/Display/FromStr/serde impls.
        let id = SubscriptionId::from(9);
        assert_eq!(i64::from(id), 9);
        assert_eq!(id.to_string(), "9");
        assert_eq!("9".parse::<SubscriptionId>().unwrap(), id);
        assert!("nope".parse::<SubscriptionId>().is_err());
        assert_eq!(serde_json::to_string(&id).unwrap(), "9");
        assert_eq!(serde_json::from_str::<SubscriptionId>("9").unwrap(), id);
    }

    #[test]
    fn channel_id_exercises_the_generated_surface() {
        // Covers this type's generated From/Into/Display/FromStr/serde impls.
        let id = ChannelId::from(9);
        assert_eq!(i64::from(id), 9);
        assert_eq!(id.to_string(), "9");
        assert_eq!("9".parse::<ChannelId>().unwrap(), id);
        assert!("nope".parse::<ChannelId>().is_err());
        assert_eq!(serde_json::to_string(&id).unwrap(), "9");
        assert_eq!(serde_json::from_str::<ChannelId>("9").unwrap(), id);
    }

    #[test]
    fn tag_id_exercises_the_generated_surface() {
        // Covers this type's generated From/Into/Display/FromStr/serde impls.
        let id = TagId::from(9);
        assert_eq!(i64::from(id), 9);
        assert_eq!(id.to_string(), "9");
        assert_eq!("9".parse::<TagId>().unwrap(), id);
        assert!("nope".parse::<TagId>().is_err());
        assert_eq!(serde_json::to_string(&id).unwrap(), "9");
        assert_eq!(serde_json::from_str::<TagId>("9").unwrap(), id);
    }

    #[test]
    fn revision_id_exercises_the_generated_surface() {
        // Covers this type's generated From/Into/Display/FromStr/serde impls.
        let id = RevisionId::from(9);
        assert_eq!(i64::from(id), 9);
        assert_eq!(id.to_string(), "9");
        assert_eq!("9".parse::<RevisionId>().unwrap(), id);
        assert!("nope".parse::<RevisionId>().is_err());
        assert_eq!(serde_json::to_string(&id).unwrap(), "9");
        assert_eq!(serde_json::from_str::<RevisionId>("9").unwrap(), id);
    }

    #[test]
    fn feed_event_id_exercises_the_generated_surface() {
        // Covers this type's generated From/Into/Display/FromStr/serde impls.
        let id = FeedEventId::from(9);
        assert_eq!(i64::from(id), 9);
        assert_eq!(id.to_string(), "9");
        assert_eq!("9".parse::<FeedEventId>().unwrap(), id);
        assert!("nope".parse::<FeedEventId>().is_err());
        assert_eq!(serde_json::to_string(&id).unwrap(), "9");
        assert_eq!(serde_json::from_str::<FeedEventId>("9").unwrap(), id);
    }
}
