//! Pure helpers for jaunder's content-addressed media storage, shared by the
//! web media upload/serve handlers and the `AtomPub` media collection (both in
//! the `server` crate). Nothing here touches the filesystem or database — these
//! are deterministic string/path computations and small classification tables,
//! so they are cheap to unit-test and safe to call from any layer.
//!
//! # Storage layout
//!
//! A stored object is addressed by its `SHA-256` content hash and laid out as
//! `<source>/<p1>/<p2>/<sha256>/<filename>` (see [`media_path`]), served under
//! `/media/` (see [`media_url`]). `p1`/`p2` are the first two byte-pairs of the
//! hex digest — a two-level fan-out that keeps any single directory small.
//! `source` distinguishes provenance (e.g. `upload` vs a remote cache).
//!
//! # Untrusted input
//!
//! Filenames and hashes round-trip through URLs, so they are attacker-
//! influenced. [`sanitize_filename`] reduces a name to a single safe path
//! component; [`Filename`] is the newtype that holds such a value — its
//! validating [`FromStr`] admits only an already-safe leaf, and its
//! [`sanitized`][Filename::sanitized] door normalizes an arbitrary name into one —
//! so an un-sanitized filename is unrepresentable past the boundary. An externally
//! supplied hash must be parsed into a [`ContentHash`]
//! (via [`is_valid_content_hash`], its `FromStr`'s validating engine) before it
//! reaches [`media_path`]: the type is what guarantees the `sha256[..2]`/`[2..4]`
//! slicing — unguarded, and panicking on a short or non-`UTF-8`-boundary value —
//! only ever sees a canonical 64-hex string.
//!
//! # Content type
//!
//! [`detect_content_type`] maps a filename extension to a `MIME` type (falling
//! back to `application/octet-stream`), and [`should_inline`] decides whether a
//! type is served inline or as an attachment (the `Content-Disposition`).

use std::path::Path;
use std::str::FromStr;

use macros::{NumNewtype, StrEnum, StrNewtype};
use thiserror::Error;

/// A validated media content hash: exactly 64 lowercase hex characters
/// (`[0-9a-f]{64}`), the canonical `format!("{digest:x}")` form of a SHA-256
/// digest. Introducing the type means an arbitrary string can no longer be passed
/// where a media content hash is expected (a transposition hazard, ADR-0063 §1).
///
/// [`FromStr`] is the single validating chokepoint — it delegates to
/// [`is_valid_content_hash`], the one source of truth for "canonical content
/// hash". The rest of the ADR-0063 string-newtype trailer (`Display`, `AsRef<str>`,
/// `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde bridge) is generated by
/// `#[derive(StrNewtype)]`, so a `ContentHash` serializes as a plain string and
/// rejects invalid input on the wire — safe to use as a (de)serialized DTO field.
///
/// The wrapped `String` is private, so the only way in is a validating parse or
/// the trusted [`from_digest`][ContentHash::from_digest] door — an arbitrary
/// `String` cannot masquerade as a content hash:
/// ```compile_fail
/// let _ = common::media::ContentHash("abc".to_string()); // private field
/// ```
/// ```compile_fail
/// fn takes_hash(_: common::media::ContentHash) {}
/// takes_hash("abc".to_string()); // a String is not a ContentHash
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct ContentHash(String);

/// Error returned when a string cannot be parsed as a [`ContentHash`].
#[derive(Debug, Error)]
#[error("content hash must be 64 lowercase hex characters ([0-9a-f]{{64}})")]
pub struct InvalidContentHash;

impl FromStr for ContentHash {
    type Err = InvalidContentHash;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if is_valid_content_hash(s) {
            Ok(ContentHash(s.to_owned()))
        } else {
            Err(InvalidContentHash)
        }
    }
}

impl ContentHash {
    /// Builds a [`ContentHash`] from the raw 32 bytes of a SHA-256 digest,
    /// lowercase-hex-encoding them here so the caller never spells the format.
    /// This is the trusted producer door — validity is **structural**: 32 bytes
    /// always encode to exactly 64 lowercase hex characters, so an invalid hash
    /// cannot be constructed (unlike a byte-slice or string door). A digest from
    /// `sha2` reaches it directly with `.into()`:
    /// `ContentHash::from_digest(Sha256::digest(bytes).into())`.
    ///
    /// A hash arriving as a **string** — a URL path segment, a `#[server]` wire
    /// arg, or a value read back from the `sha256` column — is not a digest here;
    /// it goes through [`FromStr`]/`TryFrom`, which validate the canonical form.
    #[must_use]
    pub fn from_digest(digest: [u8; 32]) -> Self {
        use std::fmt::Write as _;
        let mut hex = String::with_capacity(64);
        for byte in digest {
            // Infallible: writing to a String never errors.
            let _ = write!(hex, "{byte:02x}");
        }
        ContentHash(hex)
    }
}

/// A validated media filename: a single safe path leaf — the canonical form
/// produced by [`sanitize_filename`] (no path components, no `.`/`..`, no `\0`,
/// non-empty). The newtype makes an un-sanitized filename unrepresentable where a
/// filename is expected: the value feeds a filesystem path and a
/// `Content-Disposition` header, so an un-sanitized one is a path-traversal /
/// header-injection hazard (ADR-0063 §1: invariant + trust/safety boundary).
///
/// Two construction doors, mirroring [`ContentHash`]'s `FromStr` + `from_digest`:
/// - [`FromStr`] **validates** — it accepts a string iff it is already a canonical
///   leaf (`sanitize_filename(s) == s`, non-empty), *rejecting* a non-canonical
///   name rather than normalizing it. This is the door for untrusted URL / wire /
///   DB values that must match a stored filename exactly; `#[derive(StrNewtype)]`
///   routes `Deserialize` through it, so a non-canonical filename is rejected on
///   the wire.
/// - [`sanitized`][Filename::sanitized] **normalizes** — the upload-intake door,
///   where a client's arbitrary name is meant to be reduced to a safe leaf.
///
/// The rest of the ADR-0063 string-newtype trailer (`Display`, `AsRef<str>`,
/// `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde bridge) is generated by
/// `#[derive(StrNewtype)]`. The wrapped `String` is private, so the only ways in
/// are the two validating doors — an arbitrary `String` cannot masquerade as a
/// filename:
/// ```compile_fail
/// let _ = common::media::Filename("a".to_string()); // private field
/// ```
/// ```compile_fail
/// fn takes_filename(_: common::media::Filename) {}
/// takes_filename("a".to_string()); // a String is not a Filename
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct Filename(String);

/// Error returned when a string is not a canonical media filename leaf.
#[derive(Debug, Error)]
#[error(
    "filename must be a non-empty safe path leaf (no path components, `.`/`..`, or null bytes)"
)]
pub struct InvalidFilename;

impl FromStr for Filename {
    type Err = InvalidFilename;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        // Door A: accept only an already-canonical, non-empty leaf. `sanitize_filename`
        // is the oracle. The `is_empty` guard is explicit because `sanitize_filename("")`
        // is `""`, so `sanitize_filename(s) == s` alone would accept the empty string —
        // and a filename is never empty.
        if !s.is_empty() && sanitize_filename(s) == s {
            Ok(Filename(s.to_owned()))
        } else {
            Err(InvalidFilename)
        }
    }
}

impl Filename {
    /// Builds a [`Filename`] by **normalizing** `raw` to a safe leaf via
    /// [`sanitize_filename`], rejecting an empty result. This is the trusted
    /// upload-intake door (the `AtomPub` `Slug` header, a multipart `file_name`),
    /// where a client's arbitrary name is meant to be reduced to a single leaf —
    /// as distinct from [`FromStr`], which rejects a non-canonical name outright.
    ///
    /// # Errors
    ///
    /// Returns [`InvalidFilename`] when `raw` sanitizes to the empty string (i.e.
    /// `""`, `.`, or `..`).
    pub fn sanitized(raw: &str) -> Result<Self, InvalidFilename> {
        let s = sanitize_filename(raw);
        if s.is_empty() {
            Err(InvalidFilename)
        } else {
            Ok(Filename(s))
        }
    }
}

/// Strip path components, replace null bytes, reject `.`, `..`, and empty results.
#[must_use]
pub fn sanitize_filename(name: &str) -> String {
    // Normalize Windows backslashes to forward slashes before extracting file name
    let normalized = name.replace('\\', "/");
    let path = Path::new(&normalized);
    let Some(file_name) = path.file_name() else {
        return String::new();
    };
    let s = file_name.to_string_lossy();
    s.replace('\0', "_")
}

/// Returns true if `hash` is a canonical content hash: exactly 64 lowercase
/// hex characters (`[0-9a-f]{64}`), the form produced by `format!("{digest:x}")`
/// for a SHA-256 digest.
///
/// Callers that accept a hash from an untrusted source (e.g. a URL path
/// segment) must check this before slicing or joining it into a path:
/// [`media_path`] slices `sha256[..2]`/`[2..4]` unguarded, which panics on a
/// shorter string or one whose byte index 2 is not a UTF-8 char boundary.
#[must_use]
pub fn is_valid_content_hash(hash: &str) -> bool {
    hash.len() == 64
        && hash
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

/// Source of a media record — the provenance segment of the storage layout
/// (`upload` vs a remote `cached` file). Rides the [`StrEnum`] trailer (#562):
/// `as_str`/`Display`/`FromStr`/`TryFrom` + the generated `InvalidMediaSource`
/// error, with the `serde` bridge for the `#[server]` media DTO/wire args (#577).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, StrEnum)]
#[str_enum(serde, error = "media source must be \"upload\" or \"cached\"")]
pub enum MediaSource {
    /// File uploaded directly by a local user.
    Upload,
    /// Remote file cached locally by the system.
    Cached,
}

/// Returns `"<source>/<p1>/<p2>/<full-sha256>/<filename>"`, the content-
/// addressed layout described in the module docs.
///
/// Takes a [`ContentHash`] rather than a bare `&str`, so the `sha256[..2]`/`[2..4]`
/// slicing below can never see a short or non-`UTF-8`-boundary value — the type is
/// the guard (its `FromStr`/`from_digest` are the only ways to build one). `p1`/`p2`
/// index through `Deref<Target = str>`.
#[must_use]
pub fn media_path(source: &str, sha256: &ContentHash, filename: &str) -> String {
    let p1 = &sha256[..2];
    let p2 = &sha256[2..4];
    format!("{source}/{p1}/{p2}/{sha256}/{filename}")
}

/// Returns `"/media/<source>/<2-hex-p1>/<2-hex-p2>/<full-sha256>/<filename>"`.
#[must_use]
pub fn media_url(source: &str, sha256: &ContentHash, filename: &str) -> String {
    format!("/media/{}", media_path(source, sha256, filename))
}

/// A media `Content-Type` header value — a `type/subtype` media type with optional
/// `;`-separated parameters (e.g. `image/png`, `text/html; charset=utf-8`). Introducing
/// the type means an arbitrary string can no longer stand in for a media content type
/// (ADR-0063 §1), and every accepted value is a valid HTTP header / Atom `type=` value.
///
/// [`FromStr`] is the single validating chokepoint — it delegates to the private
/// `is_valid_content_type`. The rest of the ADR-0063 string-newtype trailer (`Display`,
/// `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned `String` conversions,
/// `PartialEq<str>`, and the validating serde + sqlx bridges) is generated by
/// `#[derive(StrNewtype)]`. The wrapped `String` is private, so the only way in is the
/// validating door — an arbitrary `String` cannot masquerade as a content type:
/// ```compile_fail
/// let _ = common::media::ContentType("x".to_string()); // private field
/// ```
/// ```compile_fail
/// fn takes_content_type(_: common::media::ContentType) {}
/// takes_content_type("image/png".to_string()); // a String is not a ContentType
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct ContentType(String);

/// Error returned when a string is not a valid media `Content-Type` value.
#[derive(Debug, Error)]
#[error("content type must be a `type/subtype` media type, e.g. `image/png`")]
pub struct InvalidContentType;

impl FromStr for ContentType {
    type Err = InvalidContentType;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if is_valid_content_type(s) {
            Ok(ContentType(s.to_owned()))
        } else {
            Err(InvalidContentType)
        }
    }
}

/// An RFC 7230 `tchar` (the token characters a `type`/`subtype` may use).
fn is_tchar(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b"!#$%&'*+-.^_`|~".contains(&b)
}

/// Whether `s` is a valid media `Content-Type`: every byte a valid `HeaderValue` byte
/// (`VCHAR` / SP / HTAB), and the essence (before the first `;`) is `token "/" token` with
/// non-empty, `tchar`-only halves. Parameters (after `;`) need only be header-safe — so
/// every accepted value is `HeaderValue::from_str`-constructible. The single source of
/// truth for [`ContentType`]'s invariant.
fn is_valid_content_type(s: &str) -> bool {
    if !s.bytes().all(|b| b == b'\t' || (0x20..=0x7e).contains(&b)) {
        return false;
    }
    // The essence is everything before the first `;` (or the whole string when there is no
    // parameter list); RFC 7231 permits optional whitespace around it, so trim for the check.
    let essence = s.split_once(';').map_or(s, |(before, _)| before).trim();
    let Some((ty, sub)) = essence.split_once('/') else {
        return false;
    };
    !ty.is_empty() && !sub.is_empty() && ty.bytes().all(is_tchar) && sub.bytes().all(is_tchar)
}

/// Returns true if the content type should be served inline rather than as an attachment.
#[must_use]
pub fn should_inline(content_type: &str) -> bool {
    matches!(
        content_type,
        "image/jpeg"
            | "image/png"
            | "image/gif"
            | "image/webp"
            | "image/svg+xml"
            | "audio/mpeg"
            | "audio/ogg"
            | "audio/flac"
            | "audio/wav"
            | "video/mp4"
            | "video/webm"
            | "application/pdf"
    )
}

/// Extension-based content type detection. Falls back to `application/octet-stream`.
/// The trusted producer door: it mints the [`ContentType`] directly from its canonical
/// `&'static str` table (all valid `type/subtype` literals), the way `render` mints
/// `RenderedHtml` — no `FromStr` round-trip, since the table is fixed and known-valid
/// (pinned by `detect_content_type_outputs_are_valid`).
#[must_use]
pub fn detect_content_type(filename: &str) -> ContentType {
    static EXTENSIONS: [(&[&str], &str); 12] = [
        (&["jpg", "jpeg"], "image/jpeg"),
        (&["png"], "image/png"),
        (&["gif"], "image/gif"),
        (&["webp"], "image/webp"),
        (&["svg"], "image/svg+xml"),
        (&["mp3"], "audio/mpeg"),
        (&["ogg", "oga"], "audio/ogg"),
        (&["flac"], "audio/flac"),
        (&["wav"], "audio/wav"),
        (&["mp4"], "video/mp4"),
        (&["webm"], "video/webm"),
        (&["pdf"], "application/pdf"),
    ];

    let ext = Path::new(filename)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();

    for (extensions, content_type) in EXTENSIONS {
        if extensions.contains(&ext.as_str()) {
            return ContentType(content_type.to_owned());
        }
    }
    ContentType("application/octet-stream".to_owned())
}

/// The maximum accepted upload size, in bytes (site config `media.max_file_size_bytes`).
/// A positive `i64` — a zero/negative limit is nonsensical — enforced by the
/// `NumNewtype`-generated validating `FromStr`/serde. Default 50 MiB.
#[derive(Clone, Copy, Debug, Eq, PartialEq, NumNewtype)]
#[num_newtype(
    inner = i64,
    min = 1,
    default = 52_428_800, // 50 MiB
    error = "media max file size must be a positive number of bytes"
)]
pub struct MaxFileSize(i64);

/// The per-user upload quota, in bytes (site config `media.user_quota_bytes`).
/// A positive `i64`, like [`MaxFileSize`]; a distinct type so a per-file limit and a
/// per-user quota can't be transposed. Default 1 GiB.
#[derive(Clone, Copy, Debug, Eq, PartialEq, NumNewtype)]
#[num_newtype(
    inner = i64,
    min = 1,
    default = 1_073_741_824, // 1 GiB
    error = "media user quota must be a positive number of bytes"
)]
pub struct UserQuota(i64);

#[cfg(test)]
mod tests {
    use super::*;
    use sha2::{Digest, Sha256};

    /// Drives the whole `NumNewtype`-generated surface of a positive-`i64` (min-1) byte
    /// newtype `T`: parse accept/trim, reject `0`/negative/non-integer with the domain
    /// message, `Default`, `Display` round-trip, `From<Self> for i64`, and the
    /// transparent-`i64` serde bridge (round-trip + wire-rejection of `0`). Both byte-limit
    /// types share this shape, so one generic assertion replaces two near-identical tests.
    /// The DTO does not serde these on the host build, so this is the reachability for that
    /// generated code. Written via `From`/`.ok()`/`.err()` (no `unwrap`), so it needs no
    /// lint exception.
    fn assert_positive_byte_newtype<T>(default: i64, err_prefix: &str)
    where
        T: ::core::str::FromStr
            + ::core::default::Default
            + ::core::fmt::Display
            + ::core::fmt::Debug
            + ::core::marker::Copy
            + ::core::cmp::PartialEq
            + ::serde::Serialize
            + ::serde::de::DeserializeOwned,
        T::Err: ::core::fmt::Display,
        i64: ::core::convert::From<T>,
    {
        // parse accepts and trims
        assert_eq!("5".parse::<T>().map(i64::from).ok(), Some(5));
        assert_eq!("  100  ".parse::<T>().map(i64::from).ok(), Some(100));
        // parse rejects 0, negatives, and non-integers...
        for bad in ["0", "-1", "abc", "1.5"] {
            assert!(bad.parse::<T>().is_err(), "{bad} should reject");
        }
        // ...with the domain message
        assert!("0"
            .parse::<T>()
            .err()
            .is_some_and(|e| e.to_string().starts_with(err_prefix)));
        // Default, and From<Self> for i64
        let d = T::default();
        assert_eq!(i64::from(d), default);
        // Display round-trips through FromStr
        assert_eq!(d.to_string().parse::<T>().ok(), Some(d));
        // serde: bare integer, round-trip, wire-rejection of 0
        assert_eq!(serde_json::to_string(&d).ok(), Some(default.to_string()));
        assert_eq!(
            serde_json::from_str::<T>("42").map(i64::from).ok(),
            Some(42)
        );
        assert!(serde_json::from_str::<T>("0").is_err());
    }

    #[test]
    fn max_file_size_surface() {
        assert_positive_byte_newtype::<MaxFileSize>(52_428_800, "media max file size");
    }

    #[test]
    fn user_quota_surface() {
        assert_positive_byte_newtype::<UserQuota>(1_073_741_824, "media user quota");
    }

    #[test]
    fn sanitize_strips_path_components() {
        assert_eq!(sanitize_filename("../../etc/passwd"), "passwd");
        assert_eq!(sanitize_filename("foo/bar/baz.txt"), "baz.txt");
        assert_eq!(sanitize_filename("C:\\Users\\file.txt"), "file.txt");
    }

    #[test]
    fn sanitize_replaces_unsafe_chars() {
        assert_eq!(sanitize_filename("file\0name.txt"), "file_name.txt");
        assert_eq!(sanitize_filename("\0"), "_");
    }

    #[test]
    fn sanitize_rejects_empty() {
        assert!(sanitize_filename("").is_empty());
        assert!(sanitize_filename(".").is_empty());
        assert!(sanitize_filename("..").is_empty());
    }

    #[test]
    fn media_path_computation() {
        let hash: ContentHash = CANONICAL.parse().unwrap();
        let path = media_path("upload", &hash, "photo.jpg");
        assert_eq!(path, format!("upload/e3/b0/{CANONICAL}/photo.jpg"));
    }

    #[test]
    fn media_url_computation() {
        let hash: ContentHash = CANONICAL.parse().unwrap();
        let url = media_url("upload", &hash, "photo.jpg");
        assert_eq!(url, format!("/media/upload/e3/b0/{CANONICAL}/photo.jpg"));
    }

    #[test]
    fn content_disposition_inline_for_images() {
        assert!(should_inline("image/jpeg"));
        assert!(should_inline("image/png"));
        assert!(should_inline("image/gif"));
        assert!(should_inline("image/webp"));
        assert!(should_inline("image/svg+xml"));
    }

    #[test]
    fn content_disposition_inline_for_media() {
        assert!(should_inline("audio/mpeg"));
        assert!(should_inline("video/mp4"));
        assert!(should_inline("application/pdf"));
    }

    #[test]
    fn content_disposition_attachment_for_others() {
        assert!(!should_inline("application/zip"));
        assert!(!should_inline("text/plain"));
        assert!(!should_inline("application/octet-stream"));
    }

    #[test]
    fn detect_content_type_known_extensions() {
        assert_eq!(detect_content_type("photo.jpg"), "image/jpeg");
        assert_eq!(detect_content_type("photo.jpeg"), "image/jpeg");
        assert_eq!(detect_content_type("image.png"), "image/png");
        assert_eq!(detect_content_type("doc.pdf"), "application/pdf");
        assert_eq!(detect_content_type("video.mp4"), "video/mp4");
    }

    #[test]
    fn detect_content_type_image_formats() {
        assert_eq!(detect_content_type("anim.gif"), "image/gif");
        assert_eq!(detect_content_type("photo.webp"), "image/webp");
        assert_eq!(detect_content_type("icon.svg"), "image/svg+xml");
    }

    #[test]
    fn detect_content_type_audio_formats() {
        assert_eq!(detect_content_type("track.mp3"), "audio/mpeg");
        assert_eq!(detect_content_type("track.ogg"), "audio/ogg");
        assert_eq!(detect_content_type("track.oga"), "audio/ogg");
        assert_eq!(detect_content_type("track.flac"), "audio/flac");
        assert_eq!(detect_content_type("track.wav"), "audio/wav");
    }

    #[test]
    fn detect_content_type_video_webm() {
        assert_eq!(detect_content_type("clip.webm"), "video/webm");
    }

    #[test]
    fn detect_content_type_unknown_extension() {
        assert_eq!(detect_content_type("file.xyz"), "application/octet-stream");
        assert_eq!(detect_content_type("noext"), "application/octet-stream");
    }

    #[test]
    fn content_type_accepts_valid() {
        for s in [
            "image/png",
            "application/pdf",
            "image/svg+xml",
            "text/html; charset=utf-8",
            "application/octet-stream",
        ] {
            assert!(s.parse::<ContentType>().is_ok(), "must accept {s:?}");
        }
    }

    #[test]
    fn content_type_rejects_malformed() {
        for s in [
            "",
            "garbage",             // no slash
            "a/",                  // empty subtype
            "/b",                  // empty type
            "image /png",          // space in type (not a tchar)
            "text/plain; x=\u{1}", // control byte inside a parameter
            "im\u{1}age/png",      // control byte in the type
        ] {
            assert!(s.parse::<ContentType>().is_err(), "must reject {s:?}");
        }
    }

    #[test]
    fn detect_content_type_outputs_are_valid() {
        // The in-module mint is honest: every canonical literal + the fallback re-parses
        // through the validating `FromStr`, so `detect` never fabricates an invalid value.
        for f in [
            "a.jpg",
            "a.png",
            "a.gif",
            "a.webp",
            "a.svg",
            "a.mp3",
            "a.ogg",
            "a.flac",
            "a.wav",
            "a.mp4",
            "a.webm",
            "a.pdf",
            "a.unknownext",
        ] {
            assert!(detect_content_type(f)
                .as_ref()
                .parse::<ContentType>()
                .is_ok());
        }
    }

    #[test]
    fn valid_content_hash_accepts_64_lowercase_hex() {
        let hash = "a".repeat(64);
        assert!(is_valid_content_hash(&hash));
        // A realistic lowercase sha256 hex digest.
        assert!(is_valid_content_hash(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        ));
    }

    #[test]
    fn valid_content_hash_rejects_short_input() {
        // The historical panic trigger: a single byte cannot be sliced at [2..].
        assert!(!is_valid_content_hash("a"));
        assert!(!is_valid_content_hash(""));
        assert!(!is_valid_content_hash(&"a".repeat(63)));
    }

    #[test]
    fn valid_content_hash_rejects_long_input() {
        assert!(!is_valid_content_hash(&"a".repeat(65)));
    }

    #[test]
    fn valid_content_hash_rejects_uppercase_hex() {
        // Stored digests are lowercase (`format!("{digest:x}")`); uppercase is not canonical.
        assert!(!is_valid_content_hash(&"A".repeat(64)));
    }

    #[test]
    fn valid_content_hash_rejects_non_hex_chars() {
        // 64 chars but contains a non-hex letter.
        assert!(!is_valid_content_hash(&format!("g{}", "a".repeat(63))));
        // 64 chars but contains a path separator.
        assert!(!is_valid_content_hash(&format!("/{}", "a".repeat(63))));
    }

    #[test]
    fn valid_content_hash_rejects_non_ascii_off_boundary() {
        // A multi-byte char makes byte index 2 land off a UTF-8 boundary — the
        // other historical panic source. 21 'é' chars = 42 bytes ... build a
        // 64-byte string whose char boundaries do not align with byte 2.
        let hash = format!("é{}", "a".repeat(62));
        assert!(!is_valid_content_hash(&hash));
    }

    // A realistic lowercase SHA-256 hex digest (the digest of the empty input).
    const CANONICAL: &str = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

    #[test]
    fn content_hash_parses_canonical_digest() {
        let h: ContentHash = CANONICAL.parse().unwrap();
        assert_eq!(h, CANONICAL);
    }

    #[test]
    fn content_hash_rejects_non_canonical_forms() {
        // Reuses the `is_valid_content_hash` invariants: short, long, uppercase,
        // non-hex, off-boundary.
        assert!("a".parse::<ContentHash>().is_err());
        assert!("a".repeat(63).parse::<ContentHash>().is_err());
        assert!("a".repeat(65).parse::<ContentHash>().is_err());
        assert!("A".repeat(64).parse::<ContentHash>().is_err());
        assert!(format!("g{}", "a".repeat(63))
            .parse::<ContentHash>()
            .is_err());
        assert!(format!("é{}", "a".repeat(62))
            .parse::<ContentHash>()
            .is_err());
    }

    #[test]
    fn content_hash_display_produces_the_canonical_string() {
        let h: ContentHash = CANONICAL.parse().unwrap();
        assert_eq!(h.to_string(), CANONICAL);
    }

    #[test]
    fn content_hash_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let h: ContentHash = CANONICAL.parse().unwrap();
        assert_eq!(
            serde_json::to_string(&h).unwrap(),
            format!("\"{CANONICAL}\"")
        );

        // Deserialize routes through the validating parse.
        assert_eq!(
            serde_json::from_str::<ContentHash>(&format!("\"{CANONICAL}\"")).unwrap(),
            h
        );
        // Invalid input is rejected at deserialize time (wire rejection).
        assert!(serde_json::from_str::<ContentHash>("\"not-a-hash\"").is_err());
    }

    #[test]
    fn content_hash_from_digest_hex_encodes_the_32_digest_bytes() {
        // The producer door hex-encodes exactly 32 bytes into the canonical
        // 64-char lowercase form — always a valid ContentHash by construction.
        assert_eq!(ContentHash::from_digest([0u8; 32]), "0".repeat(64).as_str());
        assert_eq!(
            ContentHash::from_digest([0xab; 32]),
            "ab".repeat(32).as_str()
        );
        // A real digest round-trips: its hex equals the canonical string form.
        let digest: [u8; 32] = Sha256::digest(b"").into();
        assert_eq!(ContentHash::from_digest(digest), CANONICAL);
    }

    #[test]
    fn content_hash_invalid_error_displays_the_rule() {
        let msg = "bad".parse::<ContentHash>().unwrap_err().to_string();
        assert!(msg.contains("64 lowercase hex"), "{msg}");
    }

    // --- Filename: Door A (validating FromStr, canonical-only) ---

    #[test]
    fn filename_parses_a_canonical_leaf() {
        let f: Filename = "photo.jpg".parse().unwrap();
        assert_eq!(f, "photo.jpg");
    }

    #[test]
    fn filename_rejects_non_canonical_and_empty() {
        // Non-canonical names (which Door B *would* normalize) and empty are
        // rejected here, not normalized — Door A only accepts an already-safe leaf.
        for bad in [
            "",
            "..",
            ".",
            "a/b",
            "../x",
            "sub/file.txt",
            "C:\\x\\y.txt",
            "foo\0",
        ] {
            assert!(bad.parse::<Filename>().is_err(), "must reject {bad:?}");
        }
    }

    #[test]
    fn filename_display_and_deref_read_the_leaf() {
        let f: Filename = "a.txt".parse().unwrap();
        assert_eq!(f.to_string(), "a.txt");
        assert_eq!(&f[..1], "a"); // Deref<Target = str>
    }

    // --- Filename: Door B (normalizing producer) ---

    #[test]
    fn sanitized_normalizes_to_a_safe_leaf() {
        assert_eq!(Filename::sanitized("../../etc/passwd").unwrap(), "passwd");
        assert_eq!(Filename::sanitized("foo/bar/baz.txt").unwrap(), "baz.txt");
        assert_eq!(
            Filename::sanitized("file\0name.txt").unwrap(),
            "file_name.txt"
        );
    }

    #[test]
    fn sanitized_rejects_empty_after_normalization() {
        for bad in ["", ".", ".."] {
            assert!(Filename::sanitized(bad).is_err(), "must reject {bad:?}");
        }
    }

    #[test]
    fn filename_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let f: Filename = "photo.jpg".parse().unwrap();
        assert_eq!(serde_json::to_string(&f).unwrap(), "\"photo.jpg\"");
        assert_eq!(
            serde_json::from_str::<Filename>("\"photo.jpg\"").unwrap(),
            f
        );
        // A non-canonical name is rejected at deserialize time (wire rejection).
        assert!(serde_json::from_str::<Filename>("\"../x\"").is_err());
    }

    #[test]
    fn filename_invalid_error_displays_the_rule() {
        let msg = "..".parse::<Filename>().unwrap_err().to_string();
        assert!(msg.contains("safe path leaf"), "{msg}");
    }

    // Idempotence pin (spec criterion 8): every non-empty `sanitize_filename`
    // output must re-parse through Door A. A future change to `sanitize_filename`
    // that broke idempotence would silently turn stored (Door-B-written) filenames
    // into `Decode` errors on read-back — this fails loudly here instead.
    #[test]
    fn sanitize_filename_output_always_reparses_as_filename() {
        for raw in [
            "photo.jpg",
            "../../etc/passwd",
            "foo/bar/baz.txt",
            "C:\\Users\\file.txt",
            "file\0name.txt",
            "a b.txt",
            ".hidden",
            "no-ext",
        ] {
            let s = sanitize_filename(raw);
            // Every non-empty sanitize output must re-parse through Door A. Expressed
            // as a single disjunction (not an `if` guard) so no always-true branch
            // region is left uncovered; none of these inputs sanitize to empty, so the
            // left disjunct is false and the parse is what's actually asserted.
            assert!(
                s.is_empty() || s.parse::<Filename>().is_ok(),
                "sanitize({raw:?}) = {s:?} must re-parse as Filename"
            );
        }
    }

    #[test]
    fn media_source_tokens_parse_and_round_trip() {
        assert_eq!(
            "upload".parse::<MediaSource>().unwrap(),
            MediaSource::Upload
        );
        assert_eq!(
            "cached".parse::<MediaSource>().unwrap(),
            MediaSource::Cached
        );
        assert_eq!(MediaSource::Upload.as_str(), "upload");
        assert_eq!(MediaSource::Cached.to_string(), "cached");
    }

    #[test]
    fn media_source_unknown_token_is_rejected_with_message() {
        let err = "bogus".parse::<MediaSource>().unwrap_err();
        assert_eq!(
            err.to_string(),
            "media source must be \"upload\" or \"cached\""
        );
    }

    #[test]
    fn media_source_serde_round_trips_the_token() {
        assert_eq!(
            serde_json::to_string(&MediaSource::Cached).unwrap(),
            "\"cached\""
        );
        assert_eq!(
            serde_json::from_str::<MediaSource>("\"upload\"").unwrap(),
            MediaSource::Upload
        );
    }
}
