use macros::StrNewtype;

/// A post's raw source body.
///
/// An **infallible** wrapper (no length bound — any body is valid; see ADR-0063 and
/// issue #402) whose purpose is to keep raw source distinct from rendered output
/// ([`crate::render::RenderedHtml`]), so the two ends of the render pipeline cannot be
/// transposed. The ADR-0063 string-newtype trailer (`Display`, `AsRef`/`Borrow`/
/// `Deref<str>`, owned-`String` conversion, `PartialEq<str>`, and the serde bridge) is
/// generated by `#[derive(StrNewtype)] #[str_newtype(infallible)]`; `From<String>` is the
/// single (pure-wrap) construction door, through which the derived `Deserialize` also
/// routes, so a `PostBody` serializes as a plain string.
///
/// A `PostBody` is not a `RenderedHtml`, and neither converts to the other.
///
/// The positive companion shows the identical fixture compiles — both paths resolve
/// and both construction doors accept a `&str` — so each `compile_fail` below fails
/// for the type mismatch rather than because a door changed shape. (Fixture lines
/// are hidden with `#`.)
///
/// ```
/// use common::post_body::PostBody;
/// use common::render::RenderedHtml;
/// let body = PostBody::from("x");
/// let html = RenderedHtml::from_trusted("x");
/// let _b: &str = body.as_ref();
/// let _h: &str = html.as_ref();
/// ```
///
/// No `PostBody` -> `RenderedHtml` conversion. Asserted on `.into()`, not on a
/// function argument: Rust never coerces an argument through `From`, so
/// `want_html(body)` would fail for any two distinct types and would keep failing
/// even if the `From` impl this forbids were added.
/// ```compile_fail
/// # use common::post_body::PostBody;
/// # use common::render::RenderedHtml;
/// # let body = PostBody::from("x");
/// let _h: RenderedHtml = body.into();
/// ```
///
/// …nor the reverse:
/// ```compile_fail
/// # use common::post_body::PostBody;
/// # use common::render::RenderedHtml;
/// # let html = RenderedHtml::from_trusted("x");
/// let _b: PostBody = html.into();
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
#[str_newtype(infallible)]
pub struct PostBody(String);

impl From<String> for PostBody {
    fn from(s: String) -> Self {
        Self(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn post_body_wraps_verbatim_without_trimming() {
        // Unlike PostTitle, a body is never trimmed — leading/trailing whitespace is
        // meaningful content.
        let b = PostBody::from("  # Heading\n\nbody  ");
        assert_eq!(b, "  # Heading\n\nbody  ");
    }

    #[test]
    fn post_body_display_and_deref_expose_inner() {
        let b = PostBody::from("hello");
        assert_eq!(b.to_string(), "hello");
        assert_eq!(&*b, "hello");
        assert!(b.contains("ell")); // str method via Deref
    }

    #[test]
    fn post_body_serde_round_trips_as_plain_string() {
        let b = PostBody::from("raw *body*");
        assert_eq!(serde_json::to_string(&b).unwrap(), "\"raw *body*\"");
        assert_eq!(
            serde_json::from_str::<PostBody>("\"raw *body*\"").unwrap(),
            b
        );
    }

    #[test]
    fn post_body_into_string_extracts_inner() {
        assert_eq!(String::from(PostBody::from("x")), "x");
    }
}
