use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A post's raw source body: at least one non-blank line, stored **verbatim**.
///
/// Keeps raw source distinct from rendered output ([`crate::render::RenderedHtml`]), so
/// the two ends of the render pipeline cannot be transposed. The ADR-0063 string-newtype
/// trailer (`Display`, `AsRef`/`Borrow`/`Deref<str>`, owned-`String` conversion,
/// `PartialEq<str>`, and the serde bridge) is generated by `#[derive(StrNewtype)]`.
///
/// [`FromStr`] is the **single** construction door, and the derived `Deserialize` and the
/// sqlx bridge both route through it — so a body with no non-blank line is rejected on the
/// wire *and* on decode, with no trusted bypass for stored rows. There is no legacy data
/// to accommodate (#811).
///
/// There is no length bound: any body *length* is valid. What is rejected is a body that
/// is nothing but blank lines.
///
/// **This door validates but never normalizes**, because it cannot: whether trailing
/// whitespace is content depends on the `PostFormat`, which lives beside the body rather
/// than in it. Normalization belongs to the format-aware seam in [`crate::render`].
/// Trimming here would be actively wrong — a Markdown body of `"    fn main() {}\n"` is a
/// `CommonMark` indented code block, and trimming renders it as a paragraph instead.
///
/// A `PostBody` is not a `RenderedHtml`, and neither converts to the other.
///
/// Positive companion: both endpoint types resolve independently.
/// ```
/// # use common::post_body::PostBody;
/// # use common::render::RenderedHtml;
/// fn names_resolve(_: Option<PostBody>, _: Option<RenderedHtml>) {}
/// ```
///
/// No `PostBody` -> `RenderedHtml` conversion. Asserted on `Into` itself:
/// ```compile_fail
/// # use common::post_body::PostBody;
/// # use common::render::RenderedHtml;
/// fn require_into<T: Into<RenderedHtml>>() {}
/// require_into::<PostBody>();
/// ```
///
/// …nor the reverse:
/// ```compile_fail
/// # use common::post_body::PostBody;
/// # use common::render::RenderedHtml;
/// fn require_into<T: Into<PostBody>>() {}
/// require_into::<RenderedHtml>();
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct PostBody(String);

/// Error returned when a string cannot be parsed as a [`PostBody`].
#[derive(Debug, Error)]
#[error("post body must contain at least one non-blank line")]
pub struct InvalidPostBody;

impl FromStr for PostBody {
    type Err = InvalidPostBody;

    /// Validates, then stores **verbatim** — unlike [`crate::post_summary::PostSummary`],
    /// a body is never trimmed. See the type docs for why normalization cannot happen
    /// here.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s.lines().all(|line| line.trim().is_empty()) {
            return Err(InvalidPostBody);
        }
        Ok(PostBody(s.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(s: &str) -> PostBody {
        s.parse().expect("fixture is a valid body")
    }

    #[test]
    fn post_body_wraps_verbatim_without_trimming() {
        // Unlike PostTitle, a body is never trimmed — leading/trailing whitespace is
        // meaningful content.
        let b = parse("  # Heading\n\nbody  ");
        assert_eq!(b, "  # Heading\n\nbody  ");
    }

    #[test]
    fn post_body_display_and_deref_expose_inner() {
        let b = parse("hello");
        assert_eq!(b.to_string(), "hello");
        assert_eq!(&*b, "hello");
        assert!(b.contains("ell")); // str method via Deref
    }

    #[test]
    fn post_body_serde_round_trips_as_plain_string() {
        let b = parse("raw *body*");
        assert_eq!(serde_json::to_string(&b).unwrap(), "\"raw *body*\"");
        assert_eq!(
            serde_json::from_str::<PostBody>("\"raw *body*\"").unwrap(),
            b
        );
    }

    #[test]
    fn post_body_into_string_extracts_inner() {
        assert_eq!(String::from(parse("x")), "x");
    }

    #[test]
    fn post_body_rejects_whitespace_only() {
        for blank in ["", "   ", "\n\n", "  \n \t \n"] {
            assert!(
                blank.parse::<PostBody>().is_err(),
                "expected {blank:?} to be rejected"
            );
        }
    }

    #[test]
    fn post_body_accepts_body_with_blank_lines_around_content() {
        assert!("\n\n  hi  \n\n".parse::<PostBody>().is_ok());
    }

    #[test]
    fn post_body_deserialize_rejects_blank() {
        assert!(serde_json::from_str::<PostBody>("\"  \\n \"").is_err());
    }

    #[test]
    fn post_body_preserves_verbatim_after_validation() {
        // Pins the wrapper, not the reason — the load-bearing guard against a "tidy-up"
        // trim is `markdown_body_with_leading_indent_still_renders_as_code_block` in
        // `crate::render`, which catches a code block silently becoming prose.
        let raw = "\n\n    fn main() {}\n\n  ";
        assert_eq!(parse(raw), raw);
    }
}
