use macros::StrNewtype;

/// A post's title.
///
/// An **infallible** wrapper (no length bound — issue #402) that **trims** outer
/// whitespace on construction, preserving case and internal whitespace (ADR-0063; spec
/// D2). The string-newtype trailer (`Display`, `AsRef`/`Borrow`/`Deref<str>`, owned-
/// `String` conversion, `PartialEq<str>`, the serde bridge) is generated by
/// `#[derive(StrNewtype)] #[str_newtype(infallible)]`; `From<String>` is the single
/// (trimming) construction door, through which the derived `Deserialize` also routes, so
/// wire values are trimmed identically to in-process construction.
///
/// Collapsing an empty-after-trim title to `None` is the caller's job (the field is
/// `Option<PostTitle>` and `derive_post_metadata` decides presence), not this type's.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
#[str_newtype(infallible)]
pub struct PostTitle(String);

impl From<String> for PostTitle {
    fn from(s: String) -> Self {
        Self(s.trim().to_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn post_title_trims_outer_whitespace_preserving_inner_and_case() {
        let t = PostTitle::from("  Hello  World  ");
        assert_eq!(t, "Hello  World");
    }

    #[test]
    fn post_title_deserialize_trims() {
        // Deserialize routes through From<String>, so wire input is trimmed too.
        assert_eq!(
            serde_json::from_str::<PostTitle>("\"  Trimmed \"").unwrap(),
            PostTitle::from("Trimmed")
        );
    }

    #[test]
    fn post_title_serializes_as_plain_string() {
        assert_eq!(
            serde_json::to_string(&PostTitle::from("Title")).unwrap(),
            "\"Title\""
        );
    }

    #[test]
    fn post_title_display_exposes_inner() {
        assert_eq!(PostTitle::from(" Hi ").to_string(), "Hi");
    }
}
