use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// Maximum session/app-password label length, in Unicode scalar values. Generous —
/// a label is a free-form human tag (a device or app name), not an identifier —
/// while still bounding the stored value and the create form. Chosen ≥ the login
/// User-Agent label truncation (200 chars, [`crate`]-external) so the read-side
/// decode of pre-existing session rows never fails (#325).
pub const MAX_SESSION_LABEL_CHARS: usize = 255;

/// A validated session label: surrounding whitespace trimmed, non-empty, at most
/// [`MAX_SESSION_LABEL_CHARS`] scalars. Casing is preserved (a label is a human
/// tag, not a normalized identifier).
///
/// Constructed via [`FromStr`] — the single validating/normalizing chokepoint;
/// invalid strings are rejected at the boundary so interior code (and storage)
/// works only with already-valid labels. The rest of the ADR-0063 string-newtype
/// trailer (`Display`, `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`, owned
/// `String` conversions, `PartialEq<str>`/`PartialEq<&str>`, and the validating
/// serde and sqlx bridges) is generated by `#[derive(StrNewtype)]`, so a
/// `SessionLabel` serializes as a plain string, rejects invalid input on the wire,
/// and binds/decodes as a TEXT column. No `Hash` — a `SessionLabel` is never a
/// map/set key.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct SessionLabel(String);

/// Error returned when a string cannot be parsed as a [`SessionLabel`].
#[derive(Debug, Error)]
#[error("session label must be non-empty and at most {MAX_SESSION_LABEL_CHARS} characters")]
pub struct InvalidSessionLabel;

impl FromStr for SessionLabel {
    type Err = InvalidSessionLabel;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() || trimmed.chars().count() > MAX_SESSION_LABEL_CHARS {
            return Err(InvalidSessionLabel);
        }
        Ok(SessionLabel(trimmed.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_label_parses_and_preserves_casing() {
        assert_eq!("MarsEdit".parse::<SessionLabel>().unwrap(), "MarsEdit");
        assert_eq!(
            "Ada's iPhone".parse::<SessionLabel>().unwrap(),
            "Ada's iPhone"
        );
        // Unicode is preserved as-is (no lowercasing/normalization).
        assert_eq!("Москва".parse::<SessionLabel>().unwrap(), "Москва");
    }

    #[test]
    fn session_label_trims_surrounding_whitespace() {
        assert_eq!("  Laptop  ".parse::<SessionLabel>().unwrap(), "Laptop");
        // Interior whitespace is kept.
        assert_eq!(" a b ".parse::<SessionLabel>().unwrap(), "a b");
    }

    #[test]
    fn session_label_rejects_empty_and_whitespace_only() {
        assert!("".parse::<SessionLabel>().is_err());
        assert!("   ".parse::<SessionLabel>().is_err());
        assert!("\t\n".parse::<SessionLabel>().is_err());
    }

    #[test]
    fn session_label_enforces_length_cap() {
        let max: String = "a".repeat(MAX_SESSION_LABEL_CHARS);
        assert!(max.parse::<SessionLabel>().is_ok());
        let over: String = "a".repeat(MAX_SESSION_LABEL_CHARS + 1);
        assert!(over.parse::<SessionLabel>().is_err());
        // The cap counts scalars post-trim, so surrounding whitespace does not
        // push an otherwise-valid label over the limit.
        let padded = format!("  {}  ", "a".repeat(MAX_SESSION_LABEL_CHARS));
        assert!(padded.parse::<SessionLabel>().is_ok());
    }

    #[test]
    fn session_label_display_returns_inner_string() {
        let l: SessionLabel = "MarsEdit".parse().unwrap();
        assert_eq!(l.to_string(), "MarsEdit");
        assert_eq!(l, "MarsEdit"); // generated PartialEq<&str>
    }

    #[test]
    fn session_label_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let l: SessionLabel = "MarsEdit".parse().unwrap();
        assert_eq!(serde_json::to_string(&l).unwrap(), "\"MarsEdit\"");
        assert_eq!(
            serde_json::from_str::<SessionLabel>("\"MarsEdit\"").unwrap(),
            "MarsEdit".parse::<SessionLabel>().unwrap()
        );
        // Invalid input (empty) is rejected at deserialize time.
        assert!(serde_json::from_str::<SessionLabel>("\"\"").is_err());
    }
}
