use std::str::FromStr;

use macros::StrNewtype;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::tagged_url::BaseUrl;

/// Site-wide identity and configuration.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SiteIdentity {
    /// Human-facing title for the site, used in feed metadata and similar contexts.
    pub title: SiteTitle,
    /// Optional plain-text description of Local and site-wide Syndication Feeds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tagline: Option<SiteTagline>,
    /// Public-facing base URL (an absolute `http(s)` origin, normalized to its
    /// canonical form with a trailing slash), if set. When absent, callers emit
    /// root-relative URLs.
    pub base_url: Option<BaseUrl>,
}

/// Default site title when no custom value is configured.
pub const DEFAULT_SITE_TITLE: &str = "Jaunder";

/// The site's human-facing title — surrounding whitespace trimmed, non-empty, casing and
/// interior whitespace preserved. The **validating** counterpart of the infallible
/// [`PostTitle`](crate::post_title::PostTitle); modelled on
/// [`DisplayName`](crate::display_name::DisplayName). No length cap (#580).
///
/// Constructed via [`FromStr`] — the single validating/normalizing chokepoint; the rest of the
/// ADR-0063 string-newtype trailer (`Display`, `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`,
/// owned `String` conversions, `PartialEq<str>`/`<&str>`, and the validating serde bridge) is
/// generated by `#[derive(StrNewtype)]`, so a `SiteTitle` serializes as a plain string and
/// rejects an empty value on the wire — safe as a (de)serialized DTO field.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct SiteTitle(String);

/// Error returned when a string cannot be parsed as a [`SiteTitle`].
#[derive(Debug, Error)]
#[error("site title cannot be empty")]
pub struct InvalidSiteTitle;

impl FromStr for SiteTitle {
    type Err = InvalidSiteTitle;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() {
            return Err(InvalidSiteTitle);
        }
        Ok(SiteTitle(trimmed.to_owned()))
    }
}

/// The optional Site Tagline — single-line plain text with surrounding whitespace
/// trimmed and at most 280 Unicode scalar values.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct SiteTagline(String);

/// Error returned when a string cannot be parsed as a [`SiteTagline`].
#[derive(Debug, Error)]
pub enum InvalidSiteTagline {
    /// An optional tagline has no non-blank representation.
    #[error("site tagline cannot be blank")]
    Blank,
    /// Line separators would violate the single-line presentation contract.
    #[error("site tagline cannot contain line separators")]
    LineSeparator,
    /// The display value exceeds the public presentation limit.
    #[error("site tagline cannot exceed 280 Unicode scalar values")]
    TooLong,
}

impl FromStr for SiteTagline {
    type Err = InvalidSiteTagline;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s.contains(['\r', '\n', '\u{0085}', '\u{2028}', '\u{2029}']) {
            return Err(InvalidSiteTagline::LineSeparator);
        }
        let trimmed = s.trim();
        if trimmed.is_empty() {
            return Err(InvalidSiteTagline::Blank);
        }
        if trimmed.chars().count() > 280 {
            return Err(InvalidSiteTagline::TooLong);
        }
        Ok(Self(trimmed.to_owned()))
    }
}

impl Default for SiteTitle {
    /// The app's canonical default ([`DEFAULT_SITE_TITLE`]) — the infallible construction door
    /// `get_identity` uses when no custom title is configured. `DEFAULT_SITE_TITLE` is non-empty,
    /// so the default is itself a valid `SiteTitle`.
    fn default() -> Self {
        Self(DEFAULT_SITE_TITLE.to_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn site_title_parses_trims_and_preserves_inner_and_casing() {
        assert_eq!("  My Blog  ".parse::<SiteTitle>().unwrap(), "My Blog");
        assert_eq!("A B".parse::<SiteTitle>().unwrap(), "A B");
        assert_eq!("Москва".parse::<SiteTitle>().unwrap(), "Москва");
    }

    #[test]
    fn site_title_rejects_empty_and_whitespace_only() {
        assert!("".parse::<SiteTitle>().is_err());
        assert!("   ".parse::<SiteTitle>().is_err());
        assert_eq!(
            "".parse::<SiteTitle>().unwrap_err().to_string(),
            "site title cannot be empty"
        );
    }

    #[test]
    fn site_title_display_and_partial_eq_str() {
        let t: SiteTitle = "Jaunder".parse().unwrap();
        assert_eq!(t.to_string(), "Jaunder");
        assert_eq!(t, "Jaunder"); // generated PartialEq<&str>
    }

    #[test]
    fn site_title_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let t: SiteTitle = "Jaunder".parse().unwrap();
        assert_eq!(serde_json::to_string(&t).unwrap(), "\"Jaunder\"");
        assert_eq!(
            serde_json::from_str::<SiteTitle>("\"Jaunder\"").unwrap(),
            "Jaunder".parse::<SiteTitle>().unwrap()
        );
        assert!(serde_json::from_str::<SiteTitle>("\"\"").is_err());
    }

    #[test]
    fn site_title_default_is_the_app_default() {
        assert_eq!(SiteTitle::default(), DEFAULT_SITE_TITLE);
    }

    #[test]
    fn site_tagline_parses_plain_single_line_text() {
        assert_eq!(
            "  Привет  мир  ".parse::<SiteTagline>().unwrap(),
            "Привет  мир"
        );
        assert_eq!(
            "x".repeat(280)
                .parse::<SiteTagline>()
                .unwrap()
                .chars()
                .count(),
            280
        );
    }

    #[test]
    fn site_tagline_rejects_blank_overlong_and_every_line_separator() {
        assert!(" \t ".parse::<SiteTagline>().is_err());
        assert!("x".repeat(281).parse::<SiteTagline>().is_err());
        for separator in ['\r', '\n', '\u{0085}', '\u{2028}', '\u{2029}'] {
            assert!(
                format!("before{separator}after")
                    .parse::<SiteTagline>()
                    .is_err()
            );
        }
    }

    #[test]
    fn site_tagline_serde_validates_and_optional_identity_field_is_compatible() {
        let tagline: SiteTagline = "A tagline".parse().unwrap();
        assert_eq!(serde_json::to_string(&tagline).unwrap(), "\"A tagline\"");
        assert!(serde_json::from_str::<SiteTagline>("\"line\\nbreak\"").is_err());
        let identity: SiteIdentity =
            serde_json::from_str("{\"title\":\"Jaunder\",\"base_url\":null}").unwrap();
        assert_eq!(identity.tagline, None);
        assert!(
            !serde_json::to_string(&identity)
                .unwrap()
                .contains("tagline")
        );
    }
}
