use std::str::FromStr;

use macros::StrNewtype;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::absolute_url::AbsoluteUrl;

/// Site-wide identity and configuration.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SiteIdentity {
    /// Human-facing title for the site, used in feed metadata and similar contexts.
    pub title: SiteTitle,
    /// Public-facing base URL (an absolute `http(s)` origin, normalized to its
    /// canonical form with a trailing slash), if set. When absent, callers emit
    /// root-relative URLs.
    pub base_url: Option<AbsoluteUrl>,
}

/// Default site title when no custom value is configured.
pub const DEFAULT_SITE_TITLE: &str = "Jaunder";

/// The site's human-facing title — surrounding whitespace trimmed, non-empty, casing and
/// interior whitespace preserved. The **validating** counterpart of the infallible
/// [`PostTitle`](crate::post_title::PostTitle); modelled on
/// [`DisplayName`](crate::display_name::DisplayName). No length cap (#580).
///
/// Constructed via [`FromStr`] — the single validating/normalizing chokepoint; the rest of the
/// ADR-0063 string-newtype trailer (`Display`, `AsRef<str>`, `Borrow<str>`, `Deref<Target = str>`,
/// owned `String` conversions, `PartialEq<str>`/`<&str>`, and the validating serde bridge) is
/// generated by `#[derive(StrNewtype)]`, so a `SiteTitle` serializes as a plain string and
/// rejects an empty value on the wire — safe as a (de)serialized DTO field.
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct SiteTitle(String);

/// Error returned when a string cannot be parsed as a [`SiteTitle`].
#[derive(Debug, Error)]
#[error("site title cannot be empty")]
pub struct InvalidSiteTitle;

impl FromStr for SiteTitle {
    type Err = InvalidSiteTitle;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.is_empty() {
            return Err(InvalidSiteTitle);
        }
        Ok(SiteTitle(trimmed.to_owned()))
    }
}

impl Default for SiteTitle {
    /// The app's canonical default ([`DEFAULT_SITE_TITLE`]) — the infallible construction door
    /// `get_identity` uses when no custom title is configured. `DEFAULT_SITE_TITLE` is non-empty,
    /// so the default is itself a valid `SiteTitle`.
    fn default() -> Self {
        Self(DEFAULT_SITE_TITLE.to_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn site_title_parses_trims_and_preserves_inner_and_casing() {
        assert_eq!("  My Blog  ".parse::<SiteTitle>().unwrap(), "My Blog");
        assert_eq!("A B".parse::<SiteTitle>().unwrap(), "A B");
        assert_eq!("Москва".parse::<SiteTitle>().unwrap(), "Москва");
    }

    #[test]
    fn site_title_rejects_empty_and_whitespace_only() {
        assert!("".parse::<SiteTitle>().is_err());
        assert!("   ".parse::<SiteTitle>().is_err());
        assert_eq!(
            "".parse::<SiteTitle>().unwrap_err().to_string(),
            "site title cannot be empty"
        );
    }

    #[test]
    fn site_title_display_and_partial_eq_str() {
        let t: SiteTitle = "Jaunder".parse().unwrap();
        assert_eq!(t.to_string(), "Jaunder");
        assert_eq!(t, "Jaunder"); // generated PartialEq<&str>
    }

    #[test]
    fn site_title_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let t: SiteTitle = "Jaunder".parse().unwrap();
        assert_eq!(serde_json::to_string(&t).unwrap(), "\"Jaunder\"");
        assert_eq!(
            serde_json::from_str::<SiteTitle>("\"Jaunder\"").unwrap(),
            "Jaunder".parse::<SiteTitle>().unwrap()
        );
        assert!(serde_json::from_str::<SiteTitle>("\"\"").is_err());
    }

    #[test]
    fn site_title_default_is_the_app_default() {
        assert_eq!(SiteTitle::default(), DEFAULT_SITE_TITLE);
    }
}
