use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A validated, canonical tag slug matching `[a-z0-9][a-z0-9-]*` (lowercased).
///
/// The tag's *identity*: the browse key (`/tags/:slug`), the dedup key, and the
/// SQL key. Constructed via [`FromStr`]; invalid strings are rejected at the
/// boundary so interior code works only with already-valid tags. The trailer
/// (`Display`, `AsRef`/`Borrow`/`Deref<str>`, owned-`String` conversions,
/// `PartialEq<str>`/`PartialEq<&str>`, and the validating serde bridge that
/// serializes as a plain string) is generated by `#[derive(StrNewtype)]`
/// (ADR-0063); only the normalizing `FromStr` below is hand-written. Keeps
/// `Hash`/`Ord` — `Tag` is a `HashSet`/`BTreeSet`/`HashMap` key. See also
/// [`TagLabel`], the case-preserving label whose [`slug`](TagLabel::slug) is a
/// `Tag`.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, StrNewtype)]
pub struct Tag(String);

/// Error returned when a string cannot be parsed as a [`Tag`].
#[derive(Debug, Error)]
#[error("tag must be non-empty and match [a-z0-9][a-z0-9-]*")]
pub struct InvalidTag;

impl FromStr for Tag {
    type Err = InvalidTag;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s.is_empty() {
            return Err(InvalidTag);
        }
        let normalized = s.to_lowercase();
        let mut chars = normalized.chars();
        // First character must be alphanumeric (lowercase)
        let first = chars.next().ok_or(InvalidTag)?;
        if !first.is_ascii_lowercase() && !first.is_ascii_digit() {
            return Err(InvalidTag);
        }
        // Remaining characters: lowercase alphanumeric or hyphen
        if !chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-') {
            return Err(InvalidTag);
        }
        Ok(Tag(normalized))
    }
}

/// A validated, case-preserving tag label: the author's original spelling of a
/// tag whose canonical slug ([`Tag`]) is guaranteed valid.
///
/// Where a [`Tag`] is the identity, a `TagLabel` is one *tagging*'s presentation
/// (post A tags "Rust", post B tags "rust"; both share the `Tag` "rust"). Built
/// via [`FromStr`], which trims, rejects empty, and validates that the trimmed
/// input has a valid canonical form — the original casing is preserved. The
/// trailer (incl. the serde bridge that serializes as the label string) is
/// generated by `#[derive(StrNewtype)]`; equality is on the raw label, so "same
/// tag" comparisons must go through [`slug`](Self::slug). No `Hash`/`Ord` —
/// never a map/set key (identity is always the `Tag`).
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct TagLabel(String);

/// Error returned when a string cannot be parsed as a [`TagLabel`].
#[derive(Debug, Error)]
#[error("tag must be non-empty and match [a-z0-9][a-z0-9-]* (case preserved)")]
pub struct InvalidTagLabel;

impl FromStr for TagLabel {
    type Err = InvalidTagLabel;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        // Validity is Tag's rule (the single source of truth); the casing of the
        // trimmed input is preserved rather than lowercased.
        Tag::from_str(trimmed).map_err(|_| InvalidTagLabel)?;
        Ok(TagLabel(trimmed.to_owned()))
    }
}

impl TagLabel {
    /// The canonical slug. Infallible: `TagLabel`'s inner string already parses
    /// as a `Tag` (the [`FromStr`] invariant), and both types live in this
    /// module, so the canonical `Tag` is built directly from the label's
    /// lowercase — the exact normalization `Tag::from_str` would produce.
    #[must_use]
    pub fn slug(&self) -> Tag {
        Tag(self.0.to_lowercase())
    }
}

/// Every canonical slug is a valid label (for catalog rows that carry no author
/// casing, e.g. the `list_tags` autocomplete).
impl From<Tag> for TagLabel {
    fn from(value: Tag) -> Self {
        TagLabel(value.0)
    }
}

/// Hard upper bound on tags per post. Enforced by [`parse_and_validate_tags`].
pub const MAX_TAGS_PER_POST: usize = 25;

/// Error returned when a tag list fails validation in
/// [`parse_and_validate_tags`].
#[derive(Debug, Error, PartialEq, Eq)]
pub enum TagValidationError {
    /// The number of distinct tags exceeded [`MAX_TAGS_PER_POST`].
    #[error("too many tags ({count} > {max})")]
    TooMany {
        /// The number of distinct tags supplied.
        count: usize,
        /// The enforced maximum ([`MAX_TAGS_PER_POST`]).
        max: usize,
    },
}

/// De-duplicates a list of already-validated [`TagLabel`]s and enforces the
/// per-post cap.
///
/// Each [`TagLabel`] is already non-empty and slug-valid (its `FromStr` ran at
/// the boundary), so this only de-duplicates by canonical [`slug`](TagLabel::slug)
/// — preserving the first occurrence's label casing — and enforces the
/// [`MAX_TAGS_PER_POST`] cap.
///
/// Returns the deduplicated labels in input order.
///
/// # Errors
///
/// Returns [`TagValidationError::TooMany`] if the number of distinct tags
/// exceeds [`MAX_TAGS_PER_POST`].
pub fn parse_and_validate_tags(raw: Vec<TagLabel>) -> Result<Vec<TagLabel>, TagValidationError> {
    use std::collections::HashSet;

    // Dedup on the canonical Tag (Hash) while preserving the first occurrence's
    // label casing in `out`.
    let mut seen: HashSet<Tag> = HashSet::new();
    let mut out: Vec<TagLabel> = Vec::with_capacity(raw.len().min(MAX_TAGS_PER_POST));
    for label in raw {
        if seen.insert(label.slug()) {
            out.push(label);
        }
    }
    if out.len() > MAX_TAGS_PER_POST {
        return Err(TagValidationError::TooMany {
            count: out.len(),
            max: MAX_TAGS_PER_POST,
        });
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tag_parses_valid_values() {
        assert!("hello-world".parse::<Tag>().is_ok());
        assert!("abc123".parse::<Tag>().is_ok());
        assert!("a".parse::<Tag>().is_ok());
        assert!("0".parse::<Tag>().is_ok());
        assert!("my-tag-2024".parse::<Tag>().is_ok());
    }

    #[test]
    fn tag_rejects_invalid_values() {
        // empty
        assert!("".parse::<Tag>().is_err());
        // starts with hyphen
        assert!("-hello".parse::<Tag>().is_err());
        // spaces
        assert!("hello world".parse::<Tag>().is_err());
        // underscore
        assert!("hello_world".parse::<Tag>().is_err());
        // special chars
        assert!("hello@world".parse::<Tag>().is_err());
    }

    #[test]
    fn tag_normalizes_to_lowercase() {
        let tag: Tag = "Hello-World".parse().unwrap();
        assert_eq!(tag.to_string(), "hello-world");
        assert_eq!(tag, "hello-world");
    }

    #[test]
    fn tag_display_returns_inner_string() {
        let tag: Tag = "my-tag".parse().unwrap();
        assert_eq!(tag.to_string(), "my-tag");
        assert_eq!(tag, "my-tag");
    }

    #[test]
    fn tag_normalizes_uppercase() {
        // `Tag::from_str` lowercases, so an uppercase input is accepted.
        assert!("Hello".parse::<Tag>().is_ok());
    }

    #[test]
    fn tag_rejects_non_ascii() {
        // Non-ASCII characters should be rejected
        assert!("café".parse::<Tag>().is_err());
        assert!("日本".parse::<Tag>().is_err());
        assert!("résumé".parse::<Tag>().is_err());
    }

    #[test]
    fn tag_allows_trailing_hyphen() {
        // Trailing hyphens are allowed by the pattern [a-z0-9][a-z0-9-]*
        assert!("hello-".parse::<Tag>().is_ok());
        assert!("tag-".parse::<Tag>().is_ok());
        assert_eq!("hello-".parse::<Tag>().unwrap(), "hello-");
    }

    #[test]
    fn tag_allows_hyphen_in_middle() {
        assert!("hello-world-tag".parse::<Tag>().is_ok());
        assert!("a-b-c-d".parse::<Tag>().is_ok());
        assert!("tag-1-2-3".parse::<Tag>().is_ok());
    }

    #[test]
    fn tag_allows_all_digits() {
        assert!("123".parse::<Tag>().is_ok());
        assert!("999".parse::<Tag>().is_ok());
        assert!("1".parse::<Tag>().is_ok());
    }

    #[test]
    fn tag_lowercase_normalization_various_cases() {
        let tag1: Tag = "ABC".parse().unwrap();
        assert_eq!(tag1, "abc");

        let tag2: Tag = "MixedCase".parse().unwrap();
        assert_eq!(tag2, "mixedcase");

        let tag3: Tag = "UPPERCASE-TAG-123".parse().unwrap();
        assert_eq!(tag3, "uppercase-tag-123");
    }

    #[test]
    fn tag_allows_consecutive_hyphens() {
        assert!("hello--world".parse::<Tag>().is_ok());
    }

    #[test]
    fn tag_rejects_starting_with_symbol() {
        assert!("#tag".parse::<Tag>().is_err());
        assert!("@tag".parse::<Tag>().is_err());
        assert!("+tag".parse::<Tag>().is_err());
        assert!("=tag".parse::<Tag>().is_err());
    }

    #[test]
    fn tag_clone_and_equality() {
        let tag1: Tag = "test-tag".parse().unwrap();
        let tag2 = tag1.clone();
        assert_eq!(tag1, tag2);
        assert_eq!(tag1.to_string(), tag2.to_string());
    }

    #[test]
    fn tag_hash_consistency() {
        use std::collections::HashSet;
        let tag1: Tag = "test".parse().unwrap();
        let tag2: Tag = "test".parse().unwrap();
        let tag3: Tag = "other".parse().unwrap();

        let mut set = HashSet::new();
        set.insert(tag1);
        set.insert(tag2); // Should not add duplicate
        set.insert(tag3);

        assert_eq!(set.len(), 2);
    }

    #[test]
    fn invalid_tag_error_display() {
        let err: InvalidTag = InvalidTag;
        let message = err.to_string();
        assert!(message.contains("tag must be non-empty"));
        assert!(message.contains("[a-z0-9][a-z0-9-]*"));
    }

    #[test]
    fn invalid_tag_error_debug() {
        let err: InvalidTag = InvalidTag;
        let debug_str = format!("{err:?}");
        assert_eq!(debug_str, "InvalidTag");
    }

    #[test]
    fn tag_formats_correctly() {
        use std::fmt::Write;
        let tag: Tag = "format-test".parse().unwrap();
        let mut buf = String::new();
        let _ = write!(buf, "{tag}");
        assert_eq!(buf, "format-test");
    }

    #[test]
    fn tag_debug_impl() {
        let tag: Tag = "debug-tag".parse().unwrap();
        let debug_str = format!("{tag:?}");
        assert!(debug_str.contains("debug-tag"));
    }

    #[test]
    fn tag_very_long_valid_tag() {
        let long_tag = "a".repeat(100);
        let tag = long_tag.parse::<Tag>();
        assert!(tag.is_ok());
        assert_eq!(tag.unwrap(), long_tag.as_str());
    }

    #[test]
    fn tag_mixed_case_long_tag() {
        let long_tag = "LongTagWithManyCharacters".repeat(4);
        let tag = long_tag.parse::<Tag>();
        assert!(tag.is_ok());
        assert_eq!(tag.unwrap(), long_tag.to_lowercase().as_str());
    }

    #[test]
    fn tag_single_digit() {
        assert!("0".parse::<Tag>().is_ok());
        assert!("5".parse::<Tag>().is_ok());
        assert!("9".parse::<Tag>().is_ok());
        assert_eq!("7".parse::<Tag>().unwrap(), "7");
    }

    #[test]
    fn tag_consecutive_hyphens() {
        assert!("a--b".parse::<Tag>().is_ok());
        assert!("a---b".parse::<Tag>().is_ok());
        assert_eq!("test--tag".parse::<Tag>().unwrap(), "test--tag");
    }

    #[test]
    fn invalid_tag_various_special_chars() {
        assert!("tag!".parse::<Tag>().is_err());
        assert!("tag&".parse::<Tag>().is_err());
        assert!("tag%".parse::<Tag>().is_err());
        assert!("tag$".parse::<Tag>().is_err());
        assert!("tag^".parse::<Tag>().is_err());
        assert!("tag*".parse::<Tag>().is_err());
        assert!("tag(hello)".parse::<Tag>().is_err());
        assert!("tag[test]".parse::<Tag>().is_err());
        assert!("tag{test}".parse::<Tag>().is_err());
        assert!("tag<test>".parse::<Tag>().is_err());
    }

    #[test]
    fn tag_starting_with_digit() {
        assert!("0tag".parse::<Tag>().is_ok());
        assert!("1test".parse::<Tag>().is_ok());
        assert!("9value".parse::<Tag>().is_ok());
    }

    fn labels(v: &[&str]) -> Vec<TagLabel> {
        v.iter().map(|s| s.parse().unwrap()).collect()
    }

    #[test]
    fn parse_and_validate_tags_deduplicates_repeated_tags() {
        let tags = parse_and_validate_tags(labels(&["rust", "rust", "leptos"]))
            .expect("valid tags should validate");
        assert_eq!(tags, labels(&["rust", "leptos"]));
    }

    #[test]
    fn parse_and_validate_tags_dedups_mixed_case_keeping_first_label() {
        // Dedup is on the canonical (lowercased) slug, so "Rust"/"rust" collapse
        // to one entry; the first occurrence's label casing is preserved.
        let tags = parse_and_validate_tags(labels(&["Rust", "rust", "LEPTOS"]))
            .expect("valid tags should validate");
        assert_eq!(tags, labels(&["Rust", "LEPTOS"]));
    }

    #[test]
    fn parse_and_validate_tags_rejects_too_many_tags() {
        let raw: Vec<TagLabel> = (0..=MAX_TAGS_PER_POST)
            .map(|i| format!("tag{i}").parse().unwrap())
            .collect();
        let err = parse_and_validate_tags(raw).unwrap_err();
        assert_eq!(
            err,
            TagValidationError::TooMany {
                count: MAX_TAGS_PER_POST + 1,
                max: MAX_TAGS_PER_POST
            }
        );
        assert!(err.to_string().contains("too many tags"));
    }

    #[test]
    fn tag_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let t: Tag = "rust".parse().unwrap();
        assert_eq!(serde_json::to_string(&t).unwrap(), "\"rust\"");

        // Deserialize routes through the validating parse (lowercasing too).
        assert_eq!(
            serde_json::from_str::<Tag>("\"Rust\"").unwrap(),
            "rust".parse::<Tag>().unwrap()
        );

        // Invalid input is rejected at deserialize time.
        assert!(serde_json::from_str::<Tag>("\"-bad\"").is_err());
    }

    #[test]
    fn tag_label_preserves_casing_and_derives_slug() {
        let l: TagLabel = "Rust".parse().unwrap();
        assert_eq!(l, "Rust"); // casing preserved (generated PartialEq<&str>)
        assert_eq!(l.to_string(), "Rust"); // Display = label
        assert_eq!(l.slug(), "rust"); // canonical slug is lowercased
    }

    #[test]
    fn tag_label_trims_and_rejects_invalid() {
        assert_eq!(" Rust ".parse::<TagLabel>().unwrap(), "Rust"); // trimmed, cased
        assert!("".parse::<TagLabel>().is_err()); // empty
        assert!("   ".parse::<TagLabel>().is_err()); // whitespace-only
        assert!("bad tag".parse::<TagLabel>().is_err()); // space
        assert!("-x".parse::<TagLabel>().is_err()); // leading hyphen
    }

    #[test]
    fn tag_label_serde_roundtrips_as_label_string() {
        let l: TagLabel = "Rust".parse().unwrap();
        // Serializes as the label (casing preserved), not the slug.
        assert_eq!(serde_json::to_string(&l).unwrap(), "\"Rust\"");
        assert_eq!(serde_json::from_str::<TagLabel>("\"Rust\"").unwrap(), l);
        // Invalid input is rejected at deserialize time.
        assert!(serde_json::from_str::<TagLabel>("\"-bad\"").is_err());
    }

    #[test]
    fn tag_label_from_tag_mirrors_the_slug() {
        let t: Tag = "rust".parse().unwrap();
        assert_eq!(TagLabel::from(t), "rust");
    }

    #[test]
    fn invalid_tag_label_error_display() {
        assert!(InvalidTagLabel
            .to_string()
            .contains("tag must be non-empty"));
    }
}
