use std::str::FromStr;

use macros::StrNewtype;
use thiserror::Error;

/// A validated, canonical tag slug matching `[a-z0-9][a-z0-9-]*` (lowercased).
///
/// The tag's *identity*: the browse key (`/tags/:slug`), the dedup key, and the
/// SQL key. Constructed via [`FromStr`]; invalid strings are rejected at the
/// boundary so interior code works only with already-valid tags. The trailer
/// (`Display`, `AsRef`/`Borrow`/`Deref<str>`, owned-`String` conversions,
/// `PartialEq<str>`/`PartialEq<&str>`, and the validating serde bridge that
/// serializes as a plain string) is generated by `#[derive(StrNewtype)]`
/// (ADR-0063); only the normalizing `FromStr` below is hand-written. Keeps
/// `Hash` — `Tag` is a `HashSet`/`HashMap` key; ordering (for `BTreeSet`) comes
/// from the trailer, so it is not in the derive list. See also [`TagLabel`], the
/// case-preserving label whose [`slug`](TagLabel::slug) is a `Tag`.
#[derive(Clone, Debug, PartialEq, Eq, Hash, StrNewtype)]
pub struct Tag(String);

/// Error returned when a string cannot be parsed as a [`Tag`].
#[derive(Debug, Error)]
#[error("tag must be non-empty and match [a-z0-9][a-z0-9-]*")]
pub struct InvalidTag;

impl FromStr for Tag {
    type Err = InvalidTag;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s.is_empty() {
            return Err(InvalidTag);
        }
        let normalized = s.to_lowercase();
        let mut chars = normalized.chars();
        // First character must be alphanumeric (lowercase)
        let first = chars.next().ok_or(InvalidTag)?;
        if !first.is_ascii_lowercase() && !first.is_ascii_digit() {
            return Err(InvalidTag);
        }
        // Remaining characters: lowercase alphanumeric or hyphen
        if !chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-') {
            return Err(InvalidTag);
        }
        Ok(Tag(normalized))
    }
}

/// A validated, case-preserving tag label: the author's original spelling of a
/// tag whose canonical slug ([`Tag`]) is guaranteed valid.
///
/// Where a [`Tag`] is the identity, a `TagLabel` is one *tagging*'s presentation
/// (post A tags "Rust", post B tags "rust"; both share the `Tag` "rust"). Built
/// via [`FromStr`], which trims, rejects empty, and validates that the trimmed
/// input has a valid canonical form — the original casing is preserved. The
/// trailer (incl. the serde bridge that serializes as the label string) is
/// generated by `#[derive(StrNewtype)]`; equality is on the raw label, so "same
/// tag" comparisons must go through [`slug`](Self::slug). No `Hash` — nothing
/// hashes a `TagLabel`, since identity is always the `Tag`; ordering is emitted
/// by the trailer (ADR-0063 §2).
#[derive(Clone, Debug, PartialEq, Eq, StrNewtype)]
pub struct TagLabel(String);

/// Error returned when a string cannot be parsed as a [`TagLabel`].
#[derive(Debug, Error)]
#[error("tag must be non-empty and match [a-z0-9][a-z0-9-]* (case preserved)")]
pub struct InvalidTagLabel;

impl FromStr for TagLabel {
    type Err = InvalidTagLabel;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        // Validity is Tag's rule (the single source of truth); the casing of the
        // trimmed input is preserved rather than lowercased.
        Tag::from_str(trimmed).map_err(|_| InvalidTagLabel)?;
        Ok(TagLabel(trimmed.to_owned()))
    }
}

impl TagLabel {
    /// The canonical slug. Infallible: `TagLabel`'s inner string already parses
    /// as a `Tag` (the [`FromStr`] invariant), and both types live in this
    /// module, so the canonical `Tag` is built directly from the label's
    /// lowercase — the exact normalization `Tag::from_str` would produce.
    #[must_use]
    pub fn slug(&self) -> Tag {
        Tag(self.0.to_lowercase())
    }
}

/// Every canonical slug is a valid label (for catalog rows that carry no author
/// casing, e.g. the `list_tags` autocomplete).
impl From<Tag> for TagLabel {
    fn from(value: Tag) -> Self {
        TagLabel(value.0)
    }
}

/// Finite resource bound on tags per post, enforced at the shared validation
/// boundary by [`parse_and_validate_tags`].
pub const MAX_TAGS_PER_POST: usize = 256;

/// Error returned when a tag list fails validation in
/// [`parse_and_validate_tags`].
#[derive(Debug, Error, PartialEq, Eq)]
pub enum TagValidationError {
    /// The number of distinct tags exceeded [`MAX_TAGS_PER_POST`].
    #[error("too many tags ({count} > {max})")]
    TooMany {
        /// The number of distinct tags supplied.
        count: usize,
        /// The enforced maximum ([`MAX_TAGS_PER_POST`]).
        max: usize,
    },
}

/// De-duplicates a list of already-validated [`TagLabel`]s and enforces the
/// per-post cap.
///
/// Each [`TagLabel`] is already non-empty and slug-valid (its `FromStr` ran at
/// the boundary), so this only de-duplicates by canonical [`slug`](TagLabel::slug)
/// — preserving the first occurrence's label casing — and enforces the
/// [`MAX_TAGS_PER_POST`] cap.
///
/// Returns the deduplicated labels in input order.
///
/// # Errors
///
/// Returns [`TagValidationError::TooMany`] if the number of distinct tags
/// exceeds [`MAX_TAGS_PER_POST`].
pub fn parse_and_validate_tags(raw: Vec<TagLabel>) -> Result<Vec<TagLabel>, TagValidationError> {
    use std::collections::HashSet;

    // Dedup on the canonical Tag (Hash) while preserving the first occurrence's
    // label casing in `out`.
    let mut seen: HashSet<Tag> = HashSet::new();
    let mut out: Vec<TagLabel> = Vec::with_capacity(raw.len().min(MAX_TAGS_PER_POST));
    for label in raw {
        if seen.insert(label.slug()) {
            out.push(label);
        }
    }
    if out.len() > MAX_TAGS_PER_POST {
        return Err(TagValidationError::TooMany {
            count: out.len(),
            max: MAX_TAGS_PER_POST,
        });
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    use rstest::rstest;

    const LONG_CANONICAL_TAG: &str = concat!(
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
        "aaaaaaaaaa",
    );
    const LONG_MIXED_CASE_TAG: &str = concat!(
        "LongTagWithManyCharacters",
        "LongTagWithManyCharacters",
        "LongTagWithManyCharacters",
        "LongTagWithManyCharacters",
    );
    const LONG_MIXED_CASE_CANONICAL_TAG: &str = concat!(
        "longtagwithmanycharacters",
        "longtagwithmanycharacters",
        "longtagwithmanycharacters",
        "longtagwithmanycharacters",
    );

    #[rstest]
    #[case::canonical_ascii("my-tag-2024", "my-tag-2024")]
    #[case::single_letter("a", "a")]
    #[case::single_digit("7", "7")]
    #[case::leading_digit("0tag", "0tag")]
    #[case::trailing_hyphen("hello-", "hello-")]
    #[case::middle_hyphens("a-b-c-d", "a-b-c-d")]
    #[case::consecutive_hyphens("a---b", "a---b")]
    #[case::uppercase("ABC", "abc")]
    #[case::mixed_case("Hello-World", "hello-world")]
    #[case::mixed_case_with_digits("UPPERCASE-TAG-123", "uppercase-tag-123")]
    #[case::long_canonical(LONG_CANONICAL_TAG, LONG_CANONICAL_TAG)]
    #[case::long_mixed_case(LONG_MIXED_CASE_TAG, LONG_MIXED_CASE_CANONICAL_TAG)]
    fn tag_accepts_and_canonicalizes(#[case] input: &str, #[case] canonical: &str) {
        let tag = input.parse::<Tag>().expect("case input should be accepted");
        assert_eq!(tag, canonical);
    }

    #[rstest]
    #[case::empty("")]
    #[case::leading_hyphen("-hello")]
    #[case::space("hello world")]
    #[case::underscore("hello_world")]
    #[case::leading_symbol("#tag")]
    #[case::embedded_symbol("tag!")]
    #[case::leading_non_ascii("é")]
    #[case::embedded_non_ascii("café")]
    fn tag_rejects_invalid_grammar(#[case] input: &str) {
        assert!(input.parse::<Tag>().is_err());
    }

    #[test]
    fn tag_display_returns_inner_string() {
        let tag: Tag = "my-tag".parse().unwrap();
        assert_eq!(tag.to_string(), "my-tag");
        assert_eq!(tag, "my-tag");
    }

    #[test]
    fn tag_clone_and_equality() {
        let tag1: Tag = "test-tag".parse().unwrap();
        let tag2 = tag1.clone();
        assert_eq!(tag1, tag2);
        assert_eq!(tag1.to_string(), tag2.to_string());
    }

    #[test]
    fn tag_hash_consistency() {
        use std::collections::HashSet;
        let tag1: Tag = "test".parse().unwrap();
        let tag2: Tag = "test".parse().unwrap();
        let tag3: Tag = "other".parse().unwrap();

        let mut set = HashSet::new();
        set.insert(tag1);
        set.insert(tag2); // Should not add duplicate
        set.insert(tag3);

        assert_eq!(set.len(), 2);
    }

    #[test]
    fn invalid_tag_error_display() {
        let err: InvalidTag = InvalidTag;
        let message = err.to_string();
        assert!(message.contains("tag must be non-empty"));
        assert!(message.contains("[a-z0-9][a-z0-9-]*"));
    }

    #[test]
    fn invalid_tag_error_debug() {
        let err: InvalidTag = InvalidTag;
        let debug_str = format!("{err:?}");
        assert_eq!(debug_str, "InvalidTag");
    }

    #[test]
    fn tag_formats_correctly() {
        use std::fmt::Write;
        let tag: Tag = "format-test".parse().unwrap();
        let mut buf = String::new();
        let _ = write!(buf, "{tag}");
        assert_eq!(buf, "format-test");
    }

    #[test]
    fn tag_debug_impl() {
        let tag: Tag = "debug-tag".parse().unwrap();
        let debug_str = format!("{tag:?}");
        assert!(debug_str.contains("debug-tag"));
    }

    fn labels(v: &[&str]) -> Vec<TagLabel> {
        v.iter().map(|s| s.parse().unwrap()).collect()
    }

    #[test]
    fn parse_and_validate_tags_deduplicates_repeated_tags() {
        let tags = parse_and_validate_tags(labels(&["rust", "rust", "leptos"]))
            .expect("valid tags should validate");
        assert_eq!(tags, labels(&["rust", "leptos"]));
    }

    #[test]
    fn parse_and_validate_tags_dedups_mixed_case_keeping_first_label() {
        // Dedup is on the canonical (lowercased) slug, so "Rust"/"rust" collapse
        // to one entry; the first occurrence's label casing is preserved.
        let tags = parse_and_validate_tags(labels(&["Rust", "rust", "LEPTOS"]))
            .expect("valid tags should validate");
        assert_eq!(tags, labels(&["Rust", "LEPTOS"]));
    }

    #[test]
    fn parse_and_validate_tags_accepts_exactly_the_tag_limit() {
        let raw: Vec<TagLabel> = (0..MAX_TAGS_PER_POST)
            .map(|i| format!("tag{i}").parse().unwrap())
            .collect();
        let tags = parse_and_validate_tags(raw).expect("tags at the limit should validate");
        assert_eq!(tags.len(), MAX_TAGS_PER_POST);
    }

    #[test]
    fn parse_and_validate_tags_rejects_too_many_tags() {
        let raw: Vec<TagLabel> = (0..=MAX_TAGS_PER_POST)
            .map(|i| format!("tag{i}").parse().unwrap())
            .collect();
        let err = parse_and_validate_tags(raw).unwrap_err();
        assert_eq!(
            err,
            TagValidationError::TooMany {
                count: MAX_TAGS_PER_POST + 1,
                max: MAX_TAGS_PER_POST
            }
        );
        assert!(err.to_string().contains("too many tags"));
    }

    #[test]
    fn tag_serde_serializes_as_plain_string_and_validates_on_deserialize() {
        let t: Tag = "rust".parse().unwrap();
        assert_eq!(serde_json::to_string(&t).unwrap(), "\"rust\"");

        // Deserialize routes through the validating parse (lowercasing too).
        assert_eq!(
            serde_json::from_str::<Tag>("\"Rust\"").unwrap(),
            "rust".parse::<Tag>().unwrap()
        );

        // Invalid input is rejected at deserialize time.
        assert!(serde_json::from_str::<Tag>("\"-bad\"").is_err());
    }

    #[test]
    fn tag_label_preserves_casing_and_derives_slug() {
        let l: TagLabel = "Rust".parse().unwrap();
        assert_eq!(l, "Rust"); // casing preserved (generated PartialEq<&str>)
        assert_eq!(l.to_string(), "Rust"); // Display = label
        assert_eq!(l.slug(), "rust"); // canonical slug is lowercased
    }

    #[test]
    fn tag_label_trims_and_rejects_invalid() {
        assert_eq!(" Rust ".parse::<TagLabel>().unwrap(), "Rust"); // trimmed, cased
        assert!("".parse::<TagLabel>().is_err()); // empty
        assert!("   ".parse::<TagLabel>().is_err()); // whitespace-only
        assert!("bad tag".parse::<TagLabel>().is_err()); // space
        assert!("-x".parse::<TagLabel>().is_err()); // leading hyphen
    }

    #[test]
    fn tag_label_serde_roundtrips_as_label_string() {
        let l: TagLabel = "Rust".parse().unwrap();
        // Serializes as the label (casing preserved), not the slug.
        assert_eq!(serde_json::to_string(&l).unwrap(), "\"Rust\"");
        assert_eq!(serde_json::from_str::<TagLabel>("\"Rust\"").unwrap(), l);
        // Invalid input is rejected at deserialize time.
        assert!(serde_json::from_str::<TagLabel>("\"-bad\"").is_err());
    }

    #[test]
    fn tag_label_from_tag_mirrors_the_slug() {
        let t: Tag = "rust".parse().unwrap();
        assert_eq!(TagLabel::from(t), "rust");
    }

    #[test]
    fn invalid_tag_label_error_display() {
        assert!(
            InvalidTagLabel
                .to_string()
                .contains("tag must be non-empty")
        );
    }
}
